REM 1c_create_activities.sql
spool 1c_create_activities

Create table strava.activities AS 
select ACTIVITY_ID,ACTIVITY_DATE,ACTIVITY_NAME,ACTIVITY_TYPE,ACTIVITY_DESCRIPTION,
ELAPSED_TIME,DISTANCE_KM,RELATIVE_EFFORT,COMMUTE_CHAR,ACTIVITY_GEAR,
FILENAME,
ATHLETE_WEIGHT,BIKE_WEIGHT,ELAPSED_TIME2,MOVING_TIME,DISTANCE_M,MAX_SPEED,AVERAGE_SPEED,
ELEVATION_GAIN,ELEVATION_LOSS,ELEVATION_LOW,ELEVATION_HIGH,MAX_GRADE,AVERAGE_GRADE,
--AVERAGE_POSITIVE_GRADE,
--AVERAGE_NEGATIVE_GRADE,
MAX_CADENCE,AVERAGE_CADENCE,
--MAX_HEART_RATE,
AVERAGE_HEART_RATE,
--MAX_WATTS,
AVERAGE_WATTS,CALORIES,
--MAX_TEMPERATURE,
--AVERAGE_TEMPERATURE,
RELATIVE_EFFORT2,
TOTAL_WORK,
--NUMBER_OF_RUNS,
--UPHILL_TIME,
--DOWNHILL_TIME,
--OTHER_TIME,
PERCEIVED_EXERTION,
--TYPE,
--START_TIME,
WEIGHTED_AVERAGE_POWER,POWER_COUNT,
PREFER_PERCEIVED_EXERTION,PERCEIVED_RELATIVE_EFFORT,
COMMUTE,
--TOTAL_WEIGHT_LIFTED,
FROM_UPLOAD,
GRADE_ADJUSTED_DISTANCE,
--WEATHER_OBSERVATION_TIME,
--WEATHER_CONDITION,
--WEATHER_TEMPERATURE,
--APPARENT_TEMPERATURE,
--DEWPOINT,
--HUMIDITY,
--WEATHER_PRESSURE,
--WIND_SPEED,
--WIND_GUST,
--WIND_BEARING,
--PRECIPITATION_INTENSITY,
--SUNRISE_TIME,
--SUNSET_TIME,
--MOON_PHASE,
BIKE
--GEAR,
--PRECIPITATION_PROBABILITY,
--PRECIPITATION_TYPE,
--CLOUD_COVER,
--WEATHER_VISIBILITY,
--UV_INDEX,
--WEATHER_OZONE,
--JUMP_COUNT,
--TOTAL_GRIT,
--AVG_FLOW,
--FLAGGED
from strava.activities_ext
/

ALTER TABLE activities ADD CONSTRAINT activities_pk PRIMARY KEY (activity_id);
ALTER TABLE ACTIVITIES MODIFY ACTIVITY_DATE NOT NULL;
ALTER TABLE ACTIVITIES MODIFY ACTIVITY_NAME NOT NULL;
ALTER TABLE ACTIVITIES MODIFY ACTIVITY_TYPE NOT NULL;
ALTER TABLE ACTIVITIES MODIFY AVERAGE_GRADE NOT NULL;
ALTER TABLE ACTIVITIES MODIFY COMMUTE_CHAR NOT NULL;
ALTER TABLE ACTIVITIES MODIFY DISTANCE_KM NOT NULL;
ALTER TABLE ACTIVITIES MODIFY ELAPSED_TIME NOT NULL;
ALTER TABLE ACTIVITIES MODIFY MOVING_TIME NOT NULL;
ALTER TABLE ACTIVITIES MODIFY ACTIVITY_TYPE VARCHAR2(15);

ALTER TABLE activities ADD (gpx XMLTYPE)
XMLTYPE COLUMN gpx STORE AS SECUREFILE BINARY XML (CACHE DISABLE STORAGE IN ROW);

spool off
