REM adb_activity_areas.sql
set echo on timi on
clear screen
spool adb_activity_areas.lst

CREATE TABLE STRAVA.ACTIVITY_AREAS
(ACTIVITY_ID NUMBER NOT NULL
,AREA_CODE   VARCHAR2(4) NOT NULL
,AREA_NUMBER NUMBER NOT NULL
,GEOM_LENGTH NUMBER
,CONSTRAINT ACTIVITY_AREAS_PK PRIMARY KEY (ACTIVITY_ID, AREA_CODE, AREA_NUMBER)
,CONSTRAINT ACTIVITY_AREAS_FK FOREIGN KEY (ACTIVITY_ID) REFERENCES STRAVA.ACTIVITIES (ACTIVITY_ID) ON DELETE CASCADE
,CONSTRAINT ACTIVITY_AREAS_FK2 FOREIGN KEY (AREA_CODE, AREA_NUMBER) REFERENCES STRAVA.MY_AREAS (AREA_CODE, AREA_NUMBER) ON DELETE CASCADE
);

ALTER TABLE STRAVA.ACTIVITY_AREAS
DROP CONSTRAINT ACTIVITY_AREAS_FK 
/
ALTER TABLE STRAVA.ACTIVITY_AREAS
DROP CONSTRAINT ACTIVITY_AREAS_FK2
/

ALTER TABLE STRAVA.ACTIVITY_AREAS
ADD CONSTRAINT ACTIVITY_AREAS_FK FOREIGN KEY (ACTIVITY_ID) REFERENCES STRAVA.ACTIVITIES (ACTIVITY_ID)
ON DELETE CASCADE
/

ALTER TABLE STRAVA.ACTIVITY_AREAS
ADD CONSTRAINT ACTIVITY_AREAS_FK2 FOREIGN KEY (AREA_CODE, AREA_NUMBER) REFERENCES STRAVA.MY_AREAS (AREA_CODE, AREA_NUMBER)
ON DELETE CASCADE
/

CREATE OR REPLACE TRIGGER strava.activity_areas_delete
BEFORE DELETE ON strava.activity_areas
FOR EACH ROW
DECLARE
  e_mutation EXCEPTION;
  PRAGMA EXCEPTION_INIT(e_mutation,-4091);
BEGIN
  UPDATE ACTIVITIES
  SET    processing_status = 4
  WHERE  activity_id = :old.ACTIVITY_ID
  AND    processing_status BETWEEN 5 and 8;
EXCEPTION
  WHEN e_mutation THEN 
    dbms_output.put_line('Ignoring '||sqlerrm);
END;
/
show errors

spool off
