REM adb_my_areas.sql
spool adb_my_areas.lst
clear screen
set echo on

--ALTER SYSTEM SET SECUREFILE_LARGE_OBJECT_COMPRESSION=HIGH;

  CREATE TABLE STRAVA.MY_AREAS 
   (AREA_CODE VARCHAR2(4 CHAR) NOT NULL , 
	AREA_NUMBER NUMBER(*,0) NOT NULL , 
	UQID VARCHAR2(20 CHAR) NOT NULL , 
	WIKIDATAID VARCHAR2(20 CHAR), 
	AREA_LEVEL NUMBER(*,0) NOT NULL , 
	PARENT_AREA_CODE VARCHAR2(4 CHAR), 
	PARENT_AREA_NUMBER NUMBER(*,0), 
	PARENT_UQID VARCHAR2(20 CHAR), 
	NAME VARCHAR2(60 CHAR), 
	ISO_CODE3 VARCHAR2(3 CHAR), 
	ISO_CODE2 VARCHAR2(5 CHAR), 
	ISO_NUMBER NUMBER(*,0), 
	NUM_CHILDREN NUMBER(*,0), 
	MATCHABLE NUMBER(*,0) DEFAULT 1, 
  --CONTINENT VARCHAR2(30 CHAR), 
  --REGION_UN VARCHAR2(30 CHAR), 
  --SUBREGION VARCHAR2(30 CHAR), 
  --REGION_WB VARCHAR2(30 CHAR), 
	GEOM MDSYS.SDO_GEOMETRY , 
	--GEOM_27700 MDSYS.SDO_GEOMETRY , 
	MBR MDSYS.SDO_GEOMETRY , 
	SUFFIX VARCHAR2(20 CHAR), 
	NUM_PTS NUMBER(*,0), 
	NAME_HIERARCHY VARCHAR2(4000 CHAR), 
	 CONSTRAINT MY_AREAS_UQ_ISO_CODE3 UNIQUE (ISO_CODE3), 
	 CONSTRAINT MY_AREAS2_PK PRIMARY KEY (AREA_CODE, AREA_NUMBER)
  USING INDEX (CREATE UNIQUE INDEX STRAVA.MY_AREAS_PK ON STRAVA.MY_AREAS (AREA_CODE, AREA_NUMBER)), 
	 CONSTRAINT MY_AREAS_CHECK_PARENT_AREA_CODE CHECK (area_code != parent_area_code OR area_number != parent_area_number), 
	 CONSTRAINT MY_AREAS_CHECK_PARENT_UQID CHECK (uqid != parent_uqid) , 
	 CONSTRAINT MY_AREAS_CHECK_MATCHABLE CHECK (matchable IN(0,1)) , 
	 CONSTRAINT MY_AREAS_UQID UNIQUE (UQID) , 
	 CONSTRAINT MY_AREAS_RFK_UQID FOREIGN KEY (PARENT_UQID) REFERENCES STRAVA.MY_AREAS (UQID) , 
	 CONSTRAINT MY_AREAS_RFK_AREA_CODE FOREIGN KEY (PARENT_AREA_CODE, PARENT_AREA_NUMBER) REFERENCES STRAVA.MY_AREAS (AREA_CODE, AREA_NUMBER) , 
	 CONSTRAINT MY_AREAS_FK_AREA_CODE FOREIGN KEY (AREA_CODE) REFERENCES STRAVA.MY_AREA_CODES (AREA_CODE) ENABLE
   )  
 VARRAY GEOM.SDO_ELEM_INFO       STORE AS SECUREFILE LOB ( ENABLE STORAGE IN ROW 4000 CHUNK 8192 COMPRESS HIGH DEDUPLICATE LOB) 
 VARRAY GEOM.SDO_ORDINATES       STORE AS SECUREFILE LOB ( ENABLE STORAGE IN ROW 4000 CHUNK 8192 COMPRESS HIGH DEDUPLICATE LOB) 
 --VARRAY GEOM_27700.SDO_ELEM_INFO STORE AS SECUREFILE LOB ( ENABLE STORAGE IN ROW 4000 CHUNK 8192 COMPRESS HIGH DEDUPLICATE LOB) 
 --VARRAY GEOM_27700.SDO_ORDINATES STORE AS SECUREFILE LOB ( ENABLE STORAGE IN ROW 4000 CHUNK 8192 COMPRESS HIGH DEDUPLICATE LOB) 
 VARRAY MBR.SDO_ELEM_INFO        STORE AS SECUREFILE LOB ( ENABLE STORAGE IN ROW 4000 CHUNK 8192 COMPRESS HIGH DEDUPLICATE LOB) 
 VARRAY MBR.SDO_ORDINATES        STORE AS SECUREFILE LOB ( ENABLE STORAGE IN ROW 4000 CHUNK 8192 COMPRESS HIGH DEDUPLICATE LOB)
 /
 
 SELECT table_name, column_name, segment_name, compression, securefile
FROM user_lobs
WHERE table_name = 'MY_AREAS';

--ALTER SYSTEM SET SECUREFILE_LARGE_OBJECT_COMPRESSION=HIGH;
--ALTER TABLE my_areas MOVE LOB (geom.SDO_ELEM_INFO) STORE AS SECUREFILE ( COMPRESS HIGH DEDUPLICATE LOB);


drop INDEX STRAVA.MY_AREAS_NAME_TXTIDX;
alter table my_areas modify area_code varchar2(4 char);
alter table my_areas modify parent_area_code varchar2(4 char);
alter table my_areas modify parent_uqid varchar2(20 char);
alter table my_areas modify name varchar2(60 char);
alter table my_areas modify iso_code2 varchar2(5 char);
alter table my_areas modify iso_code3 varchar2(3 char);
--alter table my_areas modify continent varchar2(30 char);
--alter table my_areas modify region_un varchar2(30 char);
--alter table my_areas modify subregion varchar2(30 char);
--alter table my_areas modify region_wb varchar2(30 char);
alter table my_areas modify suffix varchar2(20 char);

CREATE INDEX STRAVA.MY_AREAS_RFK_UQID ON STRAVA.MY_AREAS (PARENT_UQID) ;
CREATE INDEX STRAVA.MY_AREAS_RFK_AREA_CODE ON STRAVA.MY_AREAS (PARENT_AREA_CODE, PARENT_AREA_NUMBER);

DROP INDEX STRAVA.MY_AREAS_NAME_TXTIDX;
CREATE INDEX STRAVA.MY_AREAS_NAME_TXTIDX ON STRAVA.MY_AREAS (NAME) 
   INDEXTYPE IS CTXSYS.CONTEXT  PARAMETERS ('datastore my_areas_datastore lexer my_areas_lexer sync(on commit)');

CREATE INDEX STRAVA.MY_AREAS_GEOM ON STRAVA.MY_AREAS (GEOM) INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2 ;
CREATE INDEX STRAVA.MY_AREAS_MBR ON STRAVA.MY_AREAS (MBR) INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2 ;

--CREATE INDEX STRAVA.MY_AREAS_GEOM_27700 ON STRAVA.MY_AREAS (GEOM_27700) INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2;

UPDATE STRAVA.MY_AREAS 
SET GEOM_27700 = null
where GEOM_27700 is not null
/

ALTER TABLE strava.MY_AREAS DROP COLUMN geom_27700;
ALTER TABLE strava.MY_AREAS DROP COLUMN CONTINENT;
ALTER TABLE strava.MY_AREAS DROP COLUMN REGION_UN;
ALTER TABLE strava.MY_AREAS DROP COLUMN SUBREGION;
ALTER TABLE strava.MY_AREAS DROP COLUMN REGION_WB; 


ALTER TABLE STRAVA.MY_AREAS 
ADD last_updated TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP;

CREATE OR REPLACE TRIGGER strava.my_areas_last_updated
BEFORE INSERT OR UPDATE ON my_areas
FOR EACH ROW
BEGIN
  :new.last_updated := SYSTIMESTAMP;
END;
/


CREATE OR REPLACE TRIGGER strava.my_areas_update_geom
AFTER UPDATE OF geom, mbr, matchable, num_children, parent_area_code, parent_area_number, parent_uqid 
ON my_areas
FOR EACH ROW
BEGIN
  UPDATE ACTIVITIES
  SET    processing_status = 3
  WHERE  processing_status BETWEEN 4 AND 8
  AND    activity_id IN (
    SELECT activity_id
    FROM   activity_areas
    WHERE  area_code = :new.area_code
	AND area_number = :new.area_number
  );
END;
/
CREATE OR REPLACE TRIGGER strava.my_areas_update_name
AFTER UPDATE OF name
ON my_areas
FOR EACH ROW
BEGIN
  UPDATE ACTIVITIES
  SET    processing_status = 4
  WHERE  processing_status BETWEEN 5 AND 8
  AND    activity_id IN (
    SELECT activity_id
    FROM   activity_areas
    WHERE  area_code = :new.area_code 
	AND area_number = :new.area_number
  );
END;
/
show errors

/*one time update last_updatedd
ALTER TRIGGER strava.my_areas_last_updated DISABLE;
UPDATE my_areas set last_updated = TO_DATE('01012020','DDMMYYYY');
COMMIT;
*/
ALTER TRIGGER strava.my_areas_last_updated ENABLE;

alter table strava.my_areas MOVE TABLESPACE data UPDATE INDEXES;

desc my_areas
show errors
spool off