REM france_load_regions.sql
REM https://adresse.data.gouv.fr/data/contours-administratifs/latest
REM https://adresse.data.gouv.fr/data/contours-administratifs/latest/geojson/regions-5m.geojson


--DROP TABLE strava.stage_geo_data PURGE;
CREATE TABLE strava.stage_geo_data (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name        varchar2(200),
    geo_json    clob,
    geom        MDSYS.SDO_GEOMETRY
);
ALTER TABLE strava.stage_geo_data ADD CONSTRAINT stage_geo_data_pk PRIMARY KEY(id);
ALTER TABLE strava.stage_geo_data ADD CONSTRAINT stage_geo_data_uk UNIQUE(name);

--area staging table - one row per geometry
DROP TABLE stage_my_areas PURGE;
CREATE TABLE stage_my_areas (
    AREA_CODE VARCHAR2(4 CHAR) NOT NULL , 
	AREA_NUMBER NUMBER(*,0) NOT NULL , 
	UQID VARCHAR2(20 CHAR) NOT NULL , 
 	AREA_LEVEL NUMBER(*,0), 
	PARENT_AREA_CODE VARCHAR2(4 CHAR), 
	PARENT_AREA_NUMBER NUMBER(*,0), 
	PARENT_UQID VARCHAR2(20 CHAR), 
	NAME VARCHAR2(100 CHAR), 
	MATCHABLE NUMBER(*,0) DEFAULT 1, 
    NUM_CHILDREN NUMBER(*,0) DEFAULT 0,
--
    GEOM MDSYS.SDO_GEOMETRY ,
	MBR MDSYS.SDO_GEOMETRY , 
	AREA NUMBER,
	NUM_PTS NUMBER(*,0)    
);

ALTER TABLE stage_my_areas ADD CONSTRAINT stage_my_areas_pk PRIMARY KEY (area_code, area_number);
ALTER TABLE stage_my_areas ADD CONSTRAINT stage_my_areas_pk2 UNIQUE (uqid);

INSERT INTO USER_SDO_GEOM_METADATA (
    TABLE_NAME,
    COLUMN_NAME,
    DIMINFO,
    SRID
) VALUES (
    'STAGE_GEO_DATA',
    'GEOM',
    SDO_DIM_ARRAY(
        SDO_DIM_ELEMENT('Longitude', -180, 180, 0.005),
        SDO_DIM_ELEMENT('Latitude',  -90,  90, 0.005)
    ),
    4326
);

INSERT INTO USER_SDO_GEOM_METADATA (
    TABLE_NAME,
    COLUMN_NAME,
    DIMINFO,
    SRID
) VALUES (
    'STAGE_MY_AREAS',
    'GEOM',
    SDO_DIM_ARRAY(
        SDO_DIM_ELEMENT('Longitude', -180, 180, 0.005),
        SDO_DIM_ELEMENT('Latitude',  -90,  90, 0.005)
    ),
    4326
);

DROP INDEX strava.stage_geo_data_sidx
/

----------------------------------------------------------------------------------------------------
--load json FROM https://adresse.data.gouv.fr/data/contours-administratifs/latest/geojson
----------------------------------------------------------------------------------------------------
clear screen
set serveroutput on 
set timi on
--TRUNCATE TABLE strava.stage_geo_data;
delete from strava.stage_geo_data where name = 'France Regions';
DECLARE 
  l_url VARCHAR2(1000)
  := 'https://adresse.data.gouv.fr/data/contours-administratifs/latest/geojson/regions-5m.geojson';
  
  l_clob CLOB;
BEGIN
  DBMS_LOB.createtemporary(l_clob, TRUE);
  l_clob:=strava_http.http_request(l_url);
  
  --strava_http.print_clob(l_clob);
  --strava_sdo.parse_geojson(l_clob);
  
    INSERT INTO strava.stage_geo_data(name, geo_json)
    VALUES ('France Regions', l_clob);

    COMMIT;
END;
/

----------------------------------------------------------------------------------------------------
--list what we have loaded in main table
----------------------------------------------------------------------------------------------------
--staging data loaded FROM web
SELECT x.*, length(geo_json) FROM strava.stage_geo_data x;
--SELECT * FROM my_area_codes ORDER BY area_level;
COMMIT;

select * from my_areas 
--where name = 'France';
where (area_code = 'SOV' and area_number = 1159320629)
or (parent_area_code = 'SOV' and parent_area_number = 1159320629)
/
/*SOV	1159320629	France
GEOU	1159320651	France
GEOU	1159320653	Guadeloupe
GEOU	1159320655	French Guiana
GEOU	1159320657	Martinique
GEOU	1159320659	Mayotte
GEOU	1159320661	Reunion
DEPC	1159320631	French Southern and Antarctic Lands
DEPC	1159320633	Saint Barthelemy
DEPC	1159320635	Clipperton Island
DEPC	1159320639	Saint Martin
DEPC	1159320641	New Caledonia
DEPC	1159320643	French Polynesia
DEPC	1159320647	Saint Pierre and Miquelon
DEPC	1159320649	Wallis and Futuna
*/
----------------------------------------------------------------------------------------------------
--parse geo_json FROM staging tables
--SELECT UTL_HTTP.get_detailed_sqlerrm FROM dual;
--value := UTL_HTTP.get_header(resp, 'Location'); --get redirection URL in header
--note handling of redirect, can limit redirect
--note exception handler for sdo_util.from_geojson and then using alterntive manual procedure, but much slower than native
----------------------------------------------------------------------------------------------------
clear screen
set serveroutput on echo on timi on
TRUNCATE TABLE stage_my_areas;
DECLARE 
  l_clob        CLOB;
  j_root        JSON_OBJECT_T;
  j_crs         JSON_OBJECT_T;
  j_features    JSON_ARRAY_T;
  j_feature     JSON_OBJECT_T;
  j_properties  JSON_OBJECT_T;
  j_geometry    JSON_OBJECT_T;

  l_geom        MDSYS.SDO_GEOMETRY;

  l_id         INTEGER;
  l_srid       VARCHAR2(10 char);
  l_name       VARCHAR2(100 char);
  
  e_json_syntax_error  EXCEPTION;
  PRAGMA exception_init(e_json_syntax_error,-40441);
BEGIN 
  SELECT geo_json INTO l_clob FROM strava.stage_geo_data WHERE name = 'France Regions';
  l_clob := strava_http.clean_clob(l_clob);
  --strava_http.pretty_json(l_clob);
  j_root := JSON_OBJECT_T.parse(l_clob);

  j_crs := j_root.get_object('crs');
  --l_clob := j_crs.to_clob;
  --strava_http.print_clob(l_clob);
	  
  j_features := j_root.get_array('features');
  --l_srid     := REGEXP_SUBSTR(j_crs.get_object('properties').get_string('name'),'[^:]+',1,2);
  l_srid := 4326;
  FOR i IN 0 .. j_features.get_size - 1 LOOP
    j_feature := TREAT(j_features.get(i) AS JSON_OBJECT_T);
    j_properties := j_feature.get_object('properties');
	IF j_properties IS NULL THEN 
	  dbms_output.put_line('J_PROPERTIES is null');
	  l_id := i;
	ELSE
      l_clob := j_properties.to_clob;
	  strava_http.print_clob(l_clob); --use this to understand new GeoJSON file, but comment it out later
	  l_id               := j_properties.get_number('code');
      l_name             := /*initcap_placename*/(j_properties.get_string('nom'));
      dbms_output.put_line(l_id||', '||l_srid||', '||l_name);
	END IF;
	
	IF l_id IS NULL then  
	  l_id := i;
	END IF;

    j_geometry := j_feature.get_object('geometry');
	IF j_geometry IS NULL THEN
	  dbms_output.put_line(l_name||': j_geometry is null');
	  l_geom := NULL;
	ELSE
	  -- Get coordinates array
      l_clob := j_geometry.to_clob;
      
      IF i = -4 THEN
	    strava_http.pretty_json(l_clob);
  	  END IF;

      BEGIN
	    l_geom := sdo_util.from_geojson(l_clob);
	  EXCEPTION 
   	    WHEN e_json_syntax_error THEN
	      dbms_output.put_line(sqlerrm||' during parse of '||l_name||' ('||l_id||'). Switch to own function.' );
    	  l_geom := strava_sdo.build_sdo_geometry_from_geojson(j_geometry, l_srid);
	  END;

  	  l_geom.SDO_SRID := TO_NUMBER(l_srid);
	  IF l_srid != 4326 THEN
  	    l_geom := SDO_CS.TRANSFORM(l_geom, 4326);
   	    l_geom.SDO_SRID := 4326;
	  END IF;
	  l_geom := sdo_util.rectify_Geometry(SDO_CS.MAKE_2D(l_geom),0.001);
	
	END IF;
    
    dbms_output.put_line(i
	      ||','||l_id
		  ||','||l_name
		  );
	--dbms_output.put_line(SDO_UTIL.TO_WKTGEOMETRY(l_geom));
	
	INSERT INTO stage_my_areas
	(area_code, area_number, area_level, uqid, name, geom
	--, mbr, num_pts, area
	) VALUES
	('REG', 250000 + l_id, 5, 'FRAR'||l_id, l_name, l_geom
	--,sdo_geom.sdo_mbr(l_geom)
	--,SDO_UTIL.GETNUMVERTICES(l_geom)
	--,SDO_GEOM.SDO_AREA(l_geom, 0.001,'unit=sq_km')
	);
  END LOOP;
  COMMIT;
END;
/

----------------------------------------------------------------------------------------------------
-- merge mainland metropolitan france into a GEOU - not including Corsica
----------------------------------------------------------------------------------------------------
DELETE FROM stage_my_areas WHERE area_code IN('GEOS','GEOU','SOV');
commit;

INSERT INTO stage_my_areas
(area_code, area_number, uqid, area_level, name, geom, matchable, num_children)
select 'GEOS', 25010, 'FRA25010', 4, 'Mainland Metropolitan France'
, SDO_AGGR_UNION(SDOAGGRTYPE(geom,.0001)), 0, count(*)
from stage_my_areas
where area_code = 'REG'
and area_number BETWEEN 250011 AND 250093 
/
INSERT INTO stage_my_areas
(area_code, area_number, uqid, area_level, name, geom, matchable, num_children)
select 'GEOU', 2501, 'FRA2501', 3, 'Metropolitan France'
, SDO_AGGR_UNION(SDOAGGRTYPE(geom,.0001)), 0, count(*)
from stage_my_areas
where (area_code = 'REG' and area_number = 250094)
or (area_code = 'GEOS' and area_number = 25010)
/
update stage_my_areas
set parent_area_code = 'GEOS'
, parent_area_number = 25010
, parent_uqid = 'FRA25010'
where area_code = 'REG'
and area_number BETWEEN 250011 AND 250093 
/
update stage_my_areas
set parent_area_code = 'GEOU'
, parent_area_number = 2501
, parent_uqid = 'FRA2501'
where (area_code = 'REG' and area_number = 250094)
or (area_code = 'GEOS' and area_number = 25010)
/

----------------------------------------------------------------------------------------------------
--No other french regions touch each other - so this query returns no rows
----------------------------------------------------------------------------------------------------
select /*MATERIALIZE*/
         s.area_code s_area_code, s.area_number s_area_number, s.uqid s_uqid, s.area_level s_area_level, s.name s_name, s.geom s_geom
,        t.area_code t_area_code, t.area_number t_area_number, t.uqid t_uqid, t.area_level t_area_level, t.name t_name, t.geom t_geom
,        sdo_geom.relate(s.geom,'TOUCH',t.geom,1) touching
from   stage_my_areas t, stage_my_areas s
where  s.rowid < t.rowid
and    s.parent_area_code IS null
and    t.parent_area_code IS null
--and    sdo_geom.relate(s.geom,'TOUCH',t.geom,1) = 'TOUCH'
and    SDO_ANYINTERACT(t.geom, s.geom)
and    SDO_ANYINTERACT(t.mbr, s.mbr) 
/


----------------------------------------------------------------------------------------------------
-- Final Merge for Whole of France
----------------------------------------------------------------------------------------------------
DECLARE
  l_counter INTEGER := 0;
  l_geom MDSYS.SDO_GEOMETRY;
BEGIN
  FOR i IN(
    SELECT * FROM stage_my_areas 
	WHERE parent_area_code IS NULL
  ) LOOP
    l_counter := l_counter + 1;
	IF l_counter <= 1 then
	  l_geom := i.geom;
	ELSE
	  l_geom := sdo_geom.sdo_union(l_geom, i.geom);
	END IF;
	UPDATE stage_my_areas
	SET   parent_area_code = 'SOV'
	,     parent_area_number = 250
	,     parent_uqid = 'FRA250'
	WHERE area_code = i.area_code 
	AND   area_number = i.area_number;
  END LOOP;

  INSERT INTO stage_my_areas
  (area_code, area_number, uqid, area_level, name, geom, matchable, num_children)
  VALUES
  ('SOV',250,'FRA250',1,'France',l_geom,1, l_counter);  
END;
/

update stage_my_areas
SET mbr = sdo_geom.sdo_mbr(geom)
, num_pts = SDO_UTIL.GETNUMVERTICES(geom)
, area = SDO_GEOM.SDO_AREA(geom, 0.001,'unit=sq_km')
/
update stage_my_areas
set uqid = 'FRAR'||MOD(area_number,1000)
where area_code = 'REG'
and uqid like 'FRAREG%'
/

----------------------------------------------------------------------------------------------------
-- where are we after loading
----------------------------------------------------------------------------------------------------
select * from stage_my_areas
order by area_level, area_code, area_number
/
select a.*
,SDO_GEOM.SDO_AREA(geom, 0.001,'unit=sq_km') 
from my_areas a
--where name = 'France';
where (area_code = 'GEOU' and area_number = 1159320651)
or (parent_area_code = 'GEOU' and parent_area_number = 1159320651)
/

