REM france_load_departments.sql
REM https://adresse.data.gouv.fr/data/contours-administratifs/latest
REM https://adresse.data.gouv.fr/data/contours-administratifs/latest/geojson/regions-5m.geojson


--DROP TABLE strava.stage_geo_data PURGE;
CREATE TABLE strava.stage_geo_data (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name        varchar2(200),
    geo_json    clob,
    geom        MDSYS.SDO_GEOMETRY
);
ALTER TABLE strava.stage_geo_data ADD CONSTRAINT stage_geo_data_pk PRIMARY KEY(id);
ALTER TABLE strava.stage_geo_data ADD CONSTRAINT stage_geo_data_uk UNIQUE(name);

--area staging table - one row per geometry
DROP TABLE stage_my_areas PURGE;
CREATE TABLE stage_my_areas (
    AREA_CODE VARCHAR2(4 CHAR) NOT NULL , 
	AREA_NUMBER NUMBER(*,0) NOT NULL , 
	UQID VARCHAR2(20 CHAR) NOT NULL , 
 	AREA_LEVEL NUMBER(*,0), 
	PARENT_AREA_CODE VARCHAR2(4 CHAR), 
	PARENT_AREA_NUMBER NUMBER(*,0), 
	PARENT_UQID VARCHAR2(20 CHAR), 
	NAME VARCHAR2(100 CHAR), 
	MATCHABLE NUMBER(*,0) DEFAULT 1, 
    NUM_CHILDREN NUMBER(*,0) DEFAULT 0,
--
    GEOM MDSYS.SDO_GEOMETRY ,
	MBR MDSYS.SDO_GEOMETRY , 
	AREA NUMBER,
	NUM_PTS NUMBER(*,0)    
);

ALTER TABLE stage_my_areas ADD CONSTRAINT stage_my_areas_pk PRIMARY KEY (area_code, area_number);
ALTER TABLE stage_my_areas ADD CONSTRAINT stage_my_areas_pk2 UNIQUE (uqid);

INSERT INTO USER_SDO_GEOM_METADATA (
    TABLE_NAME,
    COLUMN_NAME,
    DIMINFO,
    SRID
) VALUES (
    'STAGE_GEO_DATA',
    'GEOM',
    SDO_DIM_ARRAY(
        SDO_DIM_ELEMENT('Longitude', -180, 180, 0.005),
        SDO_DIM_ELEMENT('Latitude',  -90,  90, 0.005)
    ),
    4326
);

INSERT INTO USER_SDO_GEOM_METADATA (
    TABLE_NAME,
    COLUMN_NAME,
    DIMINFO,
    SRID
) VALUES (
    'STAGE_MY_AREAS',
    'GEOM',
    SDO_DIM_ARRAY(
        SDO_DIM_ELEMENT('Longitude', -180, 180, 0.005),
        SDO_DIM_ELEMENT('Latitude',  -90,  90, 0.005)
    ),
    4326
);

DROP INDEX strava.stage_geo_data_sidx
/

----------------------------------------------------------------------------------------------------
--load json FROM https://adresse.data.gouv.fr/data/contours-administratifs/latest/geojson
----------------------------------------------------------------------------------------------------
clear screen
set serveroutput on 
set timi on
--TRUNCATE TABLE strava.stage_geo_data;
delete from strava.stage_geo_data where name = 'France Departments';
DECLARE 
  l_url VARCHAR2(1000)
  := 'https://adresse.data.gouv.fr/data/contours-administratifs/latest/geojson/departements-5m.geojson';
  
  l_clob CLOB;
BEGIN
  DBMS_LOB.createtemporary(l_clob, TRUE);
  l_clob:=strava_http.http_request(l_url);
  
  --strava_http.print_clob(l_clob);
  --strava_sdo.parse_geojson(l_clob);
  
    INSERT INTO strava.stage_geo_data(name, geo_json)
    VALUES ('France Departments', l_clob);

    COMMIT;
END;
/

----------------------------------------------------------------------------------------------------
--list what we have loaded in main table
----------------------------------------------------------------------------------------------------
--staging data loaded FROM web
SELECT x.*, length(geo_json) FROM strava.stage_geo_data x;
--SELECT * FROM my_area_codes ORDER BY area_level;
COMMIT;

----------------------------------------------------------------------------------------------------
--parse geo_json FROM staging tables
--SELECT UTL_HTTP.get_detailed_sqlerrm FROM dual;
--value := UTL_HTTP.get_header(resp, 'Location'); --get redirection URL in header
--note handling of redirect, can limit redirect
--note exception handler for sdo_util.from_geojson and then using alterntive manual procedure, but much slower than native
----------------------------------------------------------------------------------------------------
clear screen
set serveroutput on echo on timi on
--TRUNCATE TABLE stage_my_areas;
DELETE FROM stage_my_areas where area_code = 'DEPT';
DECLARE 
  l_clob        CLOB;
  j_root        JSON_OBJECT_T;
  j_crs         JSON_OBJECT_T;
  j_features    JSON_ARRAY_T;
  j_feature     JSON_OBJECT_T;
  j_properties  JSON_OBJECT_T;
  j_geometry    JSON_OBJECT_T;

  l_geom        MDSYS.SDO_GEOMETRY;

  l_id         INTEGER;
  l_srid       VARCHAR2(10 char);
  l_name       VARCHAR2(100 char);
  l_deptid     VARCHAR2(10 char);
  l_region     INTEGER;
  
  e_json_syntax_error  EXCEPTION;
  PRAGMA exception_init(e_json_syntax_error,-40441);
BEGIN 
  SELECT geo_json INTO l_clob FROM strava.stage_geo_data WHERE name = 'France Departments';
  l_clob := strava_http.clean_clob(l_clob);
  --strava_http.pretty_json(l_clob);
  j_root := JSON_OBJECT_T.parse(l_clob);

  j_crs := j_root.get_object('crs');
  --l_clob := j_crs.to_clob;
  --strava_http.print_clob(l_clob);
	  
  j_features := j_root.get_array('features');
  --l_srid     := REGEXP_SUBSTR(j_crs.get_object('properties').get_string('name'),'[^:]+',1,2);
  l_srid := 4326;
  FOR i IN 0 .. j_features.get_size - 1 LOOP
    j_feature := TREAT(j_features.get(i) AS JSON_OBJECT_T);
    j_properties := j_feature.get_object('properties');
	IF j_properties IS NULL THEN 
	  dbms_output.put_line('J_PROPERTIES is null');
	  l_id := i;
	ELSE
      l_clob := j_properties.to_clob;
	  strava_http.print_clob(l_clob); --use this to understand new GeoJSON file, but comment it out later
	  l_deptid           := j_properties.get_string('code');
	  l_id := CASE l_deptid WHEN '2A' THEN 101
	                        WHEN '2B' THEN 102
	                        ELSE l_deptid END;
      l_name             := j_properties.get_string('nom');
	  l_region           := j_properties.get_number('region');
      dbms_output.put_line(l_srid||', '||l_deptid||' ('||l_id||'), '||l_name);
	END IF;
	
	IF l_id IS NULL then  
	  l_id := i;
	END IF;

    j_geometry := j_feature.get_object('geometry');
	IF j_geometry IS NULL THEN
	  dbms_output.put_line(l_name||': j_geometry is null');
	  l_geom := NULL;
	ELSE
	  -- Get coordinates array
      l_clob := j_geometry.to_clob;
      
      IF i = -4 THEN
	    strava_http.pretty_json(l_clob);
  	  END IF;

      BEGIN
	    l_geom := sdo_util.from_geojson(l_clob);
	  EXCEPTION 
   	    WHEN e_json_syntax_error THEN
	      dbms_output.put_line(sqlerrm||' during parse of '||l_name||' ('||l_id||'). Switch to own function.' );
    	  l_geom := strava_sdo.build_sdo_geometry_from_geojson(j_geometry, l_srid);
	  END;

  	  l_geom.SDO_SRID := TO_NUMBER(l_srid);
	  IF l_srid != 4326 THEN
  	    l_geom := SDO_CS.TRANSFORM(l_geom, 4326);
   	    l_geom.SDO_SRID := 4326;
	  END IF;
	  l_geom := sdo_util.rectify_Geometry(SDO_CS.MAKE_2D(l_geom),0.001);
	
	END IF;
    
    dbms_output.put_line(i
	      ||','||l_id
		  ||','||l_name
		  );
	--dbms_output.put_line(SDO_UTIL.TO_WKTGEOMETRY(l_geom));
	
	INSERT INTO stage_my_areas
	(area_code, area_number, area_level, uqid, name, geom
	,parent_area_code, parent_area_number, parent_uqid
	, mbr, num_pts, area
	) VALUES
	('DEPT', 250000 + l_id, 6, 'FRAD2500'||l_deptid, l_name, l_geom
	,'REG', 250000 + l_region, 'FRAR'||l_region
	,sdo_geom.sdo_mbr(l_geom)
	,SDO_UTIL.GETNUMVERTICES(l_geom)
	,SDO_GEOM.SDO_AREA(l_geom, 0.001,'unit=sq_km')
	);
  END LOOP;
  COMMIT;
END;
/


update stage_my_areas
SET mbr = sdo_geom.sdo_mbr(geom)
, num_pts = SDO_UTIL.GETNUMVERTICES(geom)
, area = SDO_GEOM.SDO_AREA(geom, 0.001,'unit=sq_km')
WHERE mbr IS null
/
update stage_my_areas
set area_level = 6
where area_code = 'DEPT'
and area_level = 5
/

----------------------------------------------------------------------------------------------------
-- where are we after loading
----------------------------------------------------------------------------------------------------
select * from stage_my_areas
order by area_level, area_code, area_number
/
select a.*
,SDO_GEOM.SDO_AREA(geom, 0.001,'unit=sq_km') 
from my_areas a
where name_hierarchy like 'France%'
order by name_hierarchy;
/


select *
from my_areas
where area_code = 'DEPT'
and uqid like 'FRA%'
order by 1,2
/

792001-792096 =>  250001-25096




