REM ireland_settlements_load.sql 
REM Settlements - National Statistical Boundaries - 2015
REM settlements ungeneralised - https://data.gov.ie/en_GB/dataset/settlements-ungeneralised-national-statistical-boundaries-20151
REM https://data.gov.ie/dataset/settlements-generalised-20m-national-statistical-boundaries-20151
REM https://data.gov.ie/dataset/settlements-generalised-50m-national-statistical-boundaries-20151
REM https://data.gov.ie/dataset/settlements-generalised-100m-national-statistical-boundaries-20151

--DROP TABLE strava.stage_geo_data PURGE;
CREATE TABLE strava.stage_geo_data (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name        varchar2(200),
    geo_json    clob,
--  geom        MDSYS.SDO_GEOMETRY
);

--area staging table - one row per geometry
DROP TABLE strava.stage_my_areas PURGE;
CREATE TABLE strava.stage_my_areas (
    AREA_CODE VARCHAR2(4 CHAR) NOT NULL , 
	AREA_NUMBER NUMBER(*,0) NOT NULL , 
	UQID VARCHAR2(20 CHAR) NOT NULL , 
 	AREA_LEVEL NUMBER(*,0), 
	PARENT_AREA_CODE VARCHAR2(4 CHAR), 
	PARENT_AREA_NUMBER NUMBER(*,0), 
	PARENT_UQID VARCHAR2(20 CHAR), 
	NAME VARCHAR2(100 CHAR), 
	GAEILGE VARCHAR2(100 CHAR),
	MATCHABLE NUMBER(*,0) DEFAULT 1, 
--
    GEOM MDSYS.SDO_GEOMETRY ,
	MBR MDSYS.SDO_GEOMETRY , 
	AREA NUMBER,
	NUM_PTS NUMBER(*,0)    
);

ALTER TABLE strava.stage_my_areas ADD CONSTRAINT stage_my_areas_pk PRIMARY KEY (area_code, area_number);
ALTER TABLE strava.stage_my_areas ADD CONSTRAINT stage_my_areas_pk2 UNIQUE (uqid);

INSERT INTO USER_SDO_GEOM_METADATA (
    TABLE_NAME,
    COLUMN_NAME,
    DIMINFO,
    SRID
) VALUES (
    'STAGE_GEO_DATA',
    'GEOM',
    SDO_DIM_ARRAY(
        SDO_DIM_ELEMENT('Longitude', -180, 180, 0.005),
        SDO_DIM_ELEMENT('Latitude',  -90,  90, 0.005)
    ),
    4326
);

INSERT INTO USER_SDO_GEOM_METADATA (
    TABLE_NAME,
    COLUMN_NAME,
    DIMINFO,
    SRID
) VALUES (
    'STAGE_MY_AREAS',
    'GEOM',
    SDO_DIM_ARRAY(
        SDO_DIM_ELEMENT('Longitude', -180, 180, 0.005),
        SDO_DIM_ELEMENT('Latitude',  -90,  90, 0.005)
    ),
    4326
);

DROP INDEX stage_geo_data_sidx
/
DROP INDEX stage_my_areas_sidx
/
CREATE INDEX stage_my_areas_sidx
ON stage_my_areas(geom)
INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2
/
----------------------------------------------------------------------------------------------------
--load json FROM data.gov.ie
----------------------------------------------------------------------------------------------------
clear screen
set serveroutput on 
set timi on
--TRUNCATE TABLE strava.stage_geo_data;
delete from stage_geo_data where name = 'Settlements';
DECLARE --Townlands - National Statutory Boundaries - 2019
  l_url VARCHAR2(1000)
  := 'https://data-osi.opendata.arcgis.com/api/download/v1/items/593c427597b9444cb25bb81b669b08f8/geojson?layers=0' /*ungeneralised*/;
  --:= 'https://data-osi.opendata.arcgis.com/api/download/v1/items/7936f206e10a4260ab6fe7891a7021c1/geojson?layers=0' /*generalised20m*/;
  
  l_clob CLOB;
BEGIN
  DBMS_LOB.createtemporary(l_clob, TRUE);
  l_clob:=strava_http.http_request(l_url);
  
  --strava_http.print_clob(l_clob);
  --strava_sdo.parse_geojson(l_clob);
  
  INSERT INTO stage_geo_data (name, geo_json)
  VALUES ('Settlements', l_clob);

  DBMS_LOB.freetemporary(l_clob);
END;
/
SELECT x.*, length(geo_json) FROM stage_geo_data x;
----------------------------------------------------------------------------------------------------
--list what we have loaded in main table
----------------------------------------------------------------------------------------------------
--SELECT * FROM my_areas where name = 'Ireland';

--staging data loaded FROM web
SELECT * FROM my_area_codes ORDER BY area_level;
INSERT INTO my_area_codes VALUES ('SETL','Settlement',7);
INSERT INTO my_area_codes VALUES ('TOWN','Town',8);
update my_area_codes set area_level = 8 where area_code = 'TOWN';
COMMIT;
----------------------------------------------------------------------------------------------------
--parse geo_json FROM staging tables
--SELECT UTL_HTTP.get_detailed_sqlerrm FROM dual;
--value := UTL_HTTP.get_header(resp, 'Location'); --get redirection URL in header
--note handling of redirect, can limit redirect
--note exception handler for sdo_util.from_geojson and then using alterntive manual procedure, but much slower than native
----------------------------------------------------------------------------------------------------
clear screen
set serveroutput on echo on timi on
TRUNCATE TABLE strava.stage_my_areas;
DECLARE 
  l_clob        CLOB;
  j_root        JSON_OBJECT_T;
  j_crs         JSON_OBJECT_T;
  j_features    JSON_ARRAY_T;
  j_feature     JSON_OBJECT_T;
  j_properties  JSON_OBJECT_T;
  j_geometry    JSON_OBJECT_T;

  l_geom        MDSYS.SDO_GEOMETRY;

  l_rownumber  INTEGER;
  l_id         INTEGER;
  l_srid       VARCHAR2(10 char);
  --l_county     VARCHAR2(200 char);
  l_name       VARCHAR2(100 char);
  --l_GAEILGE    VARCHAR2(100 char); --gwail'ge
  l_num_pts    INTEGER;
  
  e_json_syntax_error  EXCEPTION;
  PRAGMA exception_init(e_json_syntax_error,-40441);
BEGIN 
  SELECT geo_json INTO l_clob FROM stage_geo_data
  WHERE name = 'Settlements';
  l_clob := strava_http.clean_clob(l_clob);
  --strava_http.pretty_json(l_clob);
  j_root := JSON_OBJECT_T.parse(l_clob);

  j_crs := j_root.get_object('crs');
  --l_clob := j_crs.to_clob;
  --strava_http.print_clob(l_clob);
	  
  j_features := j_root.get_array('features');
  l_srid     := REGEXP_SUBSTR(j_crs.get_object('properties').get_string('name'),'[^:]+',1,2);
  FOR i IN 0 .. j_features.get_size - 1 LOOP
    j_feature := TREAT(j_features.get(i) AS JSON_OBJECT_T);
    j_properties := j_feature.get_object('properties');
	IF j_properties IS NULL THEN 
	  dbms_output.put_line('J_PROPERTIES is null');
	ELSE
      --l_clob := j_properties.to_clob;
	  --strava_http.print_clob(l_clob);
	  l_rownumber        := j_properties.get_string('OBJECTID_12');
	  l_id               := j_properties.get_string('SETTLEMENT');
      --l_county           := initcap_placename(j_properties.get_string('COUNTY'));
      l_name             := initcap_placename(j_properties.get_string('SETTL_NAME'));
      --l_gaeilge          := initcap_placename(j_properties.get_string('GAEILGE'));
      --dbms_output.put_line(l_rownumber||':'||l_id||', '||l_srid||', Name:'||l_name);
	END IF;

    j_geometry := j_feature.get_object('geometry');
	IF j_geometry IS NULL THEN
	  dbms_output.put_line(l_name||': j_geometry is null');
	  l_geom := NULL;
	ELSE
	  -- Get coordinates array
      l_clob := j_geometry.to_clob;
      
      IF i = 1 THEN
	    strava_http.pretty_json(l_clob);
  	  END IF;

      BEGIN
	    l_geom := sdo_util.from_geojson(l_clob);
	  EXCEPTION 
	    WHEN e_json_syntax_error THEN
		  dbms_output.put_line(sqlerrm||' during parse of '||l_name||' ('||l_id||'). Switch to own function.' );
    	  l_geom := strava_sdo.build_sdo_geometry_from_geojson(j_geometry, l_srid);
	  END;

	  l_geom.SDO_SRID := TO_NUMBER(l_srid);
	  IF l_srid != 4326 THEN
  	    l_geom := SDO_CS.TRANSFORM(l_geom, 4326);
   	    l_geom.SDO_SRID := 4326;
	  END IF;
	  l_geom := sdo_util.rectify_Geometry(SDO_CS.MAKE_2D(l_geom),0.001);
	  l_num_pts := SDO_UTIL.GETNUMVERTICES(l_geom);
    
      /*dbms_output.put_line(i
	      ||','||l_id
	      --||', Logainm Id:'||l_logainm_id
		  --||', County:'||l_county
		  ||','||l_name
          --||' ('||l_gaeilge||')'
		  --||', '||l_num_pts||' points'
		  ); */
	  --dbms_output.put_line(SDO_UTIL.TO_WKTGEOMETRY(l_geom));
	
	  INSERT INTO stage_my_areas
	  (area_code, area_number, area_level, uqid, name, geom
	  , mbr, num_pts, area)
	  VALUES
	  ('SETL', l_id, 8, 'IRLS'||l_id, l_name, l_geom
	  ,sdo_geom.sdo_mbr(l_geom)
	  ,SDO_UTIL.GETNUMVERTICES(l_geom)
	  ,SDO_GEOM.SDO_AREA(l_geom, 0.001,'unit=sq_km'))
  	  ;
	END IF;
  END LOOP;
  COMMIT;
END;
/
update stage_my_areas set uqid = 'IRLS'||area_number;
update my_areas 
set uqid = 'IRLT'||area_number
where uqid like 'IRL%'
and area_code = 'TOWN';

----------------------------------------------------------------------------------------------------
--identify parent area in my_areas qwert
----------------------------------------------------------------------------------------------------
--unmatch settlements to townlands
update stage_my_areas
set parent_area_code = null, parent_area_number = NULl
where parent_area_code IN('SETL','TOWN')
/
clear screen
set serveroutput on
DECLARE
  e_general_error EXCEPTION;
PROCEDURE area_hsearch
(p_searchfor_area_code   stage_my_areas.area_code%TYPE
,p_searchfor_area_number stage_my_areas.area_number%TYPE
,p_searchfrom_code        my_areas.area_code%TYPE DEFAULT NULL
,p_searchfrom_number      my_areas.area_number%TYPE DEFAULT NULL
,p_query_type VARCHAR2 DEFAULT 'A'
,p_level INTEGER DEFAULT 0
) IS
  l_t0 timestamp; 
  l_t1 timestamp;
  l_secs NUMBER;
  l_num_rows NUMBER;
  l_pad VARCHAR2(20 CHAR) := '';
BEGIN
  l_pad := lpad('.',p_level,'.');
  l_t0 := SYSTIMESTAMP;
  
  IF p_level >4 then
    RAISE_APPLICATION_ERROR(-20000,'Recurrsion level '||p_level);
  ELSE
    dbms_output.put_line('Searching '||p_searchfor_area_code||'-'||p_searchfor_area_number
	        ||'. '||p_query_type||':'||p_searchfrom_code||'-'||p_searchfrom_number);

  END IF;
  
  FOR i IN(
   WITH x AS (
   SELECT m.area_code, m.area_number, m.name
   ,      new.area_code new_area_code, new.area_number new_area_number, new.name new_name, new.area new_area
   ,      CASE WHEN m.geom  IS NOT NULL AND new.geom IS NOT NULL THEN sdo_geom.sdo_area(SDO_GEOM.sdo_intersection(m.geom,new.geom,0.001), unit=>'unit=sq_km') 
		  END geom_area
   FROM   my_areas m
   ,      stage_my_areas new
   WHERE  (  (p_query_type = 'C' AND m.parent_area_code = p_searchfrom_code AND m.parent_area_number = p_searchfrom_number) 
          OR (p_query_type = 'A' AND m.area_code        = p_searchfrom_code AND m.area_number        = p_searchfrom_number)
		  --OR (p_query_type = 'A' AND p_area_number IS NULL          AND m.area_code          = p_area_code)
          --OR (p_area_code IS NULL AND p_area_number IS NULL AND parent_area_code IS NULL AND parent_area_number IS NULL)
		  )
   AND    new.area_code = p_searchfor_area_code 
   AND    new.area_number = p_searchfor_area_number
   --and    sdo_geom.sdo_intersection(m.mbr,new.mbr,1) IS NOT NULL
   --and    sdo_geom.sdo_intersection(m.geom,new.geom,1) IS NOT NULL
   and    SDO_ANYINTERACT(m.geom, new.geom)
   and    SDO_ANYINTERACT(m.mbr, new.mbr) 
   --and    sdo_geom.RELATE(m.mbr ,'mask=covers',new.mbr ,0.001) 
   --and    sdo_geom.RELATE(m.geom,'mask=covers',new.geom,0.001) 
   and     m.area_level < new.area_level
   and     m.area_level < 7
   and m.rowid != new.rowid
   )
   SELECT * FROM x 
   WHERE geom_area/new_area>=.8
   ORDER BY geom_area desc nulls last fetch first 1 rows only
  ) LOOP
    IF i.geom_area/i.new_area >= .99 THEN
      dbms_output.put_line(l_pad||'Found '||i.area_code||'-'||i.area_number
	                            ||':'||i.name
		  	 	 			    ||', area '||i.new_area||' km^2'
			 				    ||', intersection area '||i.geom_area||' km^2 ('||100*i.geom_area/i.new_area||'%)'
							    );

	  IF i.area_code = p_searchfor_area_code AND i.area_number = p_searchfor_area_number then
	    dbms_output.put_line('Same');
	  ELSE
	    dbms_output.put_line('Updating '||i.area_code||'-'||i.area_number
		            ||' is a parent of '||p_searchfor_area_code||'-'||p_searchfor_area_number);
  	    UPDATE stage_my_areas
	    SET    parent_area_code = i.area_code
	    ,      parent_area_number = i.area_number
	    WHERE  area_code = p_searchfor_area_code 
        AND    area_number = p_searchfor_area_number;
   	    area_hsearch(p_searchfor_area_code, p_searchfor_area_number, i.area_code, i.area_number, 'C', p_level+1);
	  END IF;
	ELSE
      dbms_output.put_line(l_pad||'Not Matched '||i.area_code||'-'||i.area_number
	                            ||':'||i.name
		  	 	 			    ||', area '||i.new_area||' km^2'
			 				    ||', intersection area '||i.geom_area||' km^2 ('||100*i.geom_area/i.new_area||'%)'
							    );
	END IF;
  END LOOP;

  l_t1 := SYSTIMESTAMP;
  l_secs := 60*extract(minute FROM l_t1-l_t0)+extract(second FROM l_t1-l_t0);
  --dbms_output.put_line(l_pad||'Done '||p_searchfor_area_code||'-'||p_searchfor_area_number||':'||TO_CHAR(l_secs,'9990.999')||' secs).');
END area_hsearch;
  ----------------------------------------------------------------------------------------------------
BEGIN
  FOR i IN (
    SELECT * FROM stage_my_areas 
	WHERE area_code != 'SOVC'
    AND parent_area_code != 'CTY'
    --and area_number = 35017
	FETCH FIRST 1 ROWS ONLY
  ) LOOP
    area_hsearch(i.area_code, i.area_number, 'SOVC',372, 'A', 0);
	COMMIT;
  END LOOP;
END;
/
----------------------------------------------------------------------------------------------------
--manual match settlements to counties
----------------------------------------------------------------------------------------------------
clear screen
UPDATE stage_my_areas
SET (parent_area_code, parent_area_number, parent_uqid) = (
  SELECT area_code, area_number, uqid FROM my_areas WHERE area_code = 'SOVC' AND name = 'Ireland')
WHERE area_code = 'SETL' and area_number IN();

UPDATE stage_my_areas
SET (parent_area_code, parent_area_number, parent_uqid) = (
  SELECT area_code, area_number, uqid FROM my_areas WHERE area_code = 'PROV' AND name = 'Connacht')
WHERE area_code = 'SETL' and area_number IN(35017,35021,35023);
UPDATE stage_my_areas
SET (parent_area_code, parent_area_number, parent_uqid) = (
  SELECT area_code, area_number, uqid FROM my_areas WHERE area_code = 'PROV' AND name = 'Leinster')
WHERE area_code = 'SETL' and area_number IN(35015,35020);
UPDATE stage_my_areas
SET (parent_area_code, parent_area_number, parent_uqid) = (
  SELECT area_code, area_number, uqid FROM my_areas WHERE area_code = 'PROV' AND name = 'Munster')
WHERE area_code = 'SETL' and area_number IN(35018);

UPDATE stage_my_areas
SET (parent_area_code, parent_area_number, parent_uqid) = (
  SELECT area_code, area_number, uqid FROM my_areas WHERE area_code = 'CTY' AND name = 'Carlow')
WHERE (parent_area_code is null or parent_area_code != 'CTY') and area_code = 'SETL' 
and area_number IN(1015,1018,35006,35022,35025);
UPDATE stage_my_areas
SET (parent_area_code, parent_area_number, parent_uqid) = (
  SELECT area_code, area_number, uqid FROM my_areas WHERE area_code = 'CTY' AND name = 'Cavan')
WHERE (parent_area_code is null or parent_area_code != 'CTY') and area_code = 'SETL' 
and area_number IN(32018);
UPDATE stage_my_areas
SET (parent_area_code, parent_area_number, parent_uqid) = (
  SELECT area_code, area_number, uqid FROM my_areas WHERE area_code = 'CTY' AND name = 'Clare')
WHERE (parent_area_code is null or parent_area_code != 'CTY') and area_code = 'SETL' 
and area_number IN(16001,16016);
UPDATE stage_my_areas
SET (parent_area_code, parent_area_number, parent_uqid) = (
  SELECT area_code, area_number, uqid FROM my_areas WHERE area_code = 'CTY' AND name = 'Cork')
WHERE (parent_area_code is null or parent_area_code != 'CTY') and area_code = 'SETL' 
and area_number IN(18019,18013,18043,18010,18008,18015,18007,18061,18073,18092,18108,18115);
UPDATE stage_my_areas
SET (parent_area_code, parent_area_number, parent_uqid) = (
  SELECT area_code, area_number, uqid FROM my_areas WHERE area_code = 'CTY' AND name = 'Donegal')
WHERE (parent_area_code is null or parent_area_code != 'CTY') and area_code = 'SETL' 
and area_number IN(33025, 33003, 33001,33018,33022,33043,33004,33033,33023,33059,33060);
UPDATE stage_my_areas
SET (parent_area_code, parent_area_number, parent_uqid) = (
  SELECT area_code, area_number, uqid FROM my_areas WHERE area_code = 'CTY' AND name = 'Dublin')
WHERE (parent_area_code is null or parent_area_code != 'CTY') and area_code = 'SETL' 
and area_number IN(4006,4012,4008,4005,4019);
UPDATE stage_my_areas
SET (parent_area_code, parent_area_number, parent_uqid) = (
  SELECT area_code, area_number, uqid FROM my_areas WHERE area_code = 'CTY' AND name = 'Galway')
WHERE (parent_area_code is null or parent_area_code != 'CTY') and area_code = 'SETL' 
and area_number IN(27011,27008,27002,27006,27038,27045,35011);
UPDATE stage_my_areas
SET (parent_area_code, parent_area_number, parent_uqid) = (
  SELECT area_code, area_number, uqid FROM my_areas WHERE area_code = 'CTY' AND name = 'Kildare')
WHERE (parent_area_code is null or parent_area_code != 'CTY') and area_code = 'SETL' 
and area_number IN(6036,6039);
UPDATE stage_my_areas
SET (parent_area_code, parent_area_number, parent_uqid) = (
  SELECT area_code, area_number, uqid FROM my_areas WHERE area_code = 'CTY' AND name = 'Kilkenny')
WHERE (parent_area_code is null or parent_area_code != 'CTY') and area_code = 'SETL' 
and area_number IN(7015,7027);
UPDATE stage_my_areas
SET (parent_area_code, parent_area_number, parent_uqid) = (
  SELECT area_code, area_number, uqid FROM my_areas WHERE area_code = 'CTY' AND name = 'Kerry')
WHERE (parent_area_code is null or parent_area_code != 'CTY') and area_code = 'SETL' 
and area_number IN(19039,19001,19018,19007,19021,19024,19029);
UPDATE stage_my_areas
SET (parent_area_code, parent_area_number, parent_uqid) = (
  SELECT area_code, area_number, uqid FROM my_areas WHERE area_code = 'CTY' AND name = 'Laois')
WHERE (parent_area_code is null or parent_area_code != 'CTY') and area_code = 'SETL' 
and area_number IN(8016,8022,35016);
UPDATE stage_my_areas
SET (parent_area_code, parent_area_number, parent_uqid) = (
  SELECT area_code, area_number, uqid FROM my_areas WHERE area_code = 'CTY' AND name = 'Leitrim')
WHERE (parent_area_code is null or parent_area_code != 'CTY') and area_code = 'SETL' 
and area_number IN(35024);
UPDATE stage_my_areas
SET (parent_area_code, parent_area_number, parent_uqid) = (
  SELECT area_code, area_number, uqid FROM my_areas WHERE area_code = 'CTY' AND name = 'Limerick')
WHERE (parent_area_code is null or parent_area_code != 'CTY') and area_code = 'SETL' 
and area_number IN(21028,21042,21047
                  ,23020,35003);
UPDATE stage_my_areas
SET (parent_area_code, parent_area_number, parent_uqid) = (
  SELECT area_code, area_number, uqid FROM my_areas WHERE area_code = 'CTY' AND name = 'Longford')
WHERE (parent_area_code is null or parent_area_code != 'CTY') and area_code = 'SETL' 
and area_number IN(35015);
UPDATE stage_my_areas
SET (parent_area_code, parent_area_number, parent_uqid) = (
  SELECT area_code, area_number, uqid FROM my_areas WHERE area_code = 'CTY' AND name = 'Louth')
WHERE (parent_area_code is null or parent_area_code != 'CTY') and area_code = 'SETL' 
and area_number IN(10003,10018);
UPDATE stage_my_areas
SET (parent_area_code, parent_area_number, parent_uqid) = (
  SELECT area_code, area_number, uqid FROM my_areas WHERE area_code = 'CTY' AND name = 'Mayo')
WHERE (parent_area_code is null or parent_area_code != 'CTY') and area_code = 'SETL' 
and area_number IN(29024,29027,29028,29035,29036);
UPDATE stage_my_areas
SET (parent_area_code, parent_area_number, parent_uqid) = (
  SELECT area_code, area_number, uqid FROM my_areas WHERE area_code = 'CTY' AND name = 'Meath')
WHERE (parent_area_code is null or parent_area_code != 'CTY') and area_code = 'SETL' 
and area_number IN(11007,11013,11020,11029,11030,11032,11035,35009);
UPDATE stage_my_areas
SET (parent_area_code, parent_area_number, parent_uqid) = (
  SELECT area_code, area_number, uqid FROM my_areas WHERE area_code = 'CTY' AND name = 'Offaly')
WHERE (parent_area_code is null or parent_area_code != 'CTY') and area_code = 'SETL' 
and area_number IN(12002,12010,12014,12026,12027);
UPDATE stage_my_areas
SET (parent_area_code, parent_area_number, parent_uqid) = (
  SELECT area_code, area_number, uqid FROM my_areas WHERE area_code = 'CTY' AND name = 'Roscommon')
WHERE (parent_area_code is null or parent_area_code != 'CTY') and area_code = 'SETL' 
and area_number IN(35010,30024);
UPDATE stage_my_areas
SET (parent_area_code, parent_area_number, parent_uqid) = (
  SELECT area_code, area_number, uqid FROM my_areas WHERE area_code = 'CTY' AND name = 'Sligo')
WHERE (parent_area_code is null or parent_area_code != 'CTY') and area_code = 'SETL' 
and area_number IN(31004);
UPDATE stage_my_areas
SET (parent_area_code, parent_area_number, parent_uqid) = (
  SELECT area_code, area_number, uqid FROM my_areas WHERE area_code = 'CTY' AND name = 'Tipperary')
WHERE (parent_area_code is null or parent_area_code != 'CTY') and area_code = 'SETL' 
and area_number IN(22021,23021,23017,35012,35014);
UPDATE stage_my_areas
SET (parent_area_code, parent_area_number, parent_uqid) = (
  SELECT area_code, area_number, uqid FROM my_areas WHERE area_code = 'CTY' AND name = 'Waterford')
WHERE (parent_area_code is null or parent_area_code != 'CTY') and area_code = 'SETL' 
and area_number IN(25015,25003,25008,35004);
UPDATE stage_my_areas
SET (parent_area_code, parent_area_number, parent_uqid) = (
  SELECT area_code, area_number, uqid FROM my_areas WHERE area_code = 'CTY' AND name = 'Westmeath')
WHERE (parent_area_code is null or parent_area_code != 'CTY') and area_code = 'SETL' 
and area_number IN(13010,13019,13020,13021);
UPDATE stage_my_areas
SET (parent_area_code, parent_area_number, parent_uqid) = (
  SELECT area_code, area_number, uqid FROM my_areas WHERE area_code = 'CTY' AND name = 'Wexford')
WHERE (parent_area_code is null or parent_area_code != 'CTY') and area_code = 'SETL' 
and area_number IN(14018,14022,14004,14030,14033,35008);
UPDATE stage_my_areas
SET (parent_area_code, parent_area_number, parent_uqid) = (
  SELECT area_code, area_number, uqid FROM my_areas WHERE area_code = 'CTY' AND name = 'Wicklow')
WHERE (parent_area_code is null or parent_area_code != 'CTY') and area_code = 'SETL' 
and area_number IN(15023,15033,35007,35026);

select area_code, area_number, name, parent_area_code from stage_my_areas
where area_code = 'SETL' and parent_area_code != 'CTY'
order by 1,2;
----------------------------------------------------------------------------------------------------
-- verify area match 
----------------------------------------------------------------------------------------------------
select m.area_code,m.area_number, m.name, a.name
,      sdo_anyinteract(m.mbr,a.mbr) mbr_interact
,      sdo_anyinteract(m.geom,a.geom) geom_interact
,      sdo_relate(m.geom,a.geom,'OVERLAPBDYINTERSECT') overlapping
,      sdo_relate(m.geom,a.geom,'TOUCH') touching
,      sdo_relate(m.geom,a.geom,'INSIDE') inside
,      sdo_geom.sdo_area(m.geom, unit=>'unit=sq_km') staging_km_sq
,      sdo_geom.sdo_area(sdo_geom.sdo_intersection(m.geom,a.geom,1), unit=>'unit=sq_km') intersect_km_sq    
from stage_my_areas m, my_areas a
where 1=1
and a.area_code = 'PROV' --and a.area_number = 372
and m.area_code = 'SETL'
--and m.area_number = 15008
and a.area_code = m.parent_area_code
and a.area_number = m.parent_area_number
fetch first 50 rows only
/
-------------------------------------------------------------------------------------------------------
-- demo settlement ID number structire
----------------------------------------------------------------------------------------------------
--select * from stage_my_areas;
select p.area_code,p.area_number, p.name, c.area_code
, min(c.area_number) min_area_number
, max(c.area_number) max_area_number
from my_areas p, stage_my_areas c
where 1=1
--and c.area_code = 'SETL'
and p.area_code = c.parent_area_code
and p.area_number = c.parent_area_number
group by p.area_code,p.area_number, p.name, c.area_code, round(c.area_number,-3)
order by min_area_number,1,2
/
----------------------------------------------------------------------------------------------------
-- merge staged areas into areas table
----------------------------------------------------------------------------------------------------
MERGE INTO my_areas u 
USING (select * from stage_my_areas order by area_level) s 
ON (s.area_code = u.area_code AND s.area_number = u.area_number)
WHEN MATCHED THEN UPDATE 
SET u.area_level = s.area_level
, u.parent_area_code = s.parent_area_code 
, u.parent_area_number = s.parent_area_number
, u.name = s.name
, u.matchable = s.matchable
, u.geom = s.geom
, u.mbr = s.mbr
, u.num_pts = s.num_pts
, u.num_children = null
WHEN NOT MATCHED THEN INSERT 
(area_code, area_number, uqid, area_level, parent_area_code, parent_area_number, name, matchable
, geom, mbr, num_pts, num_children)
VALUES
(s.area_code, s.area_number, s.uqid, s.area_level, s.parent_area_code, s.parent_area_number, s.name, s.matchable
, s.geom, s.mbr, s.num_pts, NULL)
/
SELECT * FROM MY_AREAS WHERE UQID = 'IRLS31004';
----------------------------------------------------------------------------------------------------
-- correct parent uqid 
----------------------------------------------------------------------------------------------------
merge into my_areas u
using (
select c.area_level, c.area_code, c.area_number, p.uqid parent_uqid
from my_areas c
  inner join my_areas p
    on p.area_code = c.parent_area_code
    and p.area_number = c.parent_area_number
where c.parent_uqid IS NULL 
and c.parent_area_code IS NOT NULL
order by c.area_level
) s
ON (s.area_code = u.area_code AND s.area_number = u.area_number)
WHEN MATCHED THEN UPDATE 
SET u.parent_uqid = s.parent_uqid
/
----------------------------------------------------------------------------------------------------
--correct count of number of children
----------------------------------------------------------------------------------------------------
merge into my_areas u
using (
select p.area_code, p.area_number, p.name, p.num_children, count(c.area_number) child_count
from my_areas p
  left outer join my_areas c
    on p.area_code = c.parent_area_code
    and p.area_number = c.parent_area_number
where 1=1
--and c.num_children IS NULL
group by p.area_code, p.area_number, p.name, p.num_children
having count(c.area_number) != NVL(p.num_children,0)
) s
ON (s.area_code = u.area_code AND s.area_number = u.area_number)
WHEN MATCHED THEN UPDATE 
SET u.num_children = s.child_count
/
----------------------------------------------------------------------------------------------------
--mark activities from recalculation - but this may hit too many
----------------------------------------------------------------------------------------------------
MERGE INTO activities u
USING (
select a.activity_id, a.name, a.start_date_utc, a.processing_status, a.last_updated activity_last_updated
, MAX(ma.last_updated) area_last_updated
from activities a
,    activity_areas aa
,    my_areas ma
where a.activity_id = aa.activity_id
and ma.area_code =aa.area_code 
and ma.area_number = aa.area_number
and a.last_updated < ma.last_updated
and a.processing_status > 3
group by a.activity_id, a.name, a.start_date_utc, a.processing_status, a.last_updated
) s
ON (s.activity_id = u.activity_id)
WHEN MATCHED THEN UPDATE
SET u.processing_status = 3
/

----------------------------------------------------------------------------------------------------
--mark for recalculation of area list - optional
----------------------------------------------------------------------------------------------------
MERGE INTO activities u
USING (
select a.activity_id, a.name, a.start_date_utc, a.processing_status
, a.last_updated act_last_updated
, ma.last_updated areas_last_updated
from activities a
,    activity_areas aa
,    my_areas ma
where a.activity_id = aa.activity_id
and ma.area_code =aa.area_code 
and ma.area_number = aa.area_number
and a.last_updated < ma.last_updated
and a.processing_status >4
) s
ON (s.activity_id = u.activity_id)
WHEN MATCHED THEN UPDATE
SET u.processing_status = 4
/


