REM ireland_load.sql
REM load Ireland: National Boundary inc. Territorial Waters
REM https://osm-boundaries.com/map
https://osm-boundaries.com/l/86d8684538cbfe2849ab9c8bd4c4f4cad5a7aff7
set serveroutput on echo on

----------------------------------------------------------------------------------------------------
-- create staging table
----------------------------------------------------------------------------------------------------
--DROP TABLE stage_geo_data PURGE;
CREATE TABLE strava.stage_geo_data (
   id          NUMBER GENERATED BY DEFAULT AS IDENTITY,
   name        varchar2(200),
   geo_json    clob
--,geom        MDSYS.SDO_GEOMETRY
);
GRANT INSERT ON strava.stage_geo_data TO admin;

--name: par-object-20260225-1730
--https://objectstorage.uk-london-1.oraclecloud.com/p/J40qKM1MMd6KDRSIoYjcH6hl-KhQbgaD2NnoYw_cjMzCarR1De9Db0O7s8IkoJOv/n/lrp1qmpxv8ea/b/bucket-gofaster1/o/export_strava.dmp
--
SELECT object_name, bytes/1024/1024 Mb
FROM table(
  DBMS_CLOUD.LIST_objects
  (credential_name => 'OBJECT_STORE_CRED'
  ,location_uri => 'https://objectstorage.uk-london-1.oraclecloud.com/n/lrp1qmpxv8ea/b/bucket-gofaster1/o/'
  ));



DECLARE
    l_blob BLOB;
BEGIN
    -- Read the file from Object Storage into CLOB
    l_blob := DBMS_CLOUD.GET_OBJECT
              (credential_name => 'OBJECT_STORE_CRED'
              ,object_uri      => 'https://objectstorage.uk-london-1.oraclecloud.com/p/172dtbsjdhx45ptJOs2CeXZXopSpj7VGVI_QPFEcOEpxQvvr-8Sm5-Oh4t2ljpaw/n/lrp1qmpxv8ea/b/bucket-gofaster1/o/OSMB-a4cc989e9d08fd47ef13d7d439df8cd84f6b09c6.geojson'
              );
    --l_clob := CAST(l_blob AS CLOB);
    -- Insert into table
    INSERT INTO strava.stage_geo_data(name, geo_json)
    VALUES ('OSMB-a4cc989e9d08fd47ef13d7d439df8cd84f6b09c6.geojson', l_blob);

    COMMIT;
END;
/
select * from strava.stage_geo_data;
----------------------------------------------------------------------------------------------------
--area staging table - one row per geometry
----------------------------------------------------------------------------------------------------
DROP TABLE stage_my_areas;
CREATE TABLE stage_my_areas (
    AREA_CODE VARCHAR2(4 CHAR) NOT NULL , 
	area_number NUMBER(*,0) NOT NULL , 
	UQID VARCHAR2(20 CHAR) NOT NULL , 
 	AREA_LEVEL NUMBER(*,0), 
	PARENT_AREA_CODE VARCHAR2(4 CHAR), 
	PARENT_area_number NUMBER(*,0), 
	PARENT_UQID VARCHAR2(20 CHAR), 
	NAME VARCHAR2(60 CHAR), 
	MATCHABLE NUMBER(*,0) DEFAULT 1, 
--
    GEOM MDSYS.SDO_GEOMETRY ,
	MBR MDSYS.SDO_GEOMETRY , 
	AREA NUMBER,
	NUM_PTS NUMBER(*,0)	
);

ALTER TABLE stage_my_areas ADD CONSTRAINT stage_my_areas_pk PRIMARY KEY (area_code, area_number);
ALTER TABLE stage_my_areas ADD CONSTRAINT stage_my_areas_pk2 UNIQUE (uqid);

INSERT INTO USER_SDO_GEOM_METADATA (
    TABLE_NAME,
    COLUMN_NAME,
    DIMINFO,
    SRID
)
VALUES (
    'STAGE_GEO_DATA',
    'GEOM',
    SDO_DIM_ARRAY(
        SDO_DIM_ELEMENT('Longitude', -180, 180, 0.005),
        SDO_DIM_ELEMENT('Latitude',  -90,  90, 0.005)
    ),
    4326
);

INSERT INTO USER_SDO_GEOM_METADATA (
    TABLE_NAME,
    COLUMN_NAME,
    DIMINFO,
    SRID
)
VALUES (
    'STAGE_MY_AREAS',
    'GEOM',
    SDO_DIM_ARRAY(
        SDO_DIM_ELEMENT('Longitude', -180, 180, 0.005),
        SDO_DIM_ELEMENT('Latitude',  -90,  90, 0.005)
    ),
    4326
);

DROP INDEX stage_geo_data_sidx
/
CREATE INDEX stage_geo_data_sidx
ON stage_geo_data(geom)
INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2
/

DROP INDEX stage_my_areas_sidx
/
CREATE INDEX stage_my_areas_sidx
ON stage_my_areas(geom)
INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2
/

----------------------------------------------------------------------------------------------------
-- parse json in STAGE_GEO_DATA
----------------------------------------------------------------------------------------------------
clear screen
set serveroutput on echo on timi on
TRUNCATE TABLE stage_my_areas;
DECLARE 
  l_clob        CLOB;
  j_root        JSON_OBJECT_T;
  j_crs         JSON_OBJECT_T;
  j_features    JSON_ARRAY_T;
  j_feature     JSON_OBJECT_T;
  j_properties  JSON_OBJECT_T;
  j_geometry    JSON_OBJECT_T;

  l_geom        MDSYS.SDO_GEOMETRY;
  --l_geom_centre MDSYS.SDO_GEOMETRY;
  l_centre      MDSYS.SDO_GEOMETRY;

  l_id       INTEGER;
  l_srid     VARCHAR2(10 char);
  l_name     VARCHAR2(100 char);
  l_num_pts  INTEGER;
  l_centrex  NUMBER;
  l_centrey  NUMBER;
  l_offset   NUMBER;
  
  e_json_syntax_error  EXCEPTION;
  PRAGMA exception_init(e_json_syntax_error,-40441);
BEGIN 
  SELECT geo_json INTO l_clob FROM stage_geo_data 
  WHERE name = 'OSMB-a4cc989e9d08fd47ef13d7d439df8cd84f6b09c6.geojson';
  --l_clob := strava_http.clean_clob(l_clob);
  --strava_http.pretty_json(l_clob);
  j_root := JSON_OBJECT_T.parse(l_clob);
  strava_http.pretty_json(l_root); --qwert

  j_crs := j_root.get_object('crs');
  --l_clob := j_crs.to_clob;
  --strava_http.print_clob(l_clob);
	  
  j_features := j_root.get_array('features');
  l_srid     := 4326;
  FOR i IN 0 .. j_features.get_size - 1 LOOP
    j_feature := TREAT(j_features.get(i) AS JSON_OBJECT_T);
    j_properties := j_feature.get_object('properties');
	IF j_properties IS NULL THEN 
	  dbms_output.put_line('J_PROPERTIES is null');
	ELSE
      l_clob := j_properties.to_clob;
	  strava_http.print_clob(l_clob);
	  l_id               := j_properties.get_string('osm_id');
	  l_name             := j_properties.get_string('name_en');
      --l_name             := initcap(j_properties.get_string('ENGLISH'));
	  --l_centrex          := j_properties.get_string('CENTROID_X');
	  --l_centrey          := j_properties.get_string('CENTROID_Y');
	  --l_centre           := SDO_CS.TRANSFORM(SDO_GEOMETRY(2001, l_srid, SDO_POINT_TYPE(l_centrex, l_centrey, NULL),NULL,NULL),4326);
	  
      dbms_output.put_line(l_id||', '||l_srid||', '||l_name
	  --||', Centre:'||l_centre.sdo_point.x
   	  --        ||','||l_centre.sdo_point.y
	  );
	END IF;

    j_geometry := j_feature.get_object('geometry');
	IF j_geometry IS NULL THEN
	  dbms_output.put_line(l_name||': j_geometry is null');
	  l_offset := NULL;
	  l_geom := NULl;
	  l_num_pts := NULL;
	  --l_geom_centre := NULL;
	ELSE
	  -- Get coordinates array
      l_clob := j_geometry.to_clob;
      
      IF i=0 THEN
        NULL;
	    --strava_http.print_clob(l_clob);
	    --strava_http.pretty_json(l_clob);
  	  END IF;

      BEGIN
	    l_geom := sdo_util.from_geojson(l_clob);
	  EXCEPTION 
	    WHEN e_json_syntax_error THEN
		  dbms_output.put_line(sqlerrm||' during parse of '||l_name||'. Switch to own function.' );
    	  l_geom := strava_sdo.build_sdo_geometry_from_geojson(j_geometry, l_srid);
	  END;

	  l_geom.SDO_SRID := TO_NUMBER(l_srid);
	  l_geom := SDO_CS.TRANSFORM(l_geom, 4326);
	  l_geom.SDO_SRID := TO_NUMBER(4326);
      l_geom := sdo_util.rectify_Geometry(SDO_CS.MAKE_2D(l_geom),0.001);	
	  l_num_pts := SDO_UTIL.GETNUMVERTICES(l_geom);
	  --l_geom_centre := SDO_GEOM.SDO_CENTROID(l_geom, 0.001);
	  --l_offset := sdo_geom.sdo_distance(l_centre,l_geom_centre,0.0005);
	END IF;
    
    dbms_output.put_line('ID:'||l_id
	      --||', Province:'||l_name
		  --||', County:'||l_county
		  ||', Name:'||l_name
	      --||', Centre:'||l_geom_centre.sdo_point.x
   	      --        ||','||l_geom_centre.sdo_point.y
		  --||', Centre Offset:'||l_offset
		  ||', '||l_num_pts||' points');
	--dbms_output.put_line(SDO_UTIL.TO_WKTGEOMETRY(l_geom));
	
	INSERT INTO stage_my_areas
	(area_code, area_number, area_level, uqid, name, geom, mbr, num_pts
	--, area
	, matchable
	) VALUES
	('SOVC', 372, 5, 'IRL372', 'Ireland', l_geom, sdo_geom.sdo_mbr(l_geom), l_num_pts
	--, SDO_GEOM.SDO_AREA(l_geom, 0.001,'unit=km')
	, 1
	)
	;
  END LOOP;
  Commit;
END;
/

UPDATE stage_my_areas
SET    mbr = sdo_geom.sdo_mbr(geom)
,      num_pts = SDO_UTIL.GETNUMVERTICES(geom)
,      area = sdo_geom.sdo_area(geom, unit=>'unit=sq_km')
/

select * from stage_my_areas;
