REM ireland_provinces_load.sql
REM load Ireland: Province Boundaries Ungeneralised - National Administrative Boundaries - 2015
REM https://data.gov.ie/dataset/province-boundaries-ungeneralised-national-administrative-boundaries-20151


----------------------------------------------------------------------------------------------------
-- create staging table
----------------------------------------------------------------------------------------------------
--DROP TABLE strava.stage_geo_data PURGE;
CREATE TABLE strava.stage_geo_data (
   id          NUMBER GENERATED BY DEFAULT AS IDENTITY,
   name        varchar2(200),
   geo_json    clob
--,geom        MDSYS.SDO_GEOMETRY
);

--area staging table - one row per geometry
DROP TABLE stage_my_areas;
CREATE TABLE stage_my_areas (
    AREA_CODE VARCHAR2(4 CHAR) NOT NULL , 
	area_number NUMBER(*,0) NOT NULL , 
	UQID VARCHAR2(20 CHAR) NOT NULL , 
 	AREA_LEVEL NUMBER(*,0), 
	PARENT_AREA_CODE VARCHAR2(4 CHAR), 
	PARENT_area_number NUMBER(*,0), 
	PARENT_UQID VARCHAR2(20 CHAR), 
	NAME VARCHAR2(60 CHAR), 
	MATCHABLE NUMBER(*,0) DEFAULT 1, 
--
    GEOM MDSYS.SDO_GEOMETRY ,
	MBR MDSYS.SDO_GEOMETRY , 
	AREA NUMBER,
	NUM_PTS NUMBER(*,0)	
);

ALTER TABLE stage_my_areas ADD CONSTRAINT stage_my_areas_pk PRIMARY KEY (area_code, area_number);
ALTER TABLE stage_my_areas ADD CONSTRAINT stage_my_areas_pk2 UNIQUE (uqid);

ALTER TABLE stage_my_areas MODIFY area_number CHECK(area_code = RTRIM(area_code));
ALTER TABLE stage_my_areas MODIFY area_number CHECK(parent_area_code = RTRIM(parent_area_code));
ALTER TABLE stage_my_areas MODIFY area_number CHECK(area_number = ROUND(area_number,0));
ALTER TABLE stage_my_areas MODIFY parent_area_number CHECK(parent_area_number = ROUND(parent_area_number,0));

INSERT INTO USER_SDO_GEOM_METADATA (
    TABLE_NAME,
    COLUMN_NAME,
    DIMINFO,
    SRID
)
VALUES (
    'STAGE_GEO_DATA',
    'GEOM',
    SDO_DIM_ARRAY(
        SDO_DIM_ELEMENT('Longitude', -180, 180, 0.005),
        SDO_DIM_ELEMENT('Latitude',  -90,  90, 0.005)
    ),
    4326
);

INSERT INTO USER_SDO_GEOM_METADATA (
    TABLE_NAME,
    COLUMN_NAME,
    DIMINFO,
    SRID
)
VALUES (
    'STAGE_MY_AREAS',
    'GEOM',
    SDO_DIM_ARRAY(
        SDO_DIM_ELEMENT('Longitude', -180, 180, 0.005),
        SDO_DIM_ELEMENT('Latitude',  -90,  90, 0.005)
    ),
    4326
);

DROP INDEX stage_geo_data_sidx
/
DROP INDEX stage_my_areas_sidx
/
CREATE INDEX stage_my_areas_sidx
ON stage_my_areas(geom)
INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2
/

----------------------------------------------------------------------------------------------------
--load json from data.gov.ie
----------------------------------------------------------------------------------------------------
clear screen
set serveroutput on timi on
TRUNCATE TABLE stage_geo_data;
DECLARE --Counties - National Statutory Boundaries - Ungeneralised - 2024
  l_url VARCHAR2(1000)
  := 'https://data-osi.opendata.arcgis.com/api/download/v1/items/6b4fac5d113e4457b059d3c66387e969/geojson?layers=0';
  
  l_clob CLOB;
BEGIN
  DBMS_LOB.createtemporary(l_clob, TRUE);
  l_clob:=strava_http.http_request(l_url,0);
  
  --strava_http.print_clob(l_clob);
  --strava_sdo.parse_geojson(l_clob);
  
  INSERT INTO stage_geo_data (name, geo_json)
  VALUES ('Provinces', l_clob);

  DBMS_LOB.freetemporary(l_clob);
END;
/

--staging data loaded from web
select x.*, length(geo_json) 
from stage_geo_data x;
----------------------------------------------------------------------------------------------------
--list what we have loaded in main table
----------------------------------------------------------------------------------------------------
select * from my_areas where name = 'Ireland';

rem 26 counties
select * from my_areas 
where parent_area_number = '1159320877'
and parent_area_code = 'SOVC';


----------------------------------------------------------------------------------------------------
--parse geo_json from staging tables
--SELECT UTL_HTTP.get_detailed_sqlerrm FROM dual;
--value := UTL_HTTP.get_header(resp, 'Location'); --get redirection URL in header
--note handling of redirect, can limit redirect
--note exception handler for sdo_util.from_geojson and then using alterntive manual procedure, but much slower than native
----------------------------------------------------------------------------------------------------
clear screen
set serveroutput on echo on timi on
DELETE FROM stage_my_areas
WHERE area_code = 'PROV';

DECLARE 
  l_clob        CLOB;
  j_root        JSON_OBJECT_T;
  j_crs         JSON_OBJECT_T;
  j_features    JSON_ARRAY_T;
  j_feature     JSON_OBJECT_T;
  j_properties  JSON_OBJECT_T;
  j_geometry    JSON_OBJECT_T;

  l_geom        MDSYS.SDO_GEOMETRY;
  l_geom_centre MDSYS.SDO_GEOMETRY;
  l_centre      MDSYS.SDO_GEOMETRY;

  l_id       INTEGER;
  l_srid     VARCHAR2(10 char);
  l_name     VARCHAR2(100 char);
  l_num_pts  INTEGER;
  l_centrex  NUMBER;
  l_centrey  NUMBER;
  l_offset   NUMBER;
  
  e_json_syntax_error  EXCEPTION;
  PRAGMA exception_init(e_json_syntax_error,-40441);
BEGIN 
  SELECT geo_json INTO l_clob FROM stage_geo_data
  WHERE name = 'Provinces';
  l_clob := strava_http.clean_clob(l_clob);
  --strava_http.pretty_json(l_clob);
  j_root := JSON_OBJECT_T.parse(l_clob);

  j_crs := j_root.get_object('crs');
  l_clob := j_crs.to_clob;
  strava_http.print_clob(l_clob);
	  
  j_features := j_root.get_array('features');
  l_srid     := REGEXP_SUBSTR(j_crs.get_object('properties').get_string('name'),'[^:]+',1,2);
  FOR i IN 0 .. j_features.get_size - 1 LOOP
    j_feature := TREAT(j_features.get(i) AS JSON_OBJECT_T);
    j_properties := j_feature.get_object('properties');
	IF j_properties IS NULL THEN 
	  dbms_output.put_line('J_PROPERTIES is null');
	ELSE
      l_clob := j_properties.to_clob;
	  strava_http.print_clob(l_clob);
	  l_id               := j_properties.get_string('PV_ID');
	  l_name             := j_properties.get_string('PROVINCE');
      --l_name             := initcap(j_properties.get_string('ENGLISH'));
	  --l_centrex          := j_properties.get_string('CENTROID_X');
	  --l_centrey          := j_properties.get_string('CENTROID_Y');
	  --l_centre           := SDO_CS.TRANSFORM(SDO_GEOMETRY(2001, l_srid, SDO_POINT_TYPE(l_centrex, l_centrey, NULL),NULL,NULL),4326);
	  
      dbms_output.put_line(l_id||', '||l_srid||', '||l_name
	  --||', Centre:'||l_centre.sdo_point.x
   	  --        ||','||l_centre.sdo_point.y
	  );
	END IF;

    j_geometry := j_feature.get_object('geometry');
	IF j_geometry IS NULL THEN
	  dbms_output.put_line(l_name||': j_geometry is null');
	  l_offset := NULL;
	  l_geom := NULl;
	  l_num_pts := NULL;
	  l_geom_centre := NULL;
	ELSE
	  -- Get coordinates array
      l_clob := j_geometry.to_clob;
      
      IF i=0 THEN
        NULL;
	    --strava_http.print_clob(l_clob);
	    --strava_http.pretty_json(l_clob);
  	  END IF;

      BEGIN
	    l_geom := sdo_util.from_geojson(l_clob);
	  EXCEPTION 
	    WHEN e_json_syntax_error THEN
		  dbms_output.put_line(sqlerrm||' during parse of '||l_name||'. Switch to own function.' );
    	  l_geom := strava_sdo.build_sdo_geometry_from_geojson(j_geometry, l_srid);
	  END;

	  l_geom.SDO_SRID := TO_NUMBER(l_srid);
	  l_geom := SDO_CS.TRANSFORM(l_geom, 4326);
      l_geom := sdo_util.rectify_Geometry(SDO_CS.MAKE_2D(l_geom),0.001);	
	  l_num_pts := SDO_UTIL.GETNUMVERTICES(l_geom);
	  l_geom_centre := SDO_GEOM.SDO_CENTROID(l_geom, 0.005);
	  --l_offset := sdo_geom.sdo_distance(l_centre,l_geom_centre,0.0005);
	END IF;
    
    dbms_output.put_line('ID:'||l_id
	      ||', Province:'||l_name
		  --||', County:'||l_county
		  --||', Council:'||l_name
	      --||', Centre:'||l_geom_centre.sdo_point.x
   	      --        ||','||l_geom_centre.sdo_point.y
		  --||', Centre Offset:'||l_offset
		  ||', '||l_num_pts||' points');
	--dbms_output.put_line(SDO_UTIL.TO_WKTGEOMETRY(l_geom));
	
	INSERT INTO stage_my_areas
	(area_code, area_number, area_level, uqid, name, geom, mbr, num_pts
	, area, matchable
	) VALUES
	('PROV', l_id, 5, 'IRL'||l_id, l_name, l_geom, sdo_geom.sdo_mbr(l_geom), l_num_pts
	, SDO_GEOM.SDO_AREA(l_geom, 0.001,'unit=km'), 0
	)
	;
  END LOOP;
  Commit;
END;
/

UPDATE stage_my_areas
SET    mbr = sdo_geom.sdo_mbr(geom)
,      num_pts = SDO_UTIL.GETNUMVERTICES(geom)
,      area = sdo_geom.sdo_area(geom, unit=>'unit=sq_km')
/

----------------------------------------------------------------------------------------------------
--union 4 provinces into 1 geometry 
--doesn't work well - so found a new ireland geometry
----------------------------------------------------------------------------------------------------
select x.* 
, SDO_GEOM.VALIDATE_GEOMETRY_WITH_CONTEXT(geom, 0.0005) AS valid
from stage_my_areas x
;

/*
delete from stage_my_areas where area_code = 'SOVC';

/*INSERT INTO stage_my_areas
(area_code, area_number, uqid, name, geom)
SELECT 'SOVC', 1159320877, 'IRL0', 'Ireland'
, SDO_AGGR_UNION(SDOAGGRTYPE(geom, 0.0005))
--, SDO_AGGR_SET_UNION(SDOAGGRTYPE(geom,0.0005),0.0005) geom
FROM stage_my_areas m
WHERE m.area_code = 'PROV'
;

set serveroutput on
DECLARE 
  l_counter INTEGER := 0;
  l_geom   SDO_GEOMETRY;
BEGIN
  FOR i IN (
    SELECT * from stage_my_areas
	WHERE area_code = 'PROV'
    ORDER BY area_number
  ) LOOP
    l_counter := l_counter + 1;
    IF l_counter = 1 THEN
      dbms_output.put_line('Start with '||i.name||' ('||i.area||'sqKm)');
      l_geom := i.geom;
    ELSE
      dbms_output.put_line('Adding '||i.name||' ('||i.area||'sqKm)');
      l_geom := SDO_GEOM.SDO_UNION(i.geom, l_geom);      
    END IF;
  END LOOP;

  BEGIN
    INSERT INTO stage_my_areas
    (area_code, area_number, uqid, name, geom, matchable)
    VALUES
    ('SOVC', 372, 'IRL0', 'Ireland', l_geom, 1);
  EXCEPTION
    WHEN dup_val_on_index then
	  UPDATE stage_my_areas
	  SET geom = l_geom
	  , matchable = 1
      where area_number = 372
      and area_code = 'SOVC';
  END;
END;
*/

----------------------------------------------------------------------------------------------------
--update geometries on loaded provinces
----------------------------------------------------------------------------------------------------
UPDATE stage_my_areas
SET parent_area_code = 'SOVC'
, parent_area_number = 372
, parent_uqid = 'IRL372'
, matchable = 0
WHERE area_code = 'PROV'
;
COMMIT 
;

----------------------------------------------------------------------------------------------------
--Irish Areas loaded into areas table
----------------------------------------------------------------------------------------------------
select * from my_areas 
where area_code = 'SOVC' AND name = 'Ireland'
/

select x.* 
from stage_my_areas x
ORDER BY 1,2
;

--add counties to staging tablee
DELETE FROM stage_my_areas WHERE AREA_CODE = 'CTY';
insert into stage_my_areas
      (area_code, area_number, AREA_LEVEL, uqid, name, geom, mbr, num_pts)
select area_code, area_number, AREA_LEVEL, uqid, name, geom, mbr, num_pts
FROM my_areas m
WHERE m.parent_area_code = 'SOVC'
and m.parent_area_number = 1159320877 --ireland
and m.area_code = 'CTY' --county
;

--unmatch counties
update stage_my_areas
set parent_area_code = null, parent_area_number = NULl
where area_code = 'CTY'
/

--fast match counties
UPDATE stage_my_areas
SET (parent_area_code, parent_area_number, parent_uqid) = (
  SELECT area_code, area_number, uqid FROM stage_my_areas WHERE area_code = 'PROV' AND name = 'Connacht')
WHERE area_code = 'CTY' AND name IN('Galway', 'Leitrim', 'Mayo', 'Roscommon', 'Sligo');
UPDATE stage_my_areas
SET (parent_area_code, parent_area_number, parent_uqid) = (
  SELECT area_code, area_number, uqid FROM stage_my_areas WHERE area_code = 'PROV' AND name = 'Leinster')
WHERE area_code = 'CTY' AND name IN('Carlow','Dublin','Kildare','Kilkenny','Laois','Longford'
                                    ,'Louth','Meath','Offaly','Westmeath','Wexford','Wicklow');
UPDATE stage_my_areas
SET (parent_area_code, parent_area_number, parent_uqid) = (
  SELECT area_code, area_number, uqid FROM stage_my_areas WHERE area_code = 'PROV' AND name = 'Munster')
WHERE area_code = 'CTY' AND name IN('Clare','Cork','Kerry','Limerick','Tipperary','Waterford');
UPDATE stage_my_areas
SET (parent_area_code, parent_area_number, parent_uqid) = (
  SELECT area_code, area_number, uqid FROM stage_my_areas WHERE area_code = 'PROV' AND name = 'Ulster')
WHERE area_code = 'CTY' AND name IN('Cavan','Donegal','Monaghan');


update stage_my_areas set area_level = 2 where area_code = 'SOVC';
update stage_my_areas set area_level = 4 where area_code = 'PROV';
update my_areas set area_level = 4 where area_code = 'PROV';
update stage_my_areas set area_level = 5 where area_code = 'CTY';

select distinct area_code, area_level from stage_my_areas
order by area_level desc
/
update stage_my_areas
set area_code = trim(area_code)
, parent_area_code = trim(parent_area_code)
;

----------------------------------------------------------------------------------------------------
--locate new areas in heirarchy below newly calculated ireland
----------------------------------------------------------------------------------------------------
update stage_my_areas
set parent_area_code = null, parent_area_number = NULl
where area_code = 'CTY' 
--and area_number = 260000
/

clear screen
set serveroutput on
DECLARE
  e_general_error EXCEPTION;
PROCEDURE area_hsearch
(p_searchfor_area_code   stage_my_areas.area_code%TYPE
,p_searchfor_area_number stage_my_areas.area_number%TYPE
,p_searchfrom_code        my_areas.area_code%TYPE DEFAULT NULL
,p_searchfrom_number      my_areas.area_number%TYPE DEFAULT NULL
,p_query_type VARCHAR2 DEFAULT 'A'
,p_level INTEGER DEFAULT 0
) IS
  l_t0 timestamp; 
  l_t1 timestamp;
  l_secs NUMBER;
  l_num_rows NUMBER;
  l_pad VARCHAR2(20 CHAR) := '';
BEGIN
  l_pad := lpad('.',p_level,'.');
  l_t0 := SYSTIMESTAMP;
  
  IF p_level >2 then
    RAISE_APPLICATION_ERROR(-20000,'Recurrsion level '||p_level);
  ELSE
    dbms_output.put_line('Searching '||p_searchfor_area_code||'-'||p_searchfor_area_number
	        ||'. '||p_query_type||':'||p_searchfrom_code||'-'||p_searchfrom_number);

  END IF;
  
  FOR i IN(
   WITH x AS (
   SELECT m.area_code, m.area_number, m.name
   ,      new.area_code new_area_code, new.area_number new_area_number, new.name new_name, new.area new_area
   ,      CASE WHEN m.geom  IS NOT NULL AND new.geom IS NOT NULL THEN sdo_geom.sdo_area(SDO_GEOM.sdo_intersection(m.geom,new.geom,0.001), unit=>'unit=sq_km') 
		  END geom_area
   FROM   stage_my_areas m
   ,      stage_my_areas new
   WHERE  (  (p_query_type = 'C' AND m.parent_area_code = p_searchfrom_code AND m.parent_area_number = p_searchfrom_number) 
          OR (p_query_type = 'A' AND m.area_code        = p_searchfrom_code AND m.area_number        = p_searchfrom_number)
		  --OR (p_query_type = 'A' AND p_area_number IS NULL          AND m.area_code          = p_area_code)
          --OR (p_area_code IS NULL AND p_area_number IS NULL AND parent_area_code IS NULL AND parent_area_number IS NULL)
		  )
   AND    new.area_code = p_searchfor_area_code 
   AND    new.area_number = p_searchfor_area_number
   --and    sdo_geom.sdo_intersection(m.mbr,new.mbr,1) IS NOT NULL
   --and    sdo_geom.sdo_intersection(m.geom,new.geom,1) IS NOT NULL
   and    SDO_ANYINTERACT(m.geom, new.geom)
   and    SDO_ANYINTERACT(m.mbr, new.mbr) 
   --and    sdo_geom.RELATE(m.mbr ,'mask=covers',new.mbr ,0.001) 
   --and    sdo_geom.RELATE(m.geom,'mask=covers',new.geom,0.001) 
   --and     m.area_level <7
   and m.rowid != new.rowid
   )
   SELECT * FROM x 
   WHERE geom_area/new_area>=.9
   ORDER BY geom_area desc nulls last fetch first 1 rows only
  ) LOOP
    IF i.geom_area/i.new_area >= .99 THEN
      dbms_output.put_line(l_pad||'Found '||i.area_code||'-'||i.area_number
	                            ||':'||i.name
		  	 	 			    ||', area '||i.new_area||' km^2'
			 				    ||', intersection area '||i.geom_area||' km^2 ('||100*i.geom_area/i.new_area||'%)'
							    );

	  IF i.area_code = p_searchfor_area_code AND i.area_number = p_searchfor_area_number then
	    dbms_output.put_line('Same');
	  ELSE
	    dbms_output.put_line('Updating '||i.area_code||'-'||i.area_number
		            ||' is a parent of '||p_searchfor_area_code||'-'||p_searchfor_area_number);
  	    UPDATE stage_my_areas
	    SET    parent_area_code = i.area_code
	    ,      parent_area_number = i.area_number
	    WHERE  area_code = p_searchfor_area_code 
        AND    area_number = p_searchfor_area_number;
   	    area_hsearch(p_searchfor_area_code, p_searchfor_area_number, i.area_code, i.area_number, 'C', p_level+1);
	  END IF;
	ELSE
      dbms_output.put_line(l_pad||'Not Matched '||i.area_code||'-'||i.area_number
	                            ||':'||i.name
		  	 	 			    ||', area '||i.new_area||' km^2'
			 				    ||', intersection area '||i.geom_area||' km^2 ('||100*i.geom_area/i.new_area||'%)'
							    );
	END IF;
  END LOOP;

  l_t1 := SYSTIMESTAMP;
  l_secs := 60*extract(minute FROM l_t1-l_t0)+extract(second FROM l_t1-l_t0);
  --dbms_output.put_line(l_pad||'Done '||p_searchfor_area_code||'-'||p_searchfor_area_number||':'||TO_CHAR(l_secs,'9990.999')||' secs).');
END area_hsearch;
  ----------------------------------------------------------------------------------------------------
BEGIN
  FOR i IN (
    SELECT * FROM stage_my_areas 
	WHERE area_code != 'SOVC'
    AND parent_area_number IS NULL
	FETCH FIRST 1 ROWS ONLY
  ) LOOP
    area_hsearch(i.area_code, i.area_number, 'SOVC',372, 'A', 0);
	COMMIT;
  END LOOP;
END;
/


----------------------------------------------------------------------------------------------------
--verify parent-child relationship
----------------------------------------------------------------------------------------------------
select p.area_level, p.area_code, p.area_number, p.name, p.area
,      c.area_level, c.area_code, c.area_number, c.name, c.area --, c.parent_area_code,c.parent_area_number
,      SDO_ANYINTERACT(p.geom, c.geom) any_interact
,      sdo_geom.RELATE(p.geom,'mask=covers',c.geom,0.001) covers
,      sdo_geom.sdo_area(SDO_GEOM.sdo_intersection(c.geom,p.geom,0.001), unit=>'unit=sq_km') 
from stage_my_areas c, stage_my_areas p
where 1=1
and c.parent_area_number = p.area_number
AND c.parent_area_Code = p.area_code 
and c.name IN('Leinster','Dublin')
order by 1,2,3,5,6,7
/


/*----------------------------------------------------------------------------------------------------
--delete old counties
----------------------------------------------------------------------------------------------------
delete from my_areas where area_code = 'CITC' and uqid like 'IRL%';
delete from my_areas where parent_area_code = 'SOVC' and parent_area_number = 1159320877;

----------------------------------------------------------------------------------------------------
--update children to 0 where children just deleted
----------------------------------------------------------------------------------------------------
MERGE INTO my_areas u
USING (
select p.area_code, p.area_number, p.num_children, count(c.area_code) new_num_children
from my_areas p
  LEFT OUTER JOIN my_areas c ON c.parent_area_code = p.area_code AND c.parent_area_number = p.area_number
WHERE p.num_children > 0
GROUP BY p.area_code, p.area_number, p.num_children
HAVING count(c.area_code)=0
) s
ON (u.area_code = s.area_code AND u.area_number = s.area_number)
WHEN MATCHED THEN UPDATE
SET u.num_children = s.new_num_children
*/
----------------------------------------------------------------------------------------------------
-- merge staged areas into areas table
----------------------------------------------------------------------------------------------------
MERGE INTO my_areas u 
USING (select * from stage_my_areas order by area_level) s 
ON (s.area_code = u.area_code AND s.area_number = u.area_number)
WHEN MATCHED THEN UPDATE 
SET u.area_level = s.area_level
, u.parent_area_code = s.parent_area_code 
, u.parent_area_number = s.parent_area_number
, u.name = s.name
, u.matchable = s.matchable
, u.geom = s.geom
, u.mbr = s.mbr
, u.num_pts = s.num_pts
, u.num_children = null
WHEN NOT MATCHED THEN INSERT 
(area_code, area_number, uqid, area_level, parent_area_code, parent_area_number, name, matchable
, geom, mbr, num_pts, num_children)
VALUES
(s.area_code, s.area_number, s.uqid, s.area_level, s.parent_area_code, s.parent_area_number, s.name, s.matchable
, s.geom, s.mbr, s.num_pts, NULL)
/
----------------------------------------------------------------------------------------------------
-- correct parent uqid 
----------------------------------------------------------------------------------------------------
merge into my_areas u
using (
select c.area_level, c.area_code, c.area_number, p.uqid parent_uqid
from my_areas c
  inner join my_areas p
    on p.area_code = c.parent_area_code
    and p.area_number = c.parent_area_number
where c.parent_uqid IS NULL 
and c.parent_area_code IS NOT NULL
order by c.area_level
) s
ON (s.area_code = u.area_code AND s.area_number = u.area_number)
WHEN MATCHED THEN UPDATE 
SET u.parent_uqid = s.parent_uqid
/
----------------------------------------------------------------------------------------------------
--correct count of number of children
----------------------------------------------------------------------------------------------------
merge into my_areas u
using (
select p.area_code, p.area_number, p.name, p.num_children, count(c.area_number) child_count
from my_areas p
  left outer join my_areas c
    on p.area_code = c.parent_area_code
    and p.area_number = c.parent_area_number
where 1=1
--and c.num_children IS NULL
group by p.area_code, p.area_number, p.name, p.num_children
having count(c.area_number) != NVL(p.num_children,0)
) s
ON (s.area_code = u.area_code AND s.area_number = u.area_number)
WHEN MATCHED THEN UPDATE 
SET u.num_children = s.child_count
/
----------------------------------------------------------------------------------------------------
--mark activities from recalculation - but this may hit too many
----------------------------------------------------------------------------------------------------
MERGE INTO activities u
USING (
select a.activity_id, a.name, a.start_date_utc, a.processing_status, a.last_updated activity_last_updated
, MAX(ma.last_updated) area_last_updated
from activities a
,    activity_areas aa
,    my_areas ma
where a.activity_id = aa.activity_id
and ma.area_code =aa.area_code 
and ma.area_number = aa.area_number
and a.last_updated < ma.last_updated
and a.processing_status > 3
group by a.activity_id, a.name, a.start_date_utc, a.processing_status, a.last_updated
) s
ON (s.activity_id = u.activity_id)
WHEN MATCHED THEN UPDATE
SET u.processing_status = 3
/

----------------------------------------------------------------------------------------------------
--mark for recalculation of area list - optional
----------------------------------------------------------------------------------------------------
MERGE INTO activities u
USING (
select a.activity_id, a.name, a.start_date_utc, a.processing_status
, a.last_updated act_last_updated
, ma.last_updated areas_last_updated
from activities a
,    activity_areas aa
,    my_areas ma
where a.activity_id = aa.activity_id
and ma.area_code =aa.area_code 
and ma.area_number = aa.area_number
and a.last_updated < ma.last_updated
and a.processing_status >4
) s
ON (s.activity_id = u.activity_id)
WHEN MATCHED THEN UPDATE
SET u.processing_status = 4
/


----------------------------------------------------------------------------------------------------
--backup old areas
----------------------------------------------------------------------------------------------------
create table strava.backup_my_areas as 
select * from strava.my_areas
where area_number = '1159320877'
and area_code = 'SOVC';

select * from strava.backup_my_areas 
/

select * from my_areas where name = 'Ireland';

update my_areas
set parent_uqid = 'IRL372'
where parent_uqid = 'NE1159320877';

delete from my_areas
where area_number = '1159320877' and area_code = 'SOVC' /*Ireland*/
/

select * from activity_areas
where area_number = '1159320877' and area_code = 'SOVC' /*Ireland*/
/