REM ireland_counties_load.sql
REM load Ireland: Counties - National Statutory Boundaries - 2019
REM https://data.gov.ie/dataset/counties-national-statutory-boundaries-20191/resource/82310721-b5a1-4d08-b5dc-a3f2313cca4e

--DROP TABLE stage_geo_data PURGE;
CREATE TABLE stage_geo_data (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name        varchar2(200),
    geo_json    clob,
    geom        MDSYS.SDO_GEOMETRY
);

--area staging table - one row per geometry
DROP TABLE stage_my_areas;
CREATE TABLE stage_my_areas (
    AREA_CODE VARCHAR2(4 CHAR) NOT NULL , 
	AREA_NUMBER NUMBER(*,0) NOT NULL , 
	UQID VARCHAR2(20 CHAR) NOT NULL , 
 	AREA_LEVEL NUMBER(*,0), 
	PARENT_AREA_CODE VARCHAR2(4 CHAR), 
	PARENT_AREA_NUMBER NUMBER(*,0), 
	PARENT_UQID VARCHAR2(20 CHAR), 
	PROVINCE VARCHAR2(60 CHAR), --add
	COUNTY VARCHAR2(60 CHAR), 
	NAME VARCHAR2(60 CHAR), 
	MATCHABLE NUMBER(*,0) DEFAULT 1, 
--
    GEOM MDSYS.SDO_GEOMETRY ,
	MBR MDSYS.SDO_GEOMETRY , 
	AREA NUMBER,
	NUM_PTS NUMBER(*,0)	
);

ALTER TABLE stage_my_areas ADD AREA NUMBER;
ALTER TABLE stage_my_areas MATCHABLE NUMBER(*,0) DEFAULT 1;
UPDATE stage_my_areas set MATCHABLE = 1;
ALTER TABLE stage_my_areas ADD CONSTRAINT stage_my_areas_pk PRIMARY KEY (area_code, area_number);
ALTER TABLE stage_my_areas ADD CONSTRAINT stage_my_areas_pk2 UNIQUE (uqid);

INSERT INTO USER_SDO_GEOM_METADATA (
    TABLE_NAME,
    COLUMN_NAME,
    DIMINFO,
    SRID
)
VALUES (
    'STAGE_GEO_DATA',
    'GEOM',
    SDO_DIM_ARRAY(
        SDO_DIM_ELEMENT('Longitude', -180, 180, 0.005),
        SDO_DIM_ELEMENT('Latitude',  -90,  90, 0.005)
    ),
    4326
);

INSERT INTO USER_SDO_GEOM_METADATA (
    TABLE_NAME,
    COLUMN_NAME,
    DIMINFO,
    SRID
)
VALUES (
    'STAGE_MY_AREAS',
    'GEOM',
    SDO_DIM_ARRAY(
        SDO_DIM_ELEMENT('Longitude', -180, 180, 0.005),
        SDO_DIM_ELEMENT('Latitude',  -90,  90, 0.005)
    ),
    4326
);

DROP INDEX stage_geo_data_sidx
/
CREATE INDEX stage_geo_data_sidx
ON stage_geo_data(geom)
INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2
/

----------------------------------------------------------------------------------------------------
--load json from data.gov.ie
----------------------------------------------------------------------------------------------------
clear screen
set serveroutput on timi on
--TRUNCATE TABLE stage_geo_data;
DECLARE --Counties - National Statutory Boundaries - Ungeneralised - 2024
  l_url VARCHAR2(1000)
  := 'https://data-osi.opendata.arcgis.com/api/download/v1/items/e6f6418eb62442c4adbe18d0a64135a2/geojson?layers=0';
  
  l_clob CLOB;
BEGIN
  DBMS_LOB.createtemporary(l_clob, TRUE);
  l_clob:=strava_http.http_request(l_url);
  
  --strava_http.print_clob(l_clob);
  --strava_sdo.parse_geojson(l_clob);
  
  INSERT INTO stage_geo_data (geo_json)
  VALUES (l_clob);

  DBMS_LOB.freetemporary(l_clob);
END;
/
--staging data loaded from web
select * from stage_geo_data;
delete from stage_geo_data where length(geo_json) < 1000;

----------------------------------------------------------------------------------------------------
--list what we have loaded in main table
----------------------------------------------------------------------------------------------------
select * from my_areas
where name = 'Ireland'
/

--delete old children of Ireland - this will cascade into activity_areas
delete from my_areas
where parent_area_number = '1159320877'
and parent_area_code = 'SOVC';


----------------------------------------------------------------------------------------------------
--parse geo_json from staging tables
--SELECT UTL_HTTP.get_detailed_sqlerrm FROM dual;
--value := UTL_HTTP.get_header(resp, 'Location'); --get redirection URL in header
--note handling of redirect, can limit redirect
--note exception handler for sdo_util.from_geojson and then using alterntive manual procedure, but much slower than native
----------------------------------------------------------------------------------------------------
clear screen
set serveroutput on echo on timi on
TRUNCATE TABLE stage_my_areas;
DECLARE 
  l_clob        CLOB;
  j_root        JSON_OBJECT_T;
  j_crs         JSON_OBJECT_T;
  j_features    JSON_ARRAY_T;
  j_feature     JSON_OBJECT_T;
  j_properties  JSON_OBJECT_T;
  j_geometry    JSON_OBJECT_T;

  l_geom        MDSYS.SDO_GEOMETRY;
  l_geom_centre MDSYS.SDO_GEOMETRY;
  l_centre      MDSYS.SDO_GEOMETRY;

  l_id       INTEGER;
  l_srid     VARCHAR2(10 char);
  l_province VARCHAR2(100 char);
  l_county   VARCHAR2(200 char);
  l_name     VARCHAR2(100 char);
  l_num_pts  INTEGER;
  l_centrex  NUMBER;
  l_centrey  NUMBER;
  l_offset   NUMBER;
  
  e_json_syntax_error  EXCEPTION;
  PRAGMA exception_init(e_json_syntax_error,-40441);
BEGIN 
  SELECT geo_json INTO l_clob FROM stage_geo_data;
  l_clob := strava_http.clean_clob(l_clob);
  --strava_http.pretty_json(l_clob);
  j_root := JSON_OBJECT_T.parse(l_clob);

  j_crs := j_root.get_object('crs');
  l_clob := j_crs.to_clob;
  strava_http.print_clob(l_clob);
	  
  j_features := j_root.get_array('features');
  l_srid     := REGEXP_SUBSTR(j_crs.get_object('properties').get_string('name'),'[^:]+',1,2);
  FOR i IN 0 .. j_features.get_size - 1 LOOP
    j_feature := TREAT(j_features.get(i) AS JSON_OBJECT_T);
    j_properties := j_feature.get_object('properties');
	IF j_properties IS NULL THEN 
	  dbms_output.put_line('J_PROPERTIES is null');
	ELSE
      l_clob := j_properties.to_clob;
	  strava_http.print_clob(l_clob);
	  l_id               := j_properties.get_string('CO_ID');
	  l_province         := j_properties.get_string('PROVINCE');
      l_county           := initcap(j_properties.get_string('COUNTY'));
      l_name             := initcap(j_properties.get_string('ENGLISH'));
	  l_centrex          := j_properties.get_string('CENTROID_X');
	  l_centrey          := j_properties.get_string('CENTROID_Y');
	  l_centre           := SDO_CS.TRANSFORM(SDO_GEOMETRY(2001, l_srid, SDO_POINT_TYPE(l_centrex, l_centrey, NULL),NULL,NULL),4326);
	  
      dbms_output.put_line(l_id||', '||l_srid||', '||l_name||', Co. '||l_county||', Province:'||l_province
	  ||', Centre:'||l_centre.sdo_point.x
   	          ||','||l_centre.sdo_point.y
	  );
	END IF;

    j_geometry := j_feature.get_object('geometry');
	IF j_geometry IS NULL THEN
	  dbms_output.put_line(l_county||': j_geometry is null');
	  l_offset := NULL;
	  l_geom := NULl;
	  l_num_pts := NULL;
	  l_geom_centre := NULL;
	ELSE
	  -- Get coordinates array
      l_clob := j_geometry.to_clob;
      
      IF l_county = 'Carlow' THEN
        NULL;
	    --strava_http.print_clob(l_clob);
	    --strava_http.pretty_json(l_clob);
  	  END IF;

      BEGIN
	    l_geom := sdo_util.from_geojson(l_clob);
	  EXCEPTION 
	    WHEN e_json_syntax_error THEN
		  dbms_output.put_line(sqlerrm||' during parse of '||l_county||'. Switch to own function.' );
    	  l_geom := strava_sdo.build_sdo_geometry_from_geojson(j_geometry, l_srid);
	  END;

	  l_geom.SDO_SRID := TO_NUMBER(l_srid);
	  l_geom := SDO_CS.TRANSFORM(l_geom, 4326);
      l_geom := sdo_util.rectify_Geometry(SDO_CS.MAKE_2D(l_geom),0.001);	
	  l_num_pts := SDO_UTIL.GETNUMVERTICES(l_geom);
	  l_geom_centre := SDO_GEOM.SDO_CENTROID(l_geom, 0.005);
	  --l_offset := sdo_geom.sdo_distance(l_centre,l_geom_centre,0.0005);
	END IF;
    
    dbms_output.put_line('ID:'||l_id
	      ||', Province:'||l_province
		  ||', County:'||l_county
		  ||', Council:'||l_name
	      ||', Centre:'||l_geom_centre.sdo_point.x
   	              ||','||l_geom_centre.sdo_point.y
		  --||', Centre Offset:'||l_offset
		  ||', '||l_num_pts||' points');
	--dbms_output.put_line(SDO_UTIL.TO_WKTGEOMETRY(l_geom));
	
	INSERT INTO stage_my_areas
	(area_code, area_number, area_level, uqid, province, county, name, geom, mbr, num_pts
	--, area
	) VALUES
	('CTY', l_id, 5, 'IRL'||l_id, l_province, l_county, l_name, l_geom, sdo_geom.sdo_mbr(l_geom), l_num_pts
	--, SDO_GEOM.SDO_AREA(l_geom, 0.001,'unit=km')
	)
	;
  END LOOP;
  Commit;
END;
/

----------------------------------------------------------------------------------------------------
--update geometries on loaded counties - though also includes city councils
----------------------------------------------------------------------------------------------------
UPDATE stage_my_areas
SET parent_area_code = 'SOVC'
, parent_area_number = 1159320877
, parent_uqid = 'NE1159320877'
/
COMMIT
/


----------------------------------------------------------------------------------------------------
--Irish Areas loaded into areas table
--citc - 6
----------------------------------------------------------------------------------------------------
select * 
from my_areas 
where uqid like 'IRL%'
and area_code like 'CITC'
/

select x.* 
, count(*) over (partition by province) num_councils
, min(uqid) over (partition by province) min_uqid
, min(area_code) over (partition by province) min_area_code
from stage_my_areas x
ORDER BY province, county
/

----------------------------------------------------------------------------------------------------
--unify city councils to produce county area
--sdo_union is quite slow - takes around 4 minutes for the 3 city/counnties
----------------------------------------------------------------------------------------------------
ROLLBACK;
DECLARE
  l_union MDSYS.SDO_GEOMETRY;
  l_counter INTEGER;
  l_tol NUMBER := 0.001;
BEGIN
  FOR i IN(
    SELECT area_code, county
    , min(area_number)-1 parent_area_number
    ,count(*) num_areas
    from stage_my_areas
    where area_code = 'CTY'
    group by area_code, county
    having count(*)>1
  ) LOOP

    --update children
    UPDATE stage_my_areas
	SET    area_code = 'CITC'
	,      area_level = 6
	,      parent_area_code = i.area_code
	,      parent_area_number = i.parent_area_number
	,      parent_uqid = 'IRL'||i.parent_area_number
	,      matchable = 0
	WHERE  area_code = i.area_code
	AND    county = i.county;

    -- insert parent (ie county rows)
    INSERT INTO stage_my_areas
	(area_code, area_number, uqid, area_level, matchable
	,parent_area_code, parent_area_number, parent_uqid
	,county, name)
	VALUES
	(i.area_code, i.parent_area_number, 'IRL'||i.parent_area_number, 5, 1
	,'SOVC', 1159320877, 'NE1159320877'
	,i.county,i.county);
    
	l_union := NULL;
	l_counter := 0;
	/*need to rectify geometries others union is null`*/
    FOR j IN (
	  SELECT a.* 
	  ,      SDO_CS.MAKE_2D(SDO_UTIL.RECTIFY_GEOMETRY(geom, l_tol)) rect_geom
	  FROM   stage_my_areas a
	  WHERE  area_code = 'CITC'
	  AND    county = i.county
	  AND    parent_area_code = i.area_code
	  AND    parent_area_number = i.parent_area_number
	  ORDER BY area_number
    ) LOOP
      dbms_output.put_line('+'||j.area_code||'.'||j.area_number||':'||j.name||', Area:'||j.area||'KmSq');
	  l_counter := l_counter + 1;
      IF l_counter = 1 THEN
        l_union := j.rect_geom;
      ELSE
        l_union := SDO_GEOM.SDO_UNION(j.rect_geom, l_union, 1);
      END IF;
	  dbms_output.put_line('Area:'||SDO_GEOM.SDO_AREA(l_union, l_tol)/1e6);
	
    END LOOP;
	
    dbms_output.put_line('='||i.area_code||'.'||i.parent_area_number||':'||i.county);
	UPDATE stage_my_areas
	SET    geom = l_union
    ,      num_pts = SDO_UTIL.GETNUMVERTICES(l_union)
    ,      mbr = sdo_geom.sdo_mbr(l_union)
    ,      area = SDO_GEOM.SDO_AREA(l_union, l_tol,'unit=sq_km')
    WHERE  area_code = i.AREA_CODE
	AND    area_number = i.parent_area_number;
  END LOOP;
END;
/

----------------------------------------------------------------------------------------------------
select *
from stage_my_areas x
ORDER BY county, uqid
/

--rollback;
select count(*) from activity_areas;

----------------------------------------------------------------------------------------------------
--delete old counties
----------------------------------------------------------------------------------------------------
delete from my_areas where area_code = 'CITC' and uqid like 'IRL%';
delete from my_areas where parent_area_code = 'SOVC' and parent_area_number = 1159320877;

----------------------------------------------------------------------------------------------------
--update children to 0 where children just deleted
----------------------------------------------------------------------------------------------------
MERGE INTO my_areas u
USING (
select p.area_code, p.area_number, p.num_children, count(c.area_code) new_num_children
from my_areas p
  LEFT OUTER JOIN my_areas c ON c.parent_area_code = p.area_code AND c.parent_area_number = p.area_number
WHERE p.num_children > 0
GROUP BY p.area_code, p.area_number, p.num_children
HAVING count(c.area_code)=0
) s
ON (u.area_code = s.area_code AND u.area_number = s.area_number)
WHEN MATCHED THEN UPDATE
SET u.num_children = s.new_num_children
/

----------------------------------------------------------------------------------------------------
--reinsert new counties etc from staging table
----------------------------------------------------------------------------------------------------
select count(*) from activity_areas;
insert into my_areas
(      area_code, area_number, uqid, area_level, parent_area_code, parent_area_number, parent_uqid, matchable, geom, mbr, num_pts, name)
select area_code, area_number, uqid, area_level, parent_area_code, parent_area_number, parent_uqid, matchable, geom, mbr, num_pts
,      CASE WHEN area_code = 'CTY' THEN name
            ELSE county END
from stage_my_areas
/

----------------------------------------------------------------------------------------------------
--recalc num_children on these records and update if different
----------------------------------------------------------------------------------------------------
MERGE INTO my_areas u
USING (
select p.area_code, p.area_number, p.num_children, count(c.area_code) new_num_children
from my_areas p
  LEFT OUTER JOIN my_areas c ON c.parent_area_code = p.area_code AND c.parent_area_number = p.area_number
GROUP BY p.area_code, p.area_number, p.num_children
HAVING count(c.area_code)!=NVL(p.num_children,0)
) s
ON (u.area_code = s.area_code AND u.area_number = s.area_number)
WHEN MATCHED THEN UPDATE
SET u.num_children = s.new_num_children
/


----------------------------------------------------------------------------------------------------
--mark activities from recalculation
----------------------------------------------------------------------------------------------------
MERGE INTO activities u
USING (
select a.activity_id, a.name, a.start_date_utc, a.processing_status
, a.last_updated activity_last_updated
, ma.last_updated area_last_updated
from activities a
,    activity_areas aa
,    my_areas ma
where a.activity_id = aa.activity_id
and ma.area_code =aa.area_code 
and ma.area_number = aa.area_number
and a.last_updated < ma.last_updated
and a.processing_status > 3
) s
ON (s.activity_id = u.activity_id)
WHEN MATCHED THEN UPDATE
SET u.processing_status = 3
/

----------------------------------------------------------------------------------------------------
--name correction update name to county ONLY
----------------------------------------------------------------------------------------------------
MERGE INTO my_areas u 
USING (SELECT * FROM stage_my_areas where area_code = 'CTY') s 
ON (u.area_code = s.area_code AND u.area_number = s.area_number)
WHEN MATCHED THEN UPDATE
SET u.name = s.county
, u.matchable = 1
/
----------------------------------------------------------------------------------------------------
--name correction update name to countcl namee
----------------------------------------------------------------------------------------------------
MERGE INTO my_areas u 
USING (SELECT * FROM stage_my_areas where area_code = 'CITC') s 
ON (u.area_code = s.area_code AND u.area_number = s.area_number)
WHEN MATCHED THEN UPDATE
SET u.name = s.county
, u.matchable = 0
/
----------------------------------------------------------------------------------------------------
--mark for recalculation of area list
----------------------------------------------------------------------------------------------------
MERGE INTO activities u
USING (
select a.activity_id, a.name, a.start_date_utc, a.processing_status
, a.last_updated act_last_updated
, ma.last_updated areas_last_updated
from activities a
,    activity_areas aa
,    my_areas ma
where a.activity_id = aa.activity_id
and ma.area_code =aa.area_code 
and ma.area_number = aa.area_number
and a.last_updated < ma.last_updated
and a.processing_status >4
) s
ON (s.activity_id = u.activity_id)
WHEN MATCHED THEN UPDATE
SET u.processing_status = 4
/
desc activities


rollback;

--end