REM Italy_load_country.sql
REM https://simplemaps.com/gis/country/it


--DROP TABLE stage_geo_data PURGE;
CREATE TABLE stage_geo_data (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name        varchar2(200),
    geo_json    clob,
    geom        MDSYS.SDO_GEOMETRY
);

--area staging table - one row per geometry
DROP TABLE stage_my_areas PURGE;
CREATE TABLE stage_my_areas (
    AREA_CODE VARCHAR2(4 CHAR) NOT NULL , 
	AREA_NUMBER NUMBER(*,0) NOT NULL , 
	UQID VARCHAR2(20 CHAR) NOT NULL , 
 	AREA_LEVEL NUMBER(*,0), 
	PARENT_AREA_CODE VARCHAR2(4 CHAR), 
	PARENT_AREA_NUMBER NUMBER(*,0), 
	PARENT_UQID VARCHAR2(20 CHAR), 
	NAME VARCHAR2(100 CHAR), 
	MATCHABLE NUMBER(*,0) DEFAULT 1, 
--
    GEOM MDSYS.SDO_GEOMETRY ,
	MBR MDSYS.SDO_GEOMETRY , 
	AREA NUMBER,
	NUM_PTS NUMBER(*,0)    
);

ALTER TABLE stage_my_areas ADD CONSTRAINT stage_my_areas_pk PRIMARY KEY (area_code, area_number);
ALTER TABLE stage_my_areas ADD CONSTRAINT stage_my_areas_pk2 UNIQUE (uqid);

INSERT INTO USER_SDO_GEOM_METADATA (
    TABLE_NAME,
    COLUMN_NAME,
    DIMINFO,
    SRID
) VALUES (
    'STAGE_GEO_DATA',
    'GEOM',
    SDO_DIM_ARRAY(
        SDO_DIM_ELEMENT('Longitude', -180, 180, 0.005),
        SDO_DIM_ELEMENT('Latitude',  -90,  90, 0.005)
    ),
    4326
);

INSERT INTO USER_SDO_GEOM_METADATA (
    TABLE_NAME,
    COLUMN_NAME,
    DIMINFO,
    SRID
) VALUES (
    'STAGE_MY_AREAS',
    'GEOM',
    SDO_DIM_ARRAY(
        SDO_DIM_ELEMENT('Longitude', -180, 180, 0.005),
        SDO_DIM_ELEMENT('Latitude',  -90,  90, 0.005)
    ),
    4326
);

DROP INDEX stage_geo_data_sidx
/

----------------------------------------------------------------------------------------------------
--load json FROM https://simplemaps.com/gis/country/it#
----------------------------------------------------------------------------------------------------
clear screen
set serveroutput on 
set timi on
--TRUNCATE TABLE strava.stage_geo_data;;

SELECT object_name, bytes/1024/1024 Mb
FROM table(
  DBMS_CLOUD.LIST_objects
  (credential_name => 'OBJECT_STORE_CRED'
  ,location_uri => 'https://objectstorage.uk-london-1.oraclecloud.com/n/lrp1qmpxv8ea/b/bucket-gofaster1/o/'
  ));


DECLARE
    l_blob BLOB;
BEGIN
    -- Read the file from Object Storage into CLOB
    l_blob := DBMS_CLOUD.GET_OBJECT
              (credential_name => 'OBJECT_STORE_CRED'
              ,object_uri      => 'https://objectstorage.uk-london-1.oraclecloud.com/n/lrp1qmpxv8ea/b/bucket-gofaster1/o/it0.json'
              );
    --l_clob := CAST(l_blob AS CLOB);
    -- Insert into table
    INSERT INTO strava.stage_geo_data(name, geo_json)
    VALUES ('Italy', l_blob);

    COMMIT;
END;
/

----------------------------------------------------------------------------------------------------
--list what we have loaded in main table
----------------------------------------------------------------------------------------------------
--staging data loaded FROM web
SELECT x.*, length(geo_json) FROM strava.stage_geo_data x;
--SELECT * FROM my_area_codes ORDER BY area_level;
COMMIT;
----------------------------------------------------------------------------------------------------
--parse geo_json FROM staging tables
--SELECT UTL_HTTP.get_detailed_sqlerrm FROM dual;
--value := UTL_HTTP.get_header(resp, 'Location'); --get redirection URL in header
--note handling of redirect, can limit redirect
--note exception handler for sdo_util.from_geojson and then using alterntive manual procedure, but much slower than native
----------------------------------------------------------------------------------------------------
clear screen
set serveroutput on echo on timi on
TRUNCATE TABLE stage_my_areas;
DECLARE 
  l_clob        CLOB;
  j_root        JSON_OBJECT_T;
  j_crs         JSON_OBJECT_T;
  j_features    JSON_ARRAY_T;
  j_feature     JSON_OBJECT_T;
  j_properties  JSON_OBJECT_T;
  j_geometry    JSON_OBJECT_T;

  l_geom        MDSYS.SDO_GEOMETRY;

  l_id         INTEGER;
  l_srid       VARCHAR2(10 char);
  l_name       VARCHAR2(100 char);
  l_num_pts    INTEGER;
  
  e_json_syntax_error  EXCEPTION;
  PRAGMA exception_init(e_json_syntax_error,-40441);
BEGIN 
  SELECT geo_json INTO l_clob FROM stage_geo_data WHERE name = 'Italy';
  l_clob := strava_http.clean_clob(l_clob);
  --strava_http.pretty_json(l_clob);
  j_root := JSON_OBJECT_T.parse(l_clob);

  j_crs := j_root.get_object('crs');
  --l_clob := j_crs.to_clob;
  --strava_http.print_clob(l_clob);
	  
  j_features := j_root.get_array('features');
  --l_srid     := REGEXP_SUBSTR(j_crs.get_object('properties').get_string('name'),'[^:]+',1,2);
  l_srid := 4326;
  FOR i IN 0 .. j_features.get_size - 1 LOOP
    j_feature := TREAT(j_features.get(i) AS JSON_OBJECT_T);
    j_properties := j_feature.get_object('properties');
	IF j_properties IS NULL THEN 
	  dbms_output.put_line('J_PROPERTIES is null');
	ELSE
      --l_clob := j_properties.to_clob;
	  strava_http.print_clob(l_clob);
	  l_id               := j_properties.get_string('ID');
      l_name             := initcap_placename(j_properties.get_string('NAME'));
      --dbms_output.put_line(l_id||', '||l_srid||', '||l_name);
	END IF;

    j_geometry := j_feature.get_object('geometry');
	IF j_geometry IS NULL THEN
	  dbms_output.put_line(l_name||': j_geometry is null');
	  l_geom := NULL;
	ELSE
	  -- Get coordinates array
      l_clob := j_geometry.to_clob;
      
      IF i = -4 THEN
	    strava_http.pretty_json(l_clob);
  	  END IF;

      BEGIN
	    l_geom := sdo_util.from_geojson(l_clob);
	  EXCEPTION 
	    WHEN e_json_syntax_error THEN
		  dbms_output.put_line(sqlerrm||' during parse of '||l_name||' ('||l_id||'). Switch to own function.' );
    	  l_geom := strava_sdo.build_sdo_geometry_from_geojson(j_geometry, l_srid);
	  END;

	  l_geom.SDO_SRID := TO_NUMBER(l_srid);
	  IF l_srid != 4326 THEN
  	    l_geom := SDO_CS.TRANSFORM(l_geom, 4326);
   	    l_geom.SDO_SRID := 4326;
	  END IF;
	  l_geom := sdo_util.rectify_Geometry(SDO_CS.MAKE_2D(l_geom),0.001);
	
	  --l_num_pts := SDO_UTIL.GETNUMVERTICES(l_geom);
	END IF;
    
    dbms_output.put_line(i
	      ||','||l_id
		  ||','||l_name
		  );
	--dbms_output.put_line(SDO_UTIL.TO_WKTGEOMETRY(l_geom));
	
	INSERT INTO stage_my_areas
	(area_code, area_number, area_level, uqid, name, geom
	, mbr, num_pts, area)
	VALUES
	('SOVC', 380, 2, 'ITA', l_name, l_geom
	,sdo_geom.sdo_mbr(l_geom)
	,SDO_UTIL.GETNUMVERTICES(l_geom)
	,SDO_GEOM.SDO_AREA(l_geom, 0.001,'unit=sq_km'))
	;
  END LOOP;
  COMMIT;
END;
/

select a.*,SDO_GEOM.SDO_AREA(geom, 0.001,'unit=sq_km')
from my_areas a
where name = 'Italy'
or parent_area_number IN(380,1159320919)
/

select * from stage_my_areas;

----------------------------------------------------------------------------------------------------
-- verify area match 
----------------------------------------------------------------------------------------------------
select m.name, a.name
,      sdo_anyinteract(m.mbr,a.mbr) mbr_interact
,      sdo_anyinteract(m.geom,a.geom) geom_interact
,      sdo_relate(m.geom,a.geom,'OVERLAPBDYINTERSECT') overlapping
,      sdo_relate(m.geom,a.geom,'TOUCH') touching
,      sdo_relate(m.geom,a.geom,'INSIDE') inside
,      sdo_geom.sdo_area(a.geom, unit=>'unit=sq_km') area_km_sq
,      sdo_geom.sdo_area(m.geom, unit=>'unit=sq_km') staging_km_sq
,      sdo_geom.sdo_area(sdo_geom.sdo_intersection(m.geom,a.geom,1), unit=>'unit=sq_km') intersect_km_sq    
from stage_my_areas m, my_areas a
where 1=1
and a.area_code = 'SOVC' and a.area_number IN(380,1159320919)
--and m.area_code = 'TOWN'
--and m.area_number = 15008
--and a.area_code = m.parent_area_code
--and a.area_number = m.parent_area_number
fetch first 10 rows only
/
----------------------------------------------------------------------------------------------------
-- merge staged areas into areas table
----------------------------------------------------------------------------------------------------
MERGE INTO my_areas u 
USING (select * from stage_my_areas order by area_level) s 
ON (s.area_code = u.area_code AND s.area_number = u.area_number)
WHEN MATCHED THEN UPDATE 
SET u.area_level = s.area_level
, u.parent_area_code = s.parent_area_code 
, u.parent_area_number = s.parent_area_number
, u.name = s.name
, u.matchable = s.matchable
, u.geom = s.geom
, u.mbr = s.mbr
, u.num_pts = s.num_pts
, u.num_children = null
WHEN NOT MATCHED THEN INSERT 
(area_code, area_number, uqid, area_level, parent_area_code, parent_area_number, name, matchable
, geom, mbr, num_pts, num_children)
VALUES
(s.area_code, s.area_number, s.uqid, s.area_level, s.parent_area_code, s.parent_area_number, s.name, s.matchable
, s.geom, s.mbr, s.num_pts, NULL)
/

UPDATE my_areas
SET parent_area_number = 380
, parent_uqid = 'ITA'
WHERE parent_area_code = 'SOVC'
AND parent_area_number IN(1159320919)
And area_code = 'GEOS'
/
UPDATE my_areas
SET parent_uqid = 'ITA'
WHERE parent_uqid = 'NE1159320919'
/
DELETE FROM my_areas
WHERE area_code = 'SOVC'
AND area_number IN(1159320919)
/

select a.*,SDO_GEOM.SDO_AREA(geom, 0.001,'unit=sq_km')
from my_areas a
where area_code IN('SOVC','GEOS')
and (name = 'Italy'
or parent_area_number IN(380,1159320919)
or area_number IN(380,1159320919)
)
/
----------------------------------------------------------------------------------------------------
--mark activities from recalculation - but this may hit too many
----------------------------------------------------------------------------------------------------
MERGE INTO activities u
USING (
select a.activity_id, a.name, a.start_date_utc, a.processing_status, a.last_updated activity_last_updated
, MAX(ma.last_updated) area_last_updated
from activities a
,    activity_areas aa
,    my_areas ma
where a.activity_id = aa.activity_id
and ma.area_code =aa.area_code 
and ma.area_number = aa.area_number
and a.last_updated < ma.last_updated
and a.processing_status > 3
group by a.activity_id, a.name, a.start_date_utc, a.processing_status, a.last_updated
) s
ON (s.activity_id = u.activity_id)
WHEN MATCHED THEN UPDATE
SET u.processing_status = 3
/
--EXECUTE dbms_Scheduler.run_job('STRAVA.CREATE_ACTIVITY_HSEARCH_UPD_ALL_JOB',FALSE) /*refresh all activity areas-can take time*/;

----------------------------------------------------------------------------------------------------
--mark for recalculation of area list - optional
----------------------------------------------------------------------------------------------------
MERGE INTO activities u
USING (
select a.activity_id, a.name, a.start_date_utc, a.processing_status
, a.last_updated act_last_updated
, ma.last_updated areas_last_updated
from activities a
,    activity_areas aa
,    my_areas ma
where a.activity_id = aa.activity_id
and ma.area_code =aa.area_code 
and ma.area_number = aa.area_number
and a.last_updated < ma.last_updated
and a.processing_status >4
) s
ON (s.activity_id = u.activity_id)
WHEN MATCHED THEN UPDATE
SET u.processing_status = 4
/

--EXECUTE dbms_Scheduler.run_job('STRAVA.ACTIVITY_AREA_LIST_UPD_ALL_JOB',FALSE) /*this runs a job to create the update jobs*/; 
--EXECUTE dbms_Scheduler.run_job('STRAVA.UPDATE_STRAVA_ACTIVTY_JOB') /*in current session*/;
--EXECUTE dbms_Scheduler.run_job('STRAVA.UPDATE_STRAVA_ACTIVTY_JOB',FALSE);