REM load_belgium.sql
REM belgium ISO 056
----------------------------------------------------------------------------------------------------
REM regionsgeweste-belgium https://www.odwb.be/explore/dataset/regionsgeweste-belgium/information/?disjunctive.reg_code&disjunctive.reg_name_fr&disjunctive.reg_name_nl&disjunctive.reg_name_de&sort=year
REM 4 REG : Régions/Geweste       3 https://hub.huwise.com/api/explore/v2.1/catalog/datasets/georef-belgium-region/exports/geojson
REM 5 PROV: Provinces/Provincies 10 https://hub.huwise.com/api/explore/v2.1/catalog/datasets/georef-belgium-province/exports/geojson
REM 6 ARR : Arrondissements      43 https://hub.huwise.com/api/explore/v2.1/catalog/datasets/georef-belgium-arrondissement/exports/geojson/
REM 7 CANT: Cantons/Kieskantone 835 https://hub.huwise.com/api/explore/v2.1/catalog/datasets/georef-belgium-canton-millesime/exports/geojson
REM 8 COMM: Communes/Gemeente   565 https://hub.huwise.com/api/explore/v2.1/catalog/datasets/georef-belgium-municipality/exports/geojson
REM 9 Sections municipales/Deelgemeente 2664 https://hub.huwise.com/api/explore/v2.1/catalog/datasets/georef-belgium-submunicipality/exports/geojson
-------------------------------------------------------------
--area codes
----------------------------------------------------------------------------------------------------
INSERT INTO my_area_codes VALUES ('ARR','Arrondisment',6);
COMMIT;

select * from my_area_codes order by area_level
/

select area_code from stage_my_areas
minus 
select area_code from my_area_codes 
/
----------------------------------------------------------------------------------------------------
--stage_geo_data --area staging table - one row per geometry
----------------------------------------------------------------------------------------------------
--DROP TABLE stage_geo_data PURGE;
CREATE TABLE stage_geo_data (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name        varchar2(200),
    geo_json    clob,
    geom        MDSYS.SDO_GEOMETRY,
	constraint stage_geo_date_pk primary key (id)
);

----------------------------------------------------------------------------------------------------
--tables
----------------------------------------------------------------------------------------------------
DROP TABLE stage_my_areas PURGE;
CREATE TABLE stage_my_areas (
    AREA_CODE VARCHAR2(4 CHAR) NOT NULL , 
	AREA_NUMBER NUMBER(*,0) NOT NULL , 
 	AREA_LEVEL NUMBER(*,0), 
	PARENT_AREA_CODE VARCHAR2(4 CHAR), 
	PARENT_AREA_NUMBER NUMBER(*,0),
	REG_CODE NUMBER (*,0),
	NAME_FR VARCHAR2(200 CHAR), 
	NAME_NL VARCHAR2(200 CHAR), 
	NAME VARCHAR2(200 CHAR), 
	MATCHABLE NUMBER(*,0) DEFAULT 1, 
	SUFFIX VARCHAR2(30 CHAR),
--
    GEOM MDSYS.SDO_GEOMETRY ,
	MBR MDSYS.SDO_GEOMETRY , 
	AREA NUMBER,
	NUM_PTS NUMBER(*,0)	
);

ALTER TABLE stage_my_areas ADD AREA NUMBER;
ALTER TABLE stage_my_areas MATCHABLE NUMBER(*,0) DEFAULT 1;
ALTER TABLE stage_my_areas ADD SUFFIX VARCHAR2(20 CHAR);
UPDATE stage_my_areas set MATCHABLE = 1;
ALTER TABLE stage_my_areas ADD CONSTRAINT stage_my_areas_pk PRIMARY KEY (area_code, area_number);
ALTER TABLE stage_my_areas ADD CONSTRAINT stage_my_areas_uk UNIQUE (gemeinde_id)
alter table stage_my_areas
add constraint stage_my_areas_rfk_area_code foreign key (parent_area_code, parent_area_number) references stage_my_areas (area_code, area_number);

INSERT INTO USER_SDO_GEOM_METADATA (
    TABLE_NAME,
    COLUMN_NAME,
    DIMINFO,
    SRID
)
VALUES (
    'STAGE_GEO_DATA',
    'GEOM',
    SDO_DIM_ARRAY(
        SDO_DIM_ELEMENT('Longitude', -180, 180, 0.005),
        SDO_DIM_ELEMENT('Latitude',  -90,  90, 0.005)
    ),
    4326
);

INSERT INTO USER_SDO_GEOM_METADATA (
    TABLE_NAME,
    COLUMN_NAME,
    DIMINFO,
    SRID
)
VALUES (
    'STAGE_MY_AREAS',
    'GEOM',
    SDO_DIM_ARRAY(
        SDO_DIM_ELEMENT('Longitude', -180, 180, 0.005),
        SDO_DIM_ELEMENT('Latitude',  -90,  90, 0.005)
    ),
    4326
);

DROP INDEX stage_geo_data_sidx
/
CREATE INDEX stage_geo_data_sidx
ON stage_geo_data(geom)
INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2
/

----------------------------------------------------------------------------------------------------
--Load GeoJSON from URL
--https://hub.huwise.com/explore/assets/georef-germany-gemeinde/
----------------------------------------------------------------------------------------------------
clear screen
set serveroutput on timi on echo on
--TRUNCATE TABLE stage_geo_data;

DECLARE   
PROCEDURE load_geojson_url(p_id NUMBER, p_url varchar2) IS
  l_clob CLOB;
BEGIN
  DBMS_LOB.createtemporary(l_clob, TRUE);
  l_clob:=strava_http.http_request(p_url);
  --strava_http.print_clob(l_clob);
  --strava_sdo.parse_geojson(l_clob);
  INSERT INTO stage_geo_data (id, geo_json) VALUES (p_id, l_clob);

  DBMS_LOB.freetemporary(l_clob);
END load_geojson_url;
BEGIN
  load_geojson_url(1,'https://hub.huwise.com/api/explore/v2.1/catalog/datasets/georef-belgium-region/exports/geojson');
  load_geojson_url(2,'https://hub.huwise.com/api/explore/v2.1/catalog/datasets/georef-belgium-province/exports/geojson');
  load_geojson_url(3,'https://hub.huwise.com/api/explore/v2.1/catalog/datasets/georef-belgium-arrondissement/exports/geojson/');
  load_geojson_url(4,'https://hub.huwise.com/api/explore/v2.1/catalog/datasets/georef-belgium-canton-millesime/exports/geojson');
  load_geojson_url(5,'https://hub.huwise.com/api/explore/v2.1/catalog/datasets/georef-belgium-municipality/exports/geojson');
  load_geojson_url(6,'https://hub.huwise.com/api/explore/v2.1/catalog/datasets/georef-belgium-submunicipality/exports/geojson');
END;
/

--staging data loaded from web
select * from stage_geo_data;
delete from stage_geo_data where length(geo_json) < 1000;
----------------------------------------------------------------------------------------------------
-- Load staged GeoJSON into stage areas
----------------------------------------------------------------------------------------------------
clear screen
set serveroutput on size unlimited echo on timi on 
ALTER TABLE stage_my_areas ADD (REG_CODE NUMBER (*,0));
ALTER TABLE stage_my_areas ADD (PROV_CODE NUMBER (*,0));
ALTER TABLE stage_my_areas ADD (ARR_CODE NUMBER (*,0));
ALTER TABLE stage_my_areas ADD (CAN_CODE NUMBER (*,0));
ALTER TABLE stage_my_areas ADD (MUN_CODE NUMBER (*,0));
ALTER TABLE stage_my_areas ADD (SMUN_CODE VARCHAR2(20 CHAR));
TRUNCATE TABLE stage_my_areas;

DECLARE   
PROCEDURE load_geojson(p_id NUMBER) IS
  k_iso         CONSTANT VARCHAR2(3) := '056'; --country isco code
  l_clob        CLOB;
  j_root        JSON_OBJECT_T;
  j_crs         JSON_OBJECT_T;
  j_features    JSON_ARRAY_T;
  j_feature     JSON_OBJECT_T;
  j_properties  JSON_OBJECT_T;
  j_geometry    JSON_OBJECT_T;

  l_geom        MDSYS.SDO_GEOMETRY;
  l_mbr         MDSYS.SDO_GEOMETRY;
  l_area        stage_my_areas.area%TYPE;
  
  l_reg_code    stage_my_areas.reg_code%TYPE;
  l_prov_code   stage_my_areas.prov_code%TYPE;
  l_arr_code    stage_my_areas.arr_code%TYPE;
  l_can_code    stage_my_areas.can_code%TYPE;
  l_mun_code    stage_my_areas.mun_code%TYPE;
  l_smun_code   stage_my_areas.smun_code%TYPE;

  l_area_code   stage_my_areas.area_code%TYPE;
  l_area_number stage_my_areas.area_number%TYPE;
  l_area_level  stage_my_areas.area_level%TYPE;
  l_name        stage_my_areas.name%TYPE;
  l_name_fr     stage_my_areas.name_fr%TYPE;
  l_name_nl     stage_my_areas.name_nl%TYPE;
  l_parent_area_code   stage_my_areas.parent_area_code%TYPE;
  l_parent_area_number stage_my_areas.parent_area_number%TYPE;

  l_srid        VARCHAR2(10 char) := '4326';
  l_suffix      stage_my_areas.suffix%TYPE;
  l_num_pts     stage_my_areas.num_pts%TYPE;
  
  e_json_syntax_error  EXCEPTION;
  PRAGMA exception_init(e_json_syntax_error,-40441);
  e_json_null_self  EXCEPTION;
  PRAGMA exception_init(e_json_null_self,-30625);
BEGIN 
  SELECT geo_json INTO l_clob FROM stage_geo_data WHERE id = p_id;
  --l_clob := strava_http.clean_clob(l_clob);
  --strava_http.pretty_json(l_clob);
  j_root := JSON_OBJECT_T.parse(l_clob);

  j_crs := j_root.get_object('crs');
  --l_clob := j_crs.to_clob;
  --strava_http.print_clob(l_clob);
	  
  j_features := j_root.get_array('features');
  --l_srid     := REGEXP_SUBSTR(j_crs.get_object('properties').get_string('name'),'[^:]+',1,2);
  
  FOR i IN 0 .. j_features.get_size - 1 LOOP
    j_feature := TREAT(j_features.get(i) AS JSON_OBJECT_T);
    j_properties := j_feature.get_object('properties');

	IF j_properties IS NULL THEN 
	  dbms_output.put_line('J_PROPERTIES is null');
	ELSE
      --l_clob := j_properties.to_clob;
	  --strava_http.print_clob(l_clob);

	  IF p_id = 1 THEN
	    l_reg_code    := j_properties.get_array('reg_code').get_string(0);
		l_name_fr     := j_properties.get_array('reg_name_fr').get_string(0);
		l_name_nl     := j_properties.get_array('reg_name_nl').get_string(0);
		l_area_level  := 4;
		l_area_code   := 'REG';
		l_area_number := k_iso||l_reg_code;
		l_parent_area_code   := 'SOVC';
		l_parent_area_number := '1159320389';
	  ELSIF p_id = 2 THEN
	    l_reg_code    := j_properties.get_array('reg_code').get_string(0);
	    l_prov_code   := j_properties.get_array('prov_code').get_string(0);
		l_name_fr     := j_properties.get_array('prov_name_fr').get_string(0);
		l_name_nl     := j_properties.get_array('prov_name_nl').get_string(0);
		
		l_area_level  := 5;
		l_area_code   := 'PROV';
		l_area_number := k_iso||l_prov_code;
		l_parent_area_code   := 'REG';
		l_parent_area_number := k_iso||l_reg_code;
	  ELSIF p_id = 3 THEN
	    l_reg_code    := j_properties.get_array('reg_code').get_string(0);
		BEGIN
  	      l_prov_code   := j_properties.get_array('prov_code').get_string(0);
    	  l_parent_area_code   := 'PROV';
	      l_parent_area_number := k_iso||l_prov_code;
		EXCEPTION 
		  WHEN e_json_null_self THEN
		    l_prov_code := NULL;
    		l_parent_area_code   := 'REG';
	    	l_parent_area_number := k_iso||l_reg_code;
		END;
	    l_arr_code    := j_properties.get_array('arr_code').get_string(0);
		l_name_fr     := j_properties.get_array('arr_name_fr').get_string(0);
		l_name_nl     := j_properties.get_array('arr_name_nl').get_string(0);

		l_area_level  := 6;
		l_area_code   := 'ARR';
		l_area_number := k_iso||l_arr_code;
	  /*ELSIF p_id = 4 THEN -- canton
	    l_reg_code    := j_properties.get_array('reg_code').get_string(0);
		BEGIN
  	      l_prov_code   := j_properties.get_array('prov_code').get_string(0);
    	  l_parent_area_code   := 'PROV';
	      l_parent_area_number := k_iso||l_prov_code;
		EXCEPTION 
		  WHEN e_json_null_self THEN
		    l_prov_code := NULL;
    		l_parent_area_code   := 'REG';
	    	l_parent_area_number := k_iso||l_reg_code;
		END;
	    l_arr_code    := j_properties.get_array('arr_code').get_string(0);
		l_can_code    := j_properties.get_array('can_code').get_string(0);
		l_name_fr     := j_properties.get_array('can_name_fr').get_string(0);
		l_name_nl     := j_properties.get_array('can_name_nl').get_string(0);

		l_area_level  := 7;
		l_area_code   := 'CANT';
		l_area_number := k_iso||l_can_code;*/
	  ELSIF p_id = 5 THEN -- municipality
	    l_reg_code    := j_properties.get_array('reg_code').get_string(0);
		BEGIN
  	      l_prov_code   := j_properties.get_array('prov_code').get_string(0);
		EXCEPTION 
		  WHEN e_json_null_self THEN
		    l_prov_code := NULL;
		END;
	    l_arr_code    := j_properties.get_array('arr_code').get_string(0);
		l_can_code    := j_properties.get_array('can_code').get_string(0);
		l_mun_code    := j_properties.get_array('mun_code').get_string(0);
		l_name_fr     := j_properties.get_array('mun_name_fr').get_string(0);
		l_name_nl     := j_properties.get_array('mun_name_nl').get_string(0);

		l_area_level  := 7;
		l_area_code   := 'MUNC';
		l_area_number := k_iso||l_mun_code;
    	l_parent_area_code   := 'ARR';
	      l_parent_area_number := k_iso||l_arr_code;
	  ELSIF p_id = 6 THEN -- sub municipality
	    l_reg_code    := j_properties.get_array('reg_code').get_string(0);
		BEGIN
  	      l_prov_code   := j_properties.get_array('prov_code').get_string(0);
		EXCEPTION 
		  WHEN e_json_null_self THEN
		    l_prov_code := NULL;
		END;
	    l_arr_code    := j_properties.get_array('arr_code').get_string(0);
		l_can_code    := j_properties.get_array('can_code').get_string(0);
		l_mun_code    := j_properties.get_array('mun_code').get_string(0);
		l_smun_code   := j_properties.get_array('smun_code').get_string(0);
		l_name_fr     := j_properties.get_array('smun_name_fr').get_string(0);
		l_name_nl     := j_properties.get_array('smun_name_nl').get_string(0);

		l_area_level  := 8;
		l_area_code   := 'COMM';
		--l_area_number := k_iso||l_smun_code;
    	l_parent_area_code   := 'MUNC';
	    l_parent_area_number := k_iso||l_mun_code;
	  END IF;

	  IF l_name_fr LIKE 'Arrondissement d_%' THEN l_name_fr := ltrim(SUBSTR(l_name_fr,18)); 
	  END IF;
	  IF l_name_nl LIKE 'Arrondissement%' THEN l_name_nl := ltrim(substr(l_name_nl,15)); 
	  END IF;

	  IF l_name_fr LIKE 'Province d_%' THEN l_name_fr := ltrim(SUBSTR(l_name_fr,12)); 
	  END IF;
	  IF l_name_nl LIKE 'Provincie%' THEN l_name_nl := ltrim(substr(l_name_nl,10)); 
	  END IF;

	  IF l_name_fr LIKE 'Région de %' THEN l_name_fr := initcap(REPLACE(l_name_fr,'Région de ')); 
	  ELSIF l_name_fr LIKE 'Région %' THEN l_name_fr := initcap(REPLACE(l_name_fr,'Région ')); 
	  END IF;
	  IF l_name_fr LIKE '%-Capitale' THEN l_name_fr := rtrim(REPLACE(l_name_fr,'-Capitale')); 
	  END IF;
      IF l_name_nl LIKE '% Gewest%' THEN l_name_nl := rtrim(REPLACE(l_name_nl,'Gewest')); END IF;
	  IF l_name_nl LIKE '%Hoofdstedelijk%' THEN l_name_nl := rtrim(REPLACE(l_name_nl,'Hoofdstedelijk')); END IF;
	  IF l_name_nl LIKE '%-Hoofdstad%' THEN l_name_nl := rtrim(REPLACE(l_name_nl,'-Hoofdstad')); END IF;
      
      IF l_name_nl = 'Brussels' THEN l_name_nl := 'Brussel'; END IF;

	  IF l_name_fr = l_name_nl THEN l_name := l_name_fr;
	  ELSIF l_name_nl IS NULL THEN l_name := l_name_fr;
	  ELSIF l_name_fr IS NULL THEN l_name := l_name_nl;
	  ELSE l_name := l_name_fr||'/'||l_name_nl;
	  END IF;

	END IF;
    --dbms_output.put_line(l_area_number||', '||l_name);

    j_geometry := j_feature.get_object('geometry');
	IF j_geometry IS NULL THEN
	  dbms_output.put_line(l_name||': j_geometry is null');
	  l_geom := NULL;
	ELSE
	  -- Get coordinates array
      l_clob := j_geometry.to_clob;      
      BEGIN
	    l_geom := sdo_util.from_geojson(l_clob);
	  EXCEPTION 
	    WHEN e_json_syntax_error THEN
		  dbms_output.put_line(sqlerrm||' during parse of '||l_name||' ('||l_area_code||'.'||l_area_number||'). Switch to own function.' );
    	  l_geom := strava_sdo.build_sdo_geometry_from_geojson(j_geometry, l_srid);
	  END;

	  l_geom.SDO_SRID := TO_NUMBER(l_srid);
	  l_geom := SDO_CS.TRANSFORM(l_geom, 4326);
      l_geom := sdo_util.rectify_Geometry(SDO_CS.MAKE_2D(l_geom),0.001);	
      l_mbr := sdo_geom.sdo_mbr(l_geom);
	  l_num_pts := SDO_UTIL.GETNUMVERTICES(l_geom);
      --l_area := SDO_GEOM.SDO_AREA(l_geom, 0.001,'unit=km');
	END IF;
    
	/*dbms_output.put_line(l_area_number
          --||':'||l_srid
	      ||', '||l_area_code||'.'||l_area_number
		  --||' ('||l_suffix||')'
		  --||', '||l_num_pts||' points'
          --||', '||l_area||' kmsq'
          );*/
	--dbms_output.put_line(SDO_UTIL.TO_WKTGEOMETRY(l_geom));
	
  	INSERT INTO stage_my_areas
	(area_code, area_number, area_level, name_fr, name_nl, name
	,parent_area_code, parent_area_number
	,reg_code, prov_code, arr_code, can_code, mun_code, smun_code
	,geom, mbr, num_pts, area, suffix
	) VALUES
  	(l_area_code, l_area_number, l_area_level, l_name_fr, l_name_nl, l_name
	,l_parent_area_code, l_parent_area_number
	,l_reg_code, l_prov_code, l_arr_code, l_can_code, l_mun_code, l_smun_code
	, l_geom, l_mbr, l_num_pts, l_area, l_suffix
	);
	
    COMMIT;
  END LOOP;
END load_geojson;
BEGIN
  load_geojson(1);
  load_geojson(2);
  load_geojson(3);
  --load_geojson(4); --do not load cantons
  load_geojson(5);
  --load_geojson(6); --skip sunbmunicipalities
END;
/
select * from stage_my_areas 
order by area_level;

UPDATE stage_my_areas
SET    mbr = sdo_geom.sdo_mbr(geom)
,      num_pts = SDO_UTIL.GETNUMVERTICES(geom)
,      area = sdo_geom.sdo_area(geom, unit=>'unit=sq_km')
where area IS NULL
/
select * from stage_my_areas
order by area_level, area_number
;

----------------------------------------------------------------------------------------------------
-- summary of numbers of areas
----------------------------------------------------------------------------------------------------
select area_level, area_code, parent_area_code
, count(*) num_areas
from stage_my_areas
group by area_code, parent_area_code, area_level
order by 1
/
----------------------------------------------------------------------------------------------------
-- disable matchable on duplicate child names
----------------------------------------------------------------------------------------------------
UPDATE stage_my_areas c
SET    c.matchable = 0
WHERE  c.matchable = 1
AND EXISTS(
  SELECT 'X'
  FROM   stage_my_areas p
  WHERE  c.parent_area_code = p.area_Code 
  AND    c.parent_area_number = p.area_number
  AND    c.name = p.name)
/
----------------------------------------------------------------------------------------------------
--check children within parents - this should be blank
----------------------------------------------------------------------------------------------------
with x as (
select p.area_code p_area_code, p.area_number p_area_number, p.name p_name, p.area p_area
,      c.area_code c_area_code, c.area_number c_area_number, c.name c_name, c.area c_area
,      sdo_geom.sdo_area(SDO_GEOM.sdo_intersection(p.geom,c.geom,0.001), unit=>'unit=sq_km') i_area
from stage_my_areas p
  inner join stage_my_areas c ON p.area_Code = c.parent_area_code AND p.area_number = c.parent_area_number
)
select x.*, round(100*i_area/c_area,3) pct
from x
where NVL(i_area/c_area,0) < .998
/
----------------------------------------------------------------------------------------------------
REM delete existing Belgium data
----------------------------------------------------------------------------------------------------
DELETE FROM my_areas
WHERE area_code != 'SOVC'
AND (area_code,area_number) IN (
    SELECT area_code, area_number
	--, name, level, sys_connect_by_path(area_code||':'||area_number||':'||name,'/') path
    FROM   my_areas m
    START WITH area_code = 'SOVC' AND area_number = 1159320389 and name = 'Belgium'
    CONNECT BY NOCYCLE prior m.area_code   = m.parent_area_code
                   AND prior m.area_number = m.parent_area_number
    )
/
----------------------------------------------------------------------------------------------------
REM insert new belgium date
----------------------------------------------------------------------------------------------------
INSERT INTO my_areas
(AREA_CODE,AREA_NUMBER,AREA_LEVEL,PARENT_AREA_CODE,PARENT_AREA_NUMBER
,NAME,MATCHABLE,GEOM,MBR,SUFFIX,NUM_PTS,LAST_UPDATED)
SELECT AREA_CODE,AREA_NUMBER,AREA_LEVEL,PARENT_AREA_CODE,PARENT_AREA_NUMBER
,NAME,MATCHABLE,GEOM,MBR,SUFFIX,NUM_PTS,sysdate
FROM stage_my_areas
order by area_level
/

REM update names
MERGE INTO my_areas u
USING (
SELECT s.*
FROM stage_my_areas s
  INNER JOIN my_areas m ON m.area_code = s.area_code and m.area_number = s.area_number
WHERE s.name != m.name
) s 
ON (u.area_code = s.area_code and u.area_number = s.area_number)
WHEN MATCHED THEN UPDATE
SET u.name = s.name
/

----------------------------------------------------------------------------------------------------
-- disable matchable on duplicate child names
----------------------------------------------------------------------------------------------------
UPDATE my_areas c
SET    c.matchable = 0
WHERE  c.matchable = 1
AND EXISTS(
  SELECT 'X'
  FROM   my_areas p
  WHERE  c.parent_area_code = p.area_Code 
  AND    c.parent_area_number = p.area_number
  AND    c.name = p.name)
/

----------------------------------------------------------------------------------------------------
-- set matchability
----------------------------------------------------------------------------------------------------
UPDATE stage_my_areas c
SET    c.matchable = 0
WHERE  c.matchable = 1
AND EXISTS(
  SELECT 'X'
  FROM   stage_my_areas p
  WHERE  c.parent_area_code = p.area_Code 
  AND    c.parent_area_number = p.area_number
  AND    c.name = p.name)
/
----------------------------------------------------------------------------------------------------
--update number of children
----------------------------------------------------------------------------------------------------
merge into my_areas u
using (
select p.area_code, p.area_number, p.name, p.num_children, count(c.area_number) child_count
from my_areas p
  left outer join my_areas c
    on p.area_code = c.parent_area_code
    and p.area_number = c.parent_area_number
where 1=1
--and c.num_children IS NULL
group by p.area_code, p.area_number, p.name, p.num_children
having count(c.area_number) != NVL(p.num_children,0)
) s
ON (s.area_code = u.area_code AND s.area_number = u.area_number)
WHEN MATCHED THEN UPDATE 
SET u.num_children = s.child_count
/
----------------------------------------------------------------------------------------------------
--mark activities from recalculation
----------------------------------------------------------------------------------------------------
MERGE INTO activities u
USING (
select a.activity_id, a.name, a.start_date_utc, a.processing_status, a.last_updated activity_last_updated
, MAX(ma.last_updated) area_last_updated
from activities a
  INNER JOIN activity_areas aa ON a.activity_id = aa.activity_id
  INNER JOIN my_areas ma ON ma.area_code =aa.area_code and ma.area_number = aa.area_number
where ma.last_updated > sysdate -7
and a.last_updated < ma.last_updated
and a.processing_status > 3
and a.processing_status < 9
and ma.name_hierarchy like 'Belgium%'
group by a.activity_id, a.name, a.start_date_utc, a.processing_status, a.last_updated 
) s
ON (s.activity_id = u.activity_id)
WHEN MATCHED THEN UPDATE
SET u.processing_status = 3
/
----------------------------------------------------------------------------------------------------
--force mark belgium activities from recalculation
----------------------------------------------------------------------------------------------------
update activities
set processing_status = 3
where processing_status > 3 and processing_status < 9
and activity_id IN(
  select distinct aa.activity_id
  from activity_areas aa 
     INNER JOIN my_areas ma ON ma.area_code =aa.area_code and ma.area_number = aa.area_number
  where ma.name_hierarchy like 'Belgium%')
/

----------------------------------------------------------------------------------------------------
-- Belgium activities
----------------------------------------------------------------------------------------------------
select activity_id, start_date_utc, name, type, area_list, processing_from activities
where activity_id IN(
  select distinct aa.activity_id
  from activity_areas aa 
     INNER JOIN my_areas ma ON ma.area_code =aa.area_code and ma.area_number = aa.area_number
  where ma.name_hierarchy like 'Belgium%')
order by start_date_utc desc
/

----------------------------------------------------------------------------------------------------
-- Belgium area hierarchy
----------------------------------------------------------------------------------------------------
SELECT area_code, area_number, name, level
, sys_connect_by_path(area_code||':'||area_number||':'||name||' ('||NVL(num_children,0)||')','/') path
FROM   my_areas m
WHERE matchable = 1
START WITH area_code = 'SOVC' AND area_number = 1159320389 and name = 'Belgium'
CONNECT BY NOCYCLE prior m.area_code   = m.parent_area_code
               AND prior m.area_number = m.parent_area_number
/

SELECT area_code, area_number, name, level
, sys_connect_by_path(area_code||':'||area_number||':'||name||' ('||NVL(num_children,0)||')','/') path
FROM   my_areas m
WHERE matchable = 1
START WITH name = 'Belgium' AND area_code = 'SOVC' AND area_number = 1159320389 
CONNECT BY NOCYCLE prior m.area_code   = m.parent_area_code
               AND prior m.area_number = m.parent_area_number
/