rem load_malta.sql
REM Malta ISO 470  MT MLT
REM Github repository: https://github.com/DaveMicallef/Malta_AdministrativeBoundaries/tree/main
--region
--island
--district (6)
--council (68?)
----------------------------------------------------------------------------------------------------
--convert shapefile to geojson with GDAL org2ogr
----------------------------------------------------------------------------------------------------
cd C:\Program Files\GDAL\
set GDAL_DATA="C:\Program Files\GDAL\gdal-data"
set GDAL_DRIVER_PATH="C:\Program Files\GDAL\gdalplugins"
del C:\Users\david\OneDrive\Documents\Downloads\output.geojson
"C:\Program Files\GDAL\ogr2ogr" -f GeoJSON C:\Users\david\OneDrive\Documents\Downloads\output.geojson ^
  C:\Users\david\OneDrive\Documents\Downloads\Malta_AdministrativeBoundaries-main\output\localities.shp ^
  -t_srs "EPSG:4326" -sql "SELECT locality_i AS locality_id, locality_n AS locality_name, english_na AS english_name, maltese_na AS maltese_name, plain_name, aliases, island, region, statistica as statistical_district, original_n as original_name, admin_id FROM localities"
----------------------------------------------------------------------------------------------------
-- Add a new area code for autonomous commune
----------------------------------------------------------------------------------------------------
INSERT INTO my_area_codes (area_code, description, area_level)
VALUES ('CNCL','Council',8);
----------------------------------------------------------------------------------------------------
--portugal area codes: SOVC, GEOU
----------------------------------------------------------------------------------------------------
select * from my_areas where name like 'Malta';
SELECT area_code, count(*), sum(matchable)
FROM   my_areas m
START WITH area_code = 'SOVC' AND area_number = 1159321065 and name = 'Malta'
CONNECT BY NOCYCLE prior m.area_code   = m.parent_area_code
               AND prior m.area_number = m.parent_area_number
group by area_code
/

----------------------------------------------------------------------------------------------------
--stage_geo_data --area staging table - one row per geometry
----------------------------------------------------------------------------------------------------
--DROP TABLE strava.stage_geo_data PURGE;
CREATE TABLE strava.stage_geo_data (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name        varchar2(200),
    geo_json    clob,
    geom        MDSYS.SDO_GEOMETRY,
	constraint stage_geo_date_pk primary key (id)
);


----------------------------------------------------------------------------------------------------
-- load geojson from object storage - but run this as ADMIN
----------------------------------------------------------------------------------------------------
TRUNCATE TABLE strava.stage_geo_data;
DECLARE
  l_blob BLOB;
BEGIN
  -- Read the file from Object Storage into CLOB
  l_blob := DBMS_CLOUD.GET_OBJECT
            (credential_name => 'OBJECT_STORE_CRED'
            ,object_uri      => 'https://objectstorage.uk-london-1.oraclecloud.com/n/lrp1qmpxv8ea/b/bucket-gofaster1/o/output.geojson'
            );
  INSERT INTO strava.stage_geo_data(id, name, geo_json) 
  VALUES (0, 'Malta', l_blob);
  COMMIT;
END;
/

----------------------------------------------------------------------------------------------------
--staging data loaded from web
----------------------------------------------------------------------------------------------------
select x.*, length(x.geo_json) from strava.stage_geo_data x;
delete from strava.stage_geo_data where length(geo_json) < 1000;

----------------------------------------------------------------------------------------------------
--tables
----------------------------------------------------------------------------------------------------
DROP TABLE strava.stage_my_areas PURGE;
CREATE TABLE strava.stage_my_areas (
    AREA_CODE VARCHAR2(4 CHAR) NOT NULL , 
	AREA_NUMBER NUMBER(*,0) NOT NULL , 
 	AREA_LEVEL NUMBER(*,0), 
	PARENT_AREA_CODE VARCHAR2(4 CHAR), 
	PARENT_AREA_NUMBER NUMBER(*,0), 
	--NAME VARCHAR2(200 CHAR), 
	--locality_id NUMBER(*,0), 
	locality_name VARCHAR2(200 CHAR), 
	english_name VARCHAR2(200 CHAR), 
	maltese_name VARCHAR2(200 CHAR), 
	plain_name VARCHAR2(200 CHAR), 
	original_name VARCHAR2(200 CHAR), 
	island VARCHAR2(100 CHAR),
	region VARCHAR2(100 CHAR),
	admin_id VARCHAR2(20 CHAR),
	MATCHABLE NUMBER(*,0) DEFAULT 1, 
	SUFFIX VARCHAR2(30 CHAR),
--
    GEOM MDSYS.SDO_GEOMETRY ,
	MBR MDSYS.SDO_GEOMETRY , 
	AREA NUMBER,
	NUM_PTS NUMBER(*,0)	
);

ALTER TABLE stage_my_areas drop column locality_id;
ALTER TABLE stage_my_areas drop column name;
ALTER TABLE stage_my_areas ADD NAME GENERATED ALWAYS AS (RTRIM(locality_name)) VIRTUAL;
ALTER TABLE stage_my_areas ADD AREA NUMBER;
ALTER TABLE stage_my_areas MATCHABLE NUMBER(*,0) DEFAULT 1;
ALTER TABLE stage_my_areas ADD SUFFIX VARCHAR2(20 CHAR);
UPDATE stage_my_areas set MATCHABLE = 1;
ALTER TABLE stage_my_areas ADD CONSTRAINT stage_my_areas_pk PRIMARY KEY (area_code, area_number);
ALTER TABLE stage_my_areas ADD CONSTRAINT stage_my_areas_uk UNIQUE (fre_id)
alter table stage_my_areas
add constraint stage_my_areas_rfk_area_code foreign key (parent_area_code, parent_area_number) references stage_my_areas (area_code, area_number);

INSERT INTO USER_SDO_GEOM_METADATA (
    TABLE_NAME,
    COLUMN_NAME,
    DIMINFO,
    SRID
)
VALUES (
    'STAGE_GEO_DATA',
    'GEOM',
    SDO_DIM_ARRAY(
        SDO_DIM_ELEMENT('Longitude', -180, 180, 0.005),
        SDO_DIM_ELEMENT('Latitude',  -90,  90, 0.005)
    ),
    4326
);

INSERT INTO USER_SDO_GEOM_METADATA (
    TABLE_NAME,
    COLUMN_NAME,
    DIMINFO,
    SRID
)
VALUES (
    'STAGE_MY_AREAS',
    'GEOM',
    SDO_DIM_ARRAY(
        SDO_DIM_ELEMENT('Longitude', -180, 180, 0.005),
        SDO_DIM_ELEMENT('Latitude',  -90,  90, 0.005)
    ),
    4326
);

DROP INDEX stage_geo_data_sidx
/
CREATE INDEX stage_geo_data_sidx
ON stage_geo_data(geom)
INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2
/

----------------------------------------------------------------------------------------------------
-- Load staged GeoJSON into stage areas
----------------------------------------------------------------------------------------------------
clear screen
set serveroutput on echo on timi on
TRUNCATE TABLE stage_my_areas;

DECLARE   
PROCEDURE load_geojson(p_id NUMBER) IS
  k_iso         CONSTANT INTEGER := '470'; --country isco code
  l_clob        CLOB;
  j_root        JSON_OBJECT_T;
  j_crs         JSON_OBJECT_T;
  j_features    JSON_ARRAY_T;
  j_feature     JSON_OBJECT_T;
  j_properties  JSON_OBJECT_T;
  j_geometry    JSON_OBJECT_T;

  l_geom        MDSYS.SDO_GEOMETRY;
  l_mbr         MDSYS.SDO_GEOMETRY;
  l_area        stage_my_areas.area%TYPE;

  l_area_code   stage_my_areas.area_code%TYPE;
  l_area_number stage_my_areas.area_number%TYPE;
  l_area_level  stage_my_areas.area_level%TYPE;

  --l_locality_id   stage_my_areas.locality_id%TYPE;
  l_locality_name stage_my_areas.locality_name%TYPE;
  l_english_name  stage_my_areas.english_name%TYPE;
  l_maltese_name  stage_my_areas.maltese_name%TYPE;
  l_plain_name    stage_my_areas.plain_name%TYPE;
  l_original_name stage_my_areas.original_name%TYPE;
  l_island        stage_my_areas.island%TYPE;
  l_region        stage_my_areas.region%TYPE;
  l_admin_id      stage_my_areas.admin_id%TYPE;

  l_parent_area_code   stage_my_areas.parent_area_code%TYPE;
  l_parent_area_number stage_my_areas.parent_area_number%TYPE;

  l_srid        VARCHAR2(10 char) := '4326';
  l_suffix      stage_my_areas.suffix%TYPE;
  l_num_pts     stage_my_areas.num_pts%TYPE;
  
  e_json_syntax_error  EXCEPTION;
  PRAGMA exception_init(e_json_syntax_error,-40441);
BEGIN 
  SELECT geo_json INTO l_clob FROM stage_geo_data WHERE id = p_id;
  l_clob := strava_http.clean_clob(l_clob);
  --strava_http.pretty_json(l_clob);
  j_root := JSON_OBJECT_T.parse(l_clob);

  --j_crs := j_root.get_object('crs');
  --l_clob := j_crs.to_clob;
  --strava_http.print_clob(l_clob);
	  
  j_features := j_root.get_array('features');
  --l_srid     := REGEXP_SUBSTR(j_crs.get_object('properties').get_string('name'),'[^:]+',1,2);
  FOR i IN 0 .. j_features.get_size - 1 LOOP
    j_feature := TREAT(j_features.get(i) AS JSON_OBJECT_T);
    j_properties := j_feature.get_object('properties');
	IF j_properties IS NULL THEN 
	  dbms_output.put_line('J_PROPERTIES is null');
	ELSE
      l_clob := j_properties.to_clob;

	  IF p_id = 0 THEN
--{ "locality_id": 1.0, "locality_name": "ATTARD", "english_name": "Attard", "maltese_name": "?'Attard", "plain_name": "Attard", "aliases": null, "island": "Malta", "region": "Central", "statistical_district": "West", "original_name": "ATTARD", "admin_id": "NC.MT01412" }
        --l_locality_id   := j_properties.get_string('locality_id');
        l_locality_name := initcap(j_properties.get_string('locality_name'));
        l_english_name  := j_properties.get_string('english_name');
        l_maltese_name  := j_properties.get_string('maltese_name');
        l_plain_name    := j_properties.get_string('plain_name');
        l_island        := j_properties.get_string('island');
        l_region        := j_properties.get_string('region');
        l_original_name := initcap(j_properties.get_string('original_name'));
        l_admin_id      := j_properties.get_string('admin_id');
		
		l_area_level  := 8;
		l_area_code   := 'CNCL';
		l_area_number := k_iso*1e4+regexp_substr(j_properties.get_string('admin_id'),'[[:digit:]]+',1,1);
	  END IF;
	END IF;

    j_geometry := j_feature.get_object('geometry');
	IF j_geometry IS NULL THEN
	  dbms_output.put_line(l_locality_name||': j_geometry is null');
	  l_geom := NULl;
	  l_num_pts := NULL;
      l_area := NULL;
      l_mbr := NULL;
	ELSE
	  -- Get coordinates array
      l_clob := j_geometry.to_clob;
      
      BEGIN
	    l_geom := sdo_util.from_geojson(l_clob);
	  EXCEPTION 
	    WHEN e_json_syntax_error THEN
		  dbms_output.put_line(sqlerrm||' during parse of '||l_area_number||':'||l_locality_name||'. Switch to own function.' );
    	  l_geom := strava_sdo.build_sdo_geometry_from_geojson(j_geometry, l_srid);
	  END;

	  l_geom.SDO_SRID := TO_NUMBER(l_srid);
	  l_geom := SDO_CS.TRANSFORM(l_geom, 4326);
      l_geom := sdo_util.rectify_Geometry(SDO_CS.MAKE_2D(l_geom),0.001);	
      l_mbr := sdo_geom.sdo_mbr(l_geom);
	  l_num_pts := SDO_UTIL.GETNUMVERTICES(l_geom);
      --l_area := SDO_GEOM.SDO_AREA(l_geom, 0.001,'unit=km');
	END IF;
    
	/*dbms_output.put_line(l_area_number
          --||':'||l_srid
		  --||' ('||l_suffix||')'
		  --||', '||l_num_pts||' points'
          --||', '||l_area||' kmsq'
          );*/
	--dbms_output.put_line(SDO_UTIL.TO_WKTGEOMETRY(l_geom));
	
  	INSERT INTO stage_my_areas
	(area_code, area_number, area_level
	--,parent_area_code, parent_area_number
	, locality_name, english_name, maltese_name, plain_name, original_name, island, region, admin_id
	, geom, mbr, num_pts, area, suffix
	) VALUES
  	(l_area_code, l_area_number, l_area_level
	--,'CTY', TRUNC(l_area_number,-4)
	, l_locality_name, l_english_name, l_maltese_name, l_plain_name, l_original_name, l_island, l_region, l_admin_id
	, l_geom, l_mbr, l_num_pts, l_area, l_suffix
	);
	
    COMMIT;
  END LOOP;
END load_geojson;
BEGIN
  load_geojson(0);
END;
/
----------------------------------------------------------------------------------------------------
-- fix some names
----------------------------------------------------------------------------------------------------
update stage_my_areas
set english_name = locality_name
, maltese_name = locality_name
, plain_name = locality_name
, original_name = locality_name
, island = 'Gozo'
, region = 'Gozo'
where area_code = 'CNCL'
and area_number = 4702666
/
update stage_my_areas
set english_name = locality_name
, maltese_name = locality_name
, plain_name = locality_name
, original_name = locality_name
, island = 'Malta'
, region = 'West'
where area_code = 'CNCL'
and area_number = 4701450 --Rabat
/
update stage_my_areas
set region = 'Gozo'
where region like 'Gozo % Comino'
/
update stage_my_areas
set region = 'Gozo'
, island = 'Gozo'
where island like '%Comino'
/
update stage_my_areas set locality_name = replace(locality_name,' (Malta)')
where locality_name like '% (Malta)'
/
update stage_my_areas set english_name = replace(english_name,' (Malta)')
where english_name like '% (Malta)'
/
update stage_my_areas set plain_name = replace(plain_name,' (Malta)')
where plain_name like '% (Malta)'
/
update stage_my_areas set original_name = replace(original_name,' (Malta)')
where original_name like '% (Malta)'
/
----------------------------------------------------------------------------------------------------
--region
----------------------------------------------------------------------------------------------------
--delete from stage_my_areas where area_code = 'REG';
insert into stage_my_areas (area_code, area_number, area_level, region, island, geom)
select 'REG', 47000+row_number() over (order by min(admin_id)) area_number, 6
, region, island, sdo_aggr_union(sdoaggrtype(geom,1)) geom
from stage_my_areas
where area_code = 'CNCL'
group by region, island
order by 1
/
----------------------------------------------------------------------------------------------------
--island
----------------------------------------------------------------------------------------------------
insert into stage_my_areas (area_code, area_number, area_level, island, geom)
select 'GEOS', 4700+row_number() over (order by min(admin_id)) area_number, 4
, island, sdo_aggr_union(sdoaggrtype(geom,1)) geom
from stage_my_areas
where area_code = 'CNCL'
group by island
order by 1
/

----------------------------------------------------------------------------------------------------
-- set parents
----------------------------------------------------------------------------------------------------
update stage_my_areas c
set (parent_area_code, parent_area_number) = (
  SELECT area_code, area_number 
  FROM stage_my_areas P
  where p.area_code = 'REG'
  AND p.region = c.region
  and p.island = c.island
  )
where area_code = 'CNCL' 
and parent_area_code IS NULL and parent_area_number IS NULL
/
update stage_my_areas c
set (parent_area_code, parent_area_number) = (
  SELECT area_code, area_number 
  FROM stage_my_areas P
  where p.area_code = 'GEOS'
  and p.island = c.island
  )
, english_name = region
, maltese_name = region
, plain_name = region
, original_name = region
, locality_name = region
,matchable = 0
where area_code = 'REG' 
--and parent_area_code IS NULL and parent_area_number IS NULL
/
update stage_my_areas c
set parent_area_code = 'SOVC'
, parent_area_number = 1159321065
, english_name = island
, maltese_name = island
, plain_name = island
, original_name = island
, locality_name = island
where area_code = 'GEOS' 
--and parent_area_code IS NULL and parent_area_number IS NULL
/
----------------------------------------------------------------------------------------------------
-- update points etc.
----------------------------------------------------------------------------------------------------
UPDATE stage_my_areas
SET    mbr = sdo_geom.sdo_mbr(geom)
,      num_pts = SDO_UTIL.GETNUMVERTICES(geom)
,      area = sdo_geom.sdo_area(geom, unit=>'unit=sq_km')
where area IS NULL
/
----------------------------------------------------------------------------------------------------
--
----------------------------------------------------------------------------------------------------
@@simplify_stage_my_areas.sql
----------------------------------------------------------------------------------------------------
--check children within parents - this should be blank
----------------------------------------------------------------------------------------------------
with x as (
select p.area_code p_area_code, p.area_number p_area_number, p.name p_name, p.suffix p_suffix, p.area p_area
,      c.area_code c_area_code, c.area_number c_area_number, c.name c_name, c.suffix c_suffix, c.area c_area
,      sdo_geom.sdo_area(SDO_GEOM.sdo_intersection(p.geom,c.geom,0.001), unit=>'unit=sq_km') i_area
from stage_my_areas p
  inner join stage_my_areas c ON p.area_Code = c.parent_area_code AND p.area_number = c.parent_area_number
)
select * 
from x
where NVL(i_area/c_area,0) < .999
/
----------------------------------------------------------------------------------------------------
-- review of malta data
----------------------------------------------------------------------------------------------------
select * from stage_my_areas
order by area_level, island, region, area_Code
/
----------------------------------------------------------------------------------------------------
REM insert new malta date
----------------------------------------------------------------------------------------------------
INSERT INTO my_areas
(AREA_CODE,AREA_NUMBER,AREA_LEVEL,PARENT_AREA_CODE,PARENT_AREA_NUMBER
,NAME,MATCHABLE,GEOM,MBR,NUM_PTS,LAST_UPDATED)
SELECT AREA_CODE,AREA_NUMBER,AREA_LEVEL,PARENT_AREA_CODE,PARENT_AREA_NUMBER
,LOCALITY_NAME,MATCHABLE,GEOM,MBR,NUM_PTS,sysdate
FROM stage_my_areas
order by area_level
/
REM update names
MERGE INTO my_areas u
USING (
SELECT s.*
FROM stage_my_areas s
  INNER JOIN my_areas m ON m.area_code = s.area_code and m.area_number = s.area_number
WHERE s.name != m.name
) s 
ON (u.area_code = s.area_code and u.area_number = s.area_number)
WHEN MATCHED THEN UPDATE
SET u.name = s.locality_name
, u.geom = s.geom
, u.mbr = s.MBR
, u.num_pts = s.num_pts
, u.last_updated = SYSDATE
/

----------------------------------------------------------------------------------------------------
--update number of children
----------------------------------------------------------------------------------------------------
merge into my_areas u
using (
select p.area_code, p.area_number, p.name, p.num_children, count(c.area_number) child_count
from my_areas p
  left outer join my_areas c
    on p.area_code = c.parent_area_code
    and p.area_number = c.parent_area_number
where 1=1
--and c.num_children IS NULL
group by p.area_code, p.area_number, p.name, p.num_children
having count(c.area_number) != NVL(p.num_children,0)
) s
ON (s.area_code = u.area_code AND s.area_number = u.area_number)
WHEN MATCHED THEN UPDATE 
SET u.num_children = s.child_count
/



