REM load_portugal.sql
REM Districts      https://hub.huwise.com/explore/assets/georef-portugal-distrito/ 15 DIS
REM Municipalities https://hub.huwise.com/explore/assets/georef-portugal-concelho/ 308 MUNC
REM Civil parishes https://hub.huwise.com/explore/assets/georef-portugal-freguesia/ 3259 CPAR
REM 
REM Portugal=620,PRT,PT
REM SOVC 1159321187
REM GEOU 1159321193
----------------------------------------------------------------------------------------------------
--portugal area codes: SOVC, GEOU
----------------------------------------------------------------------------------------------------
SELECT area_code, count(*), sum(matchable)
FROM   my_areas m
START WITH area_code = 'SOVC' AND area_number = 1159321187 and name = 'Portugal'
CONNECT BY NOCYCLE prior m.area_code   = m.parent_area_code
               AND prior m.area_number = m.parent_area_number
group by area_code
/

----------------------------------------------------------------------------------------------------
--stage_geo_data --area staging table - one row per geometry
----------------------------------------------------------------------------------------------------
--DROP TABLE stage_geo_data PURGE;
CREATE TABLE stage_geo_data (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name        varchar2(200),
    geo_json    clob,
    geom        MDSYS.SDO_GEOMETRY,
	constraint stage_geo_date_pk primary key (id)
);

----------------------------------------------------------------------------------------------------
--tables
----------------------------------------------------------------------------------------------------
DROP TABLE stage_my_areas PURGE;
CREATE TABLE stage_my_areas (
    AREA_CODE VARCHAR2(4 CHAR) NOT NULL , 
	AREA_NUMBER NUMBER(*,0) NOT NULL , 
 	AREA_LEVEL NUMBER(*,0), 
	PARENT_AREA_CODE VARCHAR2(4 CHAR), 
	PARENT_AREA_NUMBER NUMBER(*,0), 
	NAME VARCHAR2(200 CHAR), 
	dis_ID NUMBER,
	con_ID NUMBER,
	fre_ID NUMBER,
	MATCHABLE NUMBER(*,0) DEFAULT 1, 
	SUFFIX VARCHAR2(30 CHAR),
--
    GEOM MDSYS.SDO_GEOMETRY ,
	MBR MDSYS.SDO_GEOMETRY , 
	AREA NUMBER,
	NUM_PTS NUMBER(*,0)	
);

ALTER TABLE stage_my_areas ADD AREA NUMBER;
ALTER TABLE stage_my_areas MATCHABLE NUMBER(*,0) DEFAULT 1;
ALTER TABLE stage_my_areas ADD SUFFIX VARCHAR2(20 CHAR);
UPDATE stage_my_areas set MATCHABLE = 1;
ALTER TABLE stage_my_areas ADD CONSTRAINT stage_my_areas_pk PRIMARY KEY (area_code, area_number);
ALTER TABLE stage_my_areas ADD CONSTRAINT stage_my_areas_uk UNIQUE (fre_id)
alter table stage_my_areas
add constraint stage_my_areas_rfk_area_code foreign key (parent_area_code, parent_area_number) references stage_my_areas (area_code, area_number);

INSERT INTO USER_SDO_GEOM_METADATA (
    TABLE_NAME,
    COLUMN_NAME,
    DIMINFO,
    SRID
)
VALUES (
    'STAGE_GEO_DATA',
    'GEOM',
    SDO_DIM_ARRAY(
        SDO_DIM_ELEMENT('Longitude', -180, 180, 0.005),
        SDO_DIM_ELEMENT('Latitude',  -90,  90, 0.005)
    ),
    4326
);

INSERT INTO USER_SDO_GEOM_METADATA (
    TABLE_NAME,
    COLUMN_NAME,
    DIMINFO,
    SRID
)
VALUES (
    'STAGE_MY_AREAS',
    'GEOM',
    SDO_DIM_ARRAY(
        SDO_DIM_ELEMENT('Longitude', -180, 180, 0.005),
        SDO_DIM_ELEMENT('Latitude',  -90,  90, 0.005)
    ),
    4326
);

DROP INDEX stage_geo_data_sidx
/
CREATE INDEX stage_geo_data_sidx
ON stage_geo_data(geom)
INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2
/

----------------------------------------------------------------------------------------------------
--Load GeoJSON from URL
----------------------------------------------------------------------------------------------------
clear screen
set serveroutput on timi on echo on
--TRUNCATE TABLE stage_geo_data;

DECLARE   
PROCEDURE load_geojson_url(p_id NUMBER, p_url varchar2) IS
  l_clob CLOB;
BEGIN
  DBMS_LOB.createtemporary(l_clob, TRUE);
  l_clob:=strava_http.http_request(p_url);
  --strava_http.print_clob(l_clob);
  --strava_sdo.parse_geojson(l_clob);
  INSERT INTO stage_geo_data (id, geo_json) VALUES (p_id, l_clob);

  DBMS_LOB.freetemporary(l_clob);
END load_geojson_url;
BEGIN
  load_geojson_url(1,'https://hub.huwise.com/api/explore/v2.1/catalog/datasets/georef-portugal-distrito/exports/geojson/?lang=en');
  load_geojson_url(2,'https://hub.huwise.com/api/explore/v2.1/catalog/datasets/georef-portugal-concelho/exports/geojson/?lang=en');
  load_geojson_url(3,'https://hub.huwise.com/api/explore/v2.1/catalog/datasets/georef-portugal-freguesia/exports/geojson/?lang=en');
END;
/


--staging data loaded from web
select x.*, length(x.geo_json) from stage_geo_data x;
delete from stage_geo_data where length(geo_json) < 1000;
----------------------------------------------------------------------------------------------------
-- Load staged GeoJSON into stage areas
----------------------------------------------------------------------------------------------------
clear screen
set serveroutput on echo on timi on
TRUNCATE TABLE stage_my_areas;

DECLARE   
PROCEDURE load_geojson(p_id NUMBER) IS
  k_iso         CONSTANT INTEGER := '620'; --country isco code
  l_clob        CLOB;
  j_root        JSON_OBJECT_T;
  j_crs         JSON_OBJECT_T;
  j_features    JSON_ARRAY_T;
  j_feature     JSON_OBJECT_T;
  j_properties  JSON_OBJECT_T;
  j_geometry    JSON_OBJECT_T;

  l_geom        MDSYS.SDO_GEOMETRY;
  l_mbr         MDSYS.SDO_GEOMETRY;
  l_area        stage_my_areas.area%TYPE;

  l_area_code   stage_my_areas.area_code%TYPE;
  l_area_number stage_my_areas.area_number%TYPE;
  l_area_level  stage_my_areas.area_level%TYPE;
  l_name        stage_my_areas.name%TYPE;
  --l_local_name  stage_my_areas.name%TYPE;
  l_parent_area_code   stage_my_areas.parent_area_code%TYPE;
  l_parent_area_number stage_my_areas.parent_area_number%TYPE;

  l_srid        VARCHAR2(10 char) := '4326';
  l_dis_id     stage_my_areas.dis_ID%TYPE;
  l_con_id     stage_my_areas.con_id%TYPE;
  l_fre_id     stage_my_areas.fre_id%TYPE;
  l_suffix      stage_my_areas.suffix%TYPE;
  l_num_pts     stage_my_areas.num_pts%TYPE;
  
  e_json_syntax_error  EXCEPTION;
  PRAGMA exception_init(e_json_syntax_error,-40441);
BEGIN 
  SELECT geo_json INTO l_clob FROM stage_geo_data WHERE id = p_id;
  l_clob := strava_http.clean_clob(l_clob);
  --strava_http.pretty_json(l_clob);
  j_root := JSON_OBJECT_T.parse(l_clob);

  --j_crs := j_root.get_object('crs');
  --l_clob := j_crs.to_clob;
  --strava_http.print_clob(l_clob);
	  
  j_features := j_root.get_array('features');
  --l_srid     := REGEXP_SUBSTR(j_crs.get_object('properties').get_string('name'),'[^:]+',1,2);
  FOR i IN 0 .. j_features.get_size - 1 LOOP
    j_feature := TREAT(j_features.get(i) AS JSON_OBJECT_T);
    j_properties := j_feature.get_object('properties');
	IF j_properties IS NULL THEN 
	  dbms_output.put_line('J_PROPERTIES is null');
	ELSE
      l_clob := j_properties.to_clob;

	  IF p_id = 1 THEN
--"properties":{"geo_point_2d":{"lon":-7.620450962143221,"lat":39.19006294643952},"year":"2024","dis_code":"12","dis_name":"Portalegre","dis_name_upper":"PORTALEGRE","dis_name_lower":"portalegre","dis_area_code":"PRT","dis_type":"district"}}]}
	    l_dis_id     := j_properties.get_string('dis_code');
		l_suffix      := initcap(j_properties.get_string('dis_type'));
		
		l_area_level  := 5;
		l_area_code   := 'DIS';
		l_area_number := k_iso*1e2+l_dis_id;
		l_name        := j_properties.get_string('dis_name');
		--l_local_name  := j_properties.get_string('dis_name_local');
	  ELSIF p_id = 2 THEN
--"properties":{"geo_point_2d":{"lon":-8.483019498708265,"lat":41.10961341896829},"year":"2024","dis_code":"13","dis_name":"Porto","con_code":"1304","con_name":"Gondomar","con_name_upper":"GONDOMAR","con_name_lower":"gondomar","con_area_code":"PRT","con_type":"municipality"}}]}
	    l_dis_id     := j_properties.get_string('dis_code');
	    l_con_id     := j_properties.get_string('con_code');
		l_suffix      := initcap(j_properties.get_string('con_type'));
		
		l_area_level  := 6;
		l_area_code   := 'MUNC';
		l_area_number := k_iso*1e2+l_con_id;
		l_name        := j_properties.get_string('con_name'); 
		--l_local_name  := j_properties.get_string('con_name_local');
	  ELSIF p_id = 3 THEN
--"properties":{"geo_point_2d":{"lon":-31.105852925315833,"lat":39.69992679852942},"year":"2024","dis_code":"20","dis_name":"A\u00e7ores","con_code":"4901","con_name":"Corvo","fre_code":"490101","fre_name":"Corvo","fre_name_upper":"CORVO","fre_name_lower":"corvo","fre_area_code":"PRT","fre_type":"parish","fre_name_long":"Corvo"}}]}
	    l_dis_id     := j_properties.get_string('dis_code');
	    l_con_id     := j_properties.get_string('con_code');
	    l_fre_id     := j_properties.get_string('fre_code');
		l_suffix      := initcap(j_properties.get_string('fre_type'));
		
		l_area_level  := 8;
		l_area_code   := 'CPAR';
		l_area_number := k_iso*1e5+l_fre_id;
		l_name        := j_properties.get_string('fre_name');
		--l_local_name  := j_properties.get_string('fre_name_local');

	  END IF;
	END IF;

    j_geometry := j_feature.get_object('geometry');
	IF j_geometry IS NULL THEN
	  dbms_output.put_line(l_name||': j_geometry is null');
	  l_geom := NULl;
	  l_num_pts := NULL;
      l_area := NULL;
      l_mbr := NULL;
	ELSE
	  -- Get coordinates array
      l_clob := j_geometry.to_clob;
      
      BEGIN
	    l_geom := sdo_util.from_geojson(l_clob);
	  EXCEPTION 
	    WHEN e_json_syntax_error THEN
		  dbms_output.put_line(sqlerrm||' during parse of '||l_area_number||':'||l_name||'. Switch to own function.' );
    	  l_geom := strava_sdo.build_sdo_geometry_from_geojson(j_geometry, l_srid);
	  END;

	  l_geom.SDO_SRID := TO_NUMBER(l_srid);
	  l_geom := SDO_CS.TRANSFORM(l_geom, 4326);
      l_geom := sdo_util.rectify_Geometry(SDO_CS.MAKE_2D(l_geom),0.001);	
      l_mbr := sdo_geom.sdo_mbr(l_geom);
	  l_num_pts := SDO_UTIL.GETNUMVERTICES(l_geom);
      --l_area := SDO_GEOM.SDO_AREA(l_geom, 0.001,'unit=km');
	END IF;
    
	/*dbms_output.put_line(l_area_number
          --||':'||l_srid
	      ||', '||l_dis_id --||':'||l_dis
          ||', '||l_con_id --||':'||l_MUNC
          ||', '||l_fre_id --||':'||l_CPAR
		  --||' ('||l_suffix||')'
		  --||', '||l_num_pts||' points'
          --||', '||l_area||' kmsq'
          );*/
	--dbms_output.put_line(SDO_UTIL.TO_WKTGEOMETRY(l_geom));
	
	/*
	IF l_local_name IS NULL THEN NULL;
	ELSIF l_name = l_local_name THEN 
	  l_local_name := '';
	ELSE
	  l_name := l_name||'/'||l_local_name;
	END IF;
	*/
	
  	INSERT INTO stage_my_areas
	(area_code, area_number, area_level, name
	--,parent_area_code, parent_area_number
	, dis_ID, con_ID, fre_id
	, geom, mbr, num_pts, area, suffix
	) VALUES
  	(l_area_code, l_area_number, l_area_level, l_name
	--,'CTY', TRUNC(l_area_number,-4)
	, l_dis_id, l_con_id, l_fre_id
	, l_geom, l_mbr, l_num_pts, l_area, l_suffix
	);
	
    COMMIT;
  END LOOP;
END load_geojson;
BEGIN
  load_geojson(1);
  load_geojson(2);
  load_geojson(3);
END;
/

UPDATE stage_my_areas
SET    mbr = sdo_geom.sdo_mbr(geom)
,      num_pts = SDO_UTIL.GETNUMVERTICES(geom)
,      area = sdo_geom.sdo_area(geom, unit=>'unit=sq_km')
where area IS NULL
/
----------------------------------------------------------------------------------------------------
-- set parents of Regions to Sovereignity of portugal
----------------------------------------------------------------------------------------------------
UPDATE stage_my_areas
SET    parent_area_code = 'SOVC'
,      parent_area_number = 1159321187 
WHERE  area_code = 'DIS'
And    area_number IN(62020 --Açores
                     ,62030 --Madeira
                     )
;
UPDATE stage_my_areas
SET    parent_area_code = 'GEOU'
,      parent_area_number = 1159321193 --Mainland portugal
WHERE  area_code = 'DIS'
AND    (parent_area_code IS NULL OR parent_area_code != 'SOVC')
/
----------------------------------------------------------------------------------------------------
-- set parents of MUNC
----------------------------------------------------------------------------------------------------
UPDATE stage_my_areas c
SET   (c.parent_area_code, c.parent_area_number) 
    = (select p.area_code, p.area_number
	   from   stage_my_areas p
	   where  p.dis_ID = c.dis_ID
	   AND    p.con_id IS NULL
	   AND    p.fre_id IS null)
WHERE c.dis_ID IS NOT NULL
AND   c.con_id IS NOT NULL
AND   c.fre_id IS NULL
--AND   c.parent_area_code IS NULL
--AND   c.parent_area_number IS NULL
;
----------------------------------------------------------------------------------------------------
-- set parents of CPAR
----------------------------------------------------------------------------------------------------
UPDATE stage_my_areas c
SET   (c.parent_area_code, c.parent_area_number) 
    = (select p.area_code, p.area_number
	   from   stage_my_areas p
	   where  p.dis_ID = c.dis_ID
	   AND    p.con_id = c.con_id
	   AND    p.fre_id IS NULL)
WHERE c.dis_ID IS NOT NULL
AND   c.con_id IS NOT NULL
AND   c.fre_id IS NOT NULL
--AND   c.parent_area_code IS NULL
--AND   c.parent_area_number IS NULL
;
----------------------------------------------------------------------------------------------------
-- Add a new area code for autonomous commune
----------------------------------------------------------------------------------------------------
INSERT INTO my_area_codes (area_code, description, area_level)
VALUES ('CPAR','Civil Parish',8);
----------------------------------------------------------------------------------------------------
-- summary of numbers of areas
----------------------------------------------------------------------------------------------------
select area_level, area_code, suffix, count(*) num_areas
from stage_my_areas
group by area_level, area_code, suffix
order by area_level, num_areas desc
/
----------------------------------------------------------------------------------------------------
-- disable matchable on duplicate child names
----------------------------------------------------------------------------------------------------
UPDATE stage_my_areas c
SET    c.matchable = 0
WHERE  c.matchable = 1
AND EXISTS(
  SELECT 'X'
  FROM   stage_my_areas p
  WHERE  c.parent_area_code = p.area_Code 
  AND    c.parent_area_number = p.area_number
  AND    c.name = p.name)
/
----------------------------------------------------------------------------------------------------
--check children within parents - this should be blank
----------------------------------------------------------------------------------------------------
with x as (
select p.area_code p_area_code, p.area_number p_area_number, p.name p_name, p.suffix p_suffix, p.area p_area
,      c.area_code c_area_code, c.area_number c_area_number, c.name c_name, c.suffix c_suffix, c.area c_area
,      sdo_geom.sdo_area(SDO_GEOM.sdo_intersection(p.geom,c.geom,0.001), unit=>'unit=sq_km') i_area
from stage_my_areas p
  inner join stage_my_areas c ON p.area_Code = c.parent_area_code AND p.area_number = c.parent_area_number
)
select * 
from x
where NVL(i_area/c_area,0) < .9 
/
----------------------------------------------------------------------------------------------------
@@simplify_stage_my_areas.sql
----------------------------------------------------------------------------------------------------
REM delete existing portugal data
----------------------------------------------------------------------------------------------------
DELETE FROM my_areas
WHERE area_code = 'GEOU'
AND name_hierarchy like 'Portugal,%'
AND area_number IN(1159321191, 1159321189)
;
----------------------------------------------------------------------------------------------------
REM insert new portugal date
----------------------------------------------------------------------------------------------------
ALTER TABLE my_areas MODIFY name VARCHAR2(76);
INSERT INTO my_areas
(AREA_CODE,AREA_NUMBER,AREA_LEVEL,PARENT_AREA_CODE,PARENT_AREA_NUMBER
,NAME,MATCHABLE,GEOM,MBR,SUFFIX,NUM_PTS,LAST_UPDATED)
SELECT AREA_CODE,AREA_NUMBER,AREA_LEVEL,PARENT_AREA_CODE,PARENT_AREA_NUMBER
,NAME,MATCHABLE,GEOM,MBR,SUFFIX,NUM_PTS,sysdate
FROM stage_my_areas
order by area_level
/

REM update names
MERGE INTO my_areas u
USING (
SELECT s.*
FROM stage_my_areas s
  INNER JOIN my_areas m ON m.area_code = s.area_code and m.area_number = s.area_number
WHERE s.name != m.name
) s 
ON (u.area_code = s.area_code and u.area_number = s.area_number)
WHEN MATCHED THEN UPDATE
SET u.name = s.name
/
----------------------------------------------------------------------------------------------------
--update hierarchy
----------------------------------------------------------------------------------------------------
update my_areas
set name_hierarchy = strava_sdo.name_hierarchy_fn(area_code, area_number,'C')||name 
where name_hierarchy IS null
--or name_hierarchy like 'Portugal'
/
----------------------------------------------------------------------------------------------------
--update number of children
----------------------------------------------------------------------------------------------------
merge into my_areas u
using (
select p.area_code, p.area_number, p.name, p.num_children, count(c.area_number) child_count
from my_areas p
  left outer join my_areas c
    on p.area_code = c.parent_area_code
    and p.area_number = c.parent_area_number
where 1=1
--and c.num_children IS NULL
group by p.area_code, p.area_number, p.name, p.num_children
having count(c.area_number) != NVL(p.num_children,0)
) s
ON (s.area_code = u.area_code AND s.area_number = u.area_number)
WHEN MATCHED THEN UPDATE 
SET u.num_children = s.child_count
/
----------------------------------------------------------------------------------------------------
--mark activities from recalculation
----------------------------------------------------------------------------------------------------
MERGE INTO activities u
USING (
select a.activity_id, a.name, a.start_date_utc, a.processing_status, a.last_updated activity_last_updated
, MAX(ma.last_updated) area_last_updated
from activities a
  INNER JOIN activity_areas aa ON a.activity_id = aa.activity_id
  INNER JOIN my_areas ma ON ma.area_code =aa.area_code and ma.area_number = aa.area_number
where ma.last_updated > sysdate -7
and a.last_updated < ma.last_updated
and a.processing_status > 3
and a.processing_status < 9
and ma.name_hierarchy like 'Portugal%'
group by a.activity_id, a.name, a.start_date_utc, a.processing_status, a.last_updated 
) s
ON (s.activity_id = u.activity_id)
WHEN MATCHED THEN UPDATE
SET u.processing_status = 3
/
----------------------------------------------------------------------------------------------------
--force mark portugal activities from recalculation
----------------------------------------------------------------------------------------------------
update activities
set processing_status = 3
where processing_status > 3 and processing_status < 9
and activity_id IN(
  select distinct aa.activity_id
  from activity_areas aa 
     INNER JOIN my_areas ma ON ma.area_code =aa.area_code and ma.area_number = aa.area_number
  where ma.name_hierarchy like 'Portugal%')
/

select * 
from activities
where activity_id IN(
  select distinct aa.activity_id
  from activity_areas aa 
     INNER JOIN my_areas ma ON ma.area_code =aa.area_code and ma.area_number = aa.area_number
  where ma.name_hierarchy like 'Portugal%')
order by start_date_utc desc
/


drop table stage_my_areas purge;
create table stage_my_areas
as select * from my_areas p
--where p.area_code = 'SOVC' AND p.area_number = 1159321187 and p.name = 'Portugal'
where p.area_code = 'GEOU' AND p.area_number = 1159321193 and p.name = 'Portugal'
/
select * from stage_my_areas;

update my_areas p
set p.geom = (
  SELECT SDO_AGGR_UNION(SDOAGGRTYPE(c.geom, 0.01)) sum_geom
  FROM my_areas c
  where c.parent_area_code = p.area_code AND c.parent_area_number = p.area_number)
--where p.area_code = 'SOVC' AND p.area_number = 1159321187 and p.name = 'Portugal'
where p.area_code = 'GEOU' AND p.area_number = 1159321193 and p.name = 'Portugal'
/
update my_areas p
set num_pts = SDO_UTIL.GETNUMVERTICES(p.geom)
--where p.area_code = 'SOVC' AND p.area_number = 1159321187 and p.name = 'Portugal'
where p.area_code = 'GEOU' AND p.area_number = 1159321193 and p.name = 'Portugal'
/


with p as (
  select p.area_code, p.area_number, p.name, p.geom
  from my_areas p 
  --where p.area_code = 'SOVC' AND p.area_number = 1159321187 and p.name = 'Portugal'
  where p.area_code = 'GEOU' AND p.area_number = 1159321193 and p.name = 'Portugal'
), c as (
select SDO_AGGR_UNION(SDOAGGRTYPE(c.geom, 0.01)) sum_geom
from p
  inner join my_areas c 
    on (c.parent_area_code = p.area_code AND c.parent_area_number = p.area_number)
    --or (c.area_code = p.area_code AND c.area_number = p.area_number)
)
select p.*, c.sum_geom
, sdo_geom.sdo_area(p.geom, unit=>'unit=sq_km')
, SDO_UTIL.GETNUMVERTICES(p.geom)
, sdo_geom.sdo_area(c.sum_geom, unit=>'unit=sq_km')
, SDO_UTIL.GETNUMVERTICES(c.sum_geom)
from p, c
/

SELECT area_code, area_number
, name, level, sys_connect_by_path(area_code||':'||area_number||':'||name,'/') path
, name_hierarchy
    FROM   my_areas m
    START WITH name = 'Portugal'  --and area_code = 'VMG' --and area_number = 83375005 
    CONNECT BY NOCYCLE prior m.area_code   = m.parent_area_code
                   AND prior m.area_number = m.parent_area_number
/