REM load_balearics.sql
REM https://github.com/enmiquelangel/geojsonsillesbalears/tree/master
rem PROV 72407 Illes Balears - Add level 7 GOES area for each Island - or create CNCL Council
REM eivissa
REM formentera
REM mallorca
REM menorca
REM 
REM Spain=724,ESP,ES
----------------------------------------------------------------------------------------------------
--spanish area codes: SOVC, MUNC, REG, GEOS,  USER
----------------------------------------------------------------------------------------------------
SELECT area_code, count(*), sum(matchable)
FROM   my_areas m
START WITH area_code = 'PROV' AND area_number = 72407 
CONNECT BY NOCYCLE prior m.area_code   = m.parent_area_code
               AND prior m.area_number = m.parent_area_number
group by area_code
/

----------------------------------------------------------------------------------------------------
--stage_geo_data --area staging table - one row per geometry
----------------------------------------------------------------------------------------------------
--DROP TABLE stage_geo_data PURGE;
CREATE TABLE stage_geo_data (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name        varchar2(200),
    geo_json    clob,
    geom        MDSYS.SDO_GEOMETRY,
	constraint stage_geo_date_pk primary key (id)
);

----------------------------------------------------------------------------------------------------
--tables
----------------------------------------------------------------------------------------------------
DROP TABLE stage_my_areas PURGE;
CREATE TABLE stage_my_areas (
    AREA_CODE VARCHAR2(4 CHAR) NOT NULL , 
	AREA_NUMBER NUMBER(*,0) NOT NULL , 
 	AREA_LEVEL NUMBER(*,0), 
	PARENT_AREA_CODE VARCHAR2(4 CHAR), 
	PARENT_AREA_NUMBER NUMBER(*,0), 
	NAME VARCHAR2(200 CHAR), 
	MATCHABLE NUMBER(*,0) DEFAULT 1, 
	SUFFIX VARCHAR2(30 CHAR),
--
    GEOM MDSYS.SDO_GEOMETRY ,
	MBR MDSYS.SDO_GEOMETRY , 
	AREA NUMBER,
	NUM_PTS NUMBER(*,0)	
);

ALTER TABLE stage_my_areas ADD AREA NUMBER;
ALTER TABLE stage_my_areas MATCHABLE NUMBER(*,0) DEFAULT 1;
ALTER TABLE stage_my_areas ADD SUFFIX VARCHAR2(20 CHAR);
UPDATE stage_my_areas set MATCHABLE = 1;
ALTER TABLE stage_my_areas ADD CONSTRAINT stage_my_areas_pk PRIMARY KEY (area_code, area_number);
ALTER TABLE stage_my_areas ADD CONSTRAINT stage_my_areas_uk UNIQUE (MUNC_id)
alter table stage_my_areas
add constraint stage_my_areas_rfk_area_code foreign key (parent_area_code, parent_area_number) references stage_my_areas (area_code, area_number);

INSERT INTO USER_SDO_GEOM_METADATA (
    TABLE_NAME,
    COLUMN_NAME,
    DIMINFO,
    SRID
)
VALUES (
    'STAGE_GEO_DATA',
    'GEOM',
    SDO_DIM_ARRAY(
        SDO_DIM_ELEMENT('Longitude', -180, 180, 0.005),
        SDO_DIM_ELEMENT('Latitude',  -90,  90, 0.005)
    ),
    4326
);

INSERT INTO USER_SDO_GEOM_METADATA (
    TABLE_NAME,
    COLUMN_NAME,
    DIMINFO,
    SRID
)
VALUES (
    'STAGE_MY_AREAS',
    'GEOM',
    SDO_DIM_ARRAY(
        SDO_DIM_ELEMENT('Longitude', -180, 180, 0.005),
        SDO_DIM_ELEMENT('Latitude',  -90,  90, 0.005)
    ),
    4326
);

DROP INDEX stage_geo_data_sidx
/
CREATE INDEX stage_geo_data_sidx
ON stage_geo_data(geom)
INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2
/

----------------------------------------------------------------------------------------------------
--insert MBRs
----------------------------------------------------------------------------------------------------
TRUNCATE TABLE stage_geo_data;
INSERT INTO stage_geo_data (id,geo_json)
VALUES (0,'{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {
        "island": "Mallorca"
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [[
          [2.30, 39.25],
          [3.45, 39.25],
          [3.45, 39.97],
          [2.30, 39.97],
          [2.30, 39.25]
        ]]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "island": "Menorca"
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [[
          [3.79, 39.79],
          [4.33, 39.79],
          [4.33, 40.10],
          [3.79, 40.10],
          [3.79, 39.79]
        ]]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "island": "Ibiza"
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [[
          [1.12, 38.87],
          [1.56, 38.87],
          [1.56, 39.11],
          [1.12, 39.11],
          [1.12, 38.87]
        ]]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "island": "Formentera"
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [[
          [1.39, 38.66],
          [1.58, 38.66],
          [1.58, 38.73],
          [1.39, 38.73],
          [1.39, 38.66]
        ]]
      }
    }
  ]
}');
----------------------------------------------------------------------------------------------------
--Load GeoJSON from URL
----------------------------------------------------------------------------------------------------
clear screen
set serveroutput on timi on echo on
--TRUNCATE TABLE stage_geo_data;

DECLARE   
PROCEDURE load_geojson_url(p_id NUMBER, p_url varchar2) IS
  l_clob CLOB;
BEGIN
  DBMS_LOB.createtemporary(l_clob, TRUE);
  l_clob:=strava_http.http_request(p_url);
  --strava_http.print_clob(l_clob);
  --strava_sdo.parse_geojson(l_clob);
  INSERT INTO stage_geo_data (id, geo_json) VALUES (p_id, l_clob);

  DBMS_LOB.freetemporary(l_clob);
END load_geojson_url;
BEGIN
--load_geojson_url(1,'https://raw.githubusercontent.com/enmiquelangel/geojsonsillesbalears/master/eivissa.json');
--load_geojson_url(2,'https://raw.githubusercontent.com/enmiquelangel/geojsonsillesbalears/master/formentera.json');
--load_geojson_url(3,'https://raw.githubusercontent.com/enmiquelangel/geojsonsillesbalears/master/mallorca.json');
--load_geojson_url(4,'https://raw.githubusercontent.com/enmiquelangel/geojsonsillesbalears/master/menorca.json');
END;
/


--staging data loaded from web
select x.*, length(x.geo_json) from stage_geo_data x;
delete from stage_geo_data where length(geo_json) < 1000;
----------------------------------------------------------------------------------------------------
-- Load staged GeoJSON into stage areas
----------------------------------------------------------------------------------------------------
clear screen
set serveroutput on echo on timi on
TRUNCATE TABLE stage_my_areas;

DECLARE   
PROCEDURE load_geojson(p_id NUMBER) IS
  k_iso         CONSTANT INTEGER := '724'; --country isco code
  l_clob        CLOB;
  j_root        JSON_OBJECT_T;
  j_crs         JSON_OBJECT_T;
  j_features    JSON_ARRAY_T;
  j_feature     JSON_OBJECT_T;
  j_properties  JSON_OBJECT_T;
  j_geometry    JSON_OBJECT_T;

  l_geom        MDSYS.SDO_GEOMETRY;
  l_mbr         MDSYS.SDO_GEOMETRY;
  l_area        stage_my_areas.area%TYPE;

  l_area_code   stage_my_areas.area_code%TYPE;
  l_area_number stage_my_areas.area_number%TYPE;
  l_area_level  stage_my_areas.area_level%TYPE;
  l_name        stage_my_areas.name%TYPE;
  l_parent_area_code   stage_my_areas.parent_area_code%TYPE;
  l_parent_area_number stage_my_areas.parent_area_number%TYPE;
  l_user_id     integer;

  l_srid        VARCHAR2(10 char) := '4326';
  l_suffix      stage_my_areas.suffix%TYPE;
  l_num_pts     stage_my_areas.num_pts%TYPE;
  
  e_json_syntax_error  EXCEPTION;
  PRAGMA exception_init(e_json_syntax_error,-40441);
BEGIN 
  SELECT geo_json INTO l_clob FROM stage_geo_data WHERE id = p_id;
  l_clob := strava_http.clean_clob(l_clob);
  --strava_http.pretty_json(l_clob);
  j_root := JSON_OBJECT_T.parse(l_clob);

  --j_crs := j_root.get_object('crs');
  --l_clob := j_crs.to_clob;
  --strava_http.print_clob(l_clob);
	  
  j_features := j_root.get_array('features');
  --l_srid     := REGEXP_SUBSTR(j_crs.get_object('properties').get_string('name'),'[^:]+',1,2);
  FOR i IN 0 .. j_features.get_size - 1 LOOP
    j_feature := TREAT(j_features.get(i) AS JSON_OBJECT_T);
    j_properties := j_feature.get_object('properties');
	IF j_properties IS NULL THEN 
	  dbms_output.put_line('J_PROPERTIES is null');
	ELSE
      l_clob := j_properties.to_clob;

	  IF p_id = 0 THEN
		l_name        := j_properties.get_string('island');
		IF l_name = 'Formentera' THEN l_user_id := 1;
		ELSIF l_name = 'Ibiza' THEN l_user_id := 2;
		ELSIF l_name = 'Mallorca' THEN l_user_id := 3;
		ELSIF l_name = 'Menorca' THEN l_user_id := 4;
		ELSE l_user_id := NULL;
		END IF;
		
		l_area_level  := 7;
		l_area_code   := 'USER';
		l_area_number := k_iso*1e3+l_user_id;
	  END IF;
	END IF;

    j_geometry := j_feature.get_object('geometry');
	IF j_geometry IS NULL THEN
	  dbms_output.put_line(l_name||': j_geometry is null');
	  l_geom := NULl;
	  l_num_pts := NULL;
      l_area := NULL;
      l_mbr := NULL;
	ELSE
	  -- Get coordinates array
      l_clob := j_geometry.to_clob;
      
      BEGIN
	    l_geom := sdo_util.from_geojson(l_clob);
	  EXCEPTION 
	    WHEN e_json_syntax_error THEN
		  dbms_output.put_line(sqlerrm||' during parse of '||l_area_number||':'||l_name||'. Switch to own function.' );
    	  l_geom := strava_sdo.build_sdo_geometry_from_geojson(j_geometry, l_srid);
	  END;

	  l_geom.SDO_SRID := TO_NUMBER(l_srid);
	  l_geom := SDO_CS.TRANSFORM(l_geom, 4326);
      l_geom := sdo_util.rectify_Geometry(SDO_CS.MAKE_2D(l_geom),0.001);	
      l_mbr := sdo_geom.sdo_mbr(l_geom);
	  l_num_pts := SDO_UTIL.GETNUMVERTICES(l_geom);
      --l_area := SDO_GEOM.SDO_AREA(l_geom, 0.001,'unit=km');
	END IF;
    
	/*dbms_output.put_line(l_area_number
          --||':'||l_srid
		  --||' ('||l_suffix||')'
		  --||', '||l_num_pts||' points'
          --||', '||l_area||' kmsq'
          );*/
	--dbms_output.put_line(SDO_UTIL.TO_WKTGEOMETRY(l_geom));
		
  	INSERT INTO stage_my_areas
	(area_code, area_number, area_level, name
	--,parent_area_code, parent_area_number
	, geom, mbr, num_pts, area
	) VALUES
  	(l_area_code, l_area_number, l_area_level, l_name
	--,'CTY', TRUNC(l_area_number,-4)
	, l_geom, l_mbr, l_num_pts, l_area
	);
	
    COMMIT;
  END LOOP;
END load_geojson;
BEGIN
  load_geojson(0);
END;
/

UPDATE stage_my_areas
SET    mbr = sdo_geom.sdo_mbr(geom)
,      num_pts = SDO_UTIL.GETNUMVERTICES(geom)
,      area = sdo_geom.sdo_area(geom, unit=>'unit=sq_km')
where area IS NULL
/
----------------------------------------------------------------------------------------------------
-- set parents of Regions to Sovereignity of Spain
----------------------------------------------------------------------------------------------------
UPDATE stage_my_areas
SET    parent_area_code = 'PROV'
,      parent_area_number = 72407
,      area_level = 7
/
----------------------------------------------------------------------------------------------------
-- summary of numbers of areas
----------------------------------------------------------------------------------------------------
select area_level, area_code, suffix, count(*) num_areas
from stage_my_areas
group by area_level, area_code, suffix
order by area_level, num_areas desc
/
----------------------------------------------------------------------------------------------------
REM insert new Spain date
----------------------------------------------------------------------------------------------------
INSERT INTO my_areas
(AREA_CODE,AREA_NUMBER,AREA_LEVEL,PARENT_AREA_CODE,PARENT_AREA_NUMBER
,NAME,MATCHABLE,GEOM,MBR,SUFFIX,NUM_PTS,LAST_UPDATED)
SELECT AREA_CODE,AREA_NUMBER,AREA_LEVEL,PARENT_AREA_CODE,PARENT_AREA_NUMBER
,NAME,MATCHABLE,GEOM,MBR,SUFFIX,NUM_PTS,sysdate
FROM stage_my_areas
order by area_level
/

REM update names
MERGE INTO my_areas u
USING (
SELECT s.*
FROM stage_my_areas s
  INNER JOIN my_areas m ON m.area_code = s.area_code and m.area_number = s.area_number
WHERE s.name != m.name
) s 
ON (u.area_code = s.area_code and u.area_number = s.area_number)
WHEN MATCHED THEN UPDATE
SET u.name = s.name
/
----------------------------------------------------------------------------------------------------
--reorganise hierarchy
----------------------------------------------------------------------------------------------------
merge into my_areas u
using (
select p.area_code p_area_code, p.area_number p_area_number --, p.name
,      c.area_code c_area_code, c.area_number c_area_number --, c.name
--,      sdo_geom.sdo_area(SDO_GEOM.sdo_intersection(p.geom,c.geom,0.001), unit=>'unit=sq_km') i_area
from my_areas p
,    my_areas c
where p.parent_area_code = 'PROV'
and   p.parent_area_number = 72407
and   p.area_code = 'USER'
and   c.parent_area_code = p.parent_area_code
and   c.parent_area_number = p.parent_area_number
and   c.area_code != p.area_code
and   SDO_ANYINTERACT(c.geom, p.geom) = 'TRUE'
--order by 1,2,4,5
) s on (u.area_code = s.c_area_code and u.area_number = s.c_area_number)
when matched then update
set u.parent_area_code = s.p_area_code
, u.parent_area_number = s.p_area_number
;
----------------------------------------------------------------------------------------------------
--update hierarchy
---------------------------------------------------------------------------------------------------
select name, name_hierarchy
from my_areas
where name_hierarchy like 'Spain,B%'
order by 2
/
@@update_my_areas_name_hierarchy.sql
----------------------------------------------------------------------------------------------------
--update number of children
----------------------------------------------------------------------------------------------------
merge into my_areas u
using (
select p.area_code, p.area_number, p.name, p.num_children, count(c.area_number) child_count
from my_areas p
  left outer join my_areas c
    on p.area_code = c.parent_area_code
    and p.area_number = c.parent_area_number
where 1=1
--and c.num_children IS NULL
group by p.area_code, p.area_number, p.name, p.num_children
having count(c.area_number) != NVL(p.num_children,0)
) s
ON (s.area_code = u.area_code AND s.area_number = u.area_number)
WHEN MATCHED THEN UPDATE 
SET u.num_children = s.child_count
/
----------------------------------------------------------------------------------------------------
--validation
----------------------------------------------------------------------------------------------------
select * from my_areas
where area_code = 'USER'
and area_number BETWEEN 724000 AND 724999
/
select * from my_areas
where parent_area_code = 'USER'
and parent_area_number BETWEEN 724000 AND 724999
/
select ma.*
from activity_areas aa
  inner join my_areas ma on ma.area_code = aa.area_Code and ma.area_number =aa.area_number
where aa.activity_id=2299588375
/
----------------------------------------------------------------------------------------------------
--mark activities from recalculation
----------------------------------------------------------------------------------------------------
MERGE INTO activities u
USING (
select a.activity_id, a.name, a.start_date_utc, a.processing_status, a.last_updated activity_last_updated
, MAX(ma.last_updated) area_last_updated
from activities a
  INNER JOIN activity_areas aa ON a.activity_id = aa.activity_id
  INNER JOIN my_areas ma ON ma.area_code =aa.area_code and ma.area_number = aa.area_number
where ma.last_updated > sysdate -7
and a.last_updated < ma.last_updated
and a.processing_status > 3
and a.processing_status < 9
and ma.name_hierarchy like 'Spain%'
group by a.activity_id, a.name, a.start_date_utc, a.processing_status, a.last_updated 
) s
ON (s.activity_id = u.activity_id)
WHEN MATCHED THEN UPDATE
SET u.processing_status = 3
/
----------------------------------------------------------------------------------------------------
--force mark Spain activities from recalculation
----------------------------------------------------------------------------------------------------
update activities
set processing_status = 3
where processing_status > 3 and processing_status < 9
and activity_id IN(
  select distinct aa.activity_id
  from activity_areas aa 
     INNER JOIN my_areas ma ON ma.area_code =aa.area_code and ma.area_number = aa.area_number
  where ma.name_hierarchy like 'Spain%')
/

select * 
from activities
where activity_id IN(
  select distinct aa.activity_id
  from activity_areas aa 
     INNER JOIN my_areas ma ON ma.area_code =aa.area_code and ma.area_number = aa.area_number
  where ma.name_hierarchy like 'Spain%')
order by start_date_utc desc
/
