REM load_italy2.sql
REM Regions        https://github.com/guglielmo/geojson-italy/edit/main/geojson/limits_IT_regions.geojson
REM Provinces      https://github.com/guglielmo/geojson-italy/edit/main/geojson/limits_IT_provinces.geojson
REM Cities         https://github.com/guglielmo/geojson-italy/edit/main/geojson/limits_IT_metropolitan_cities.geojson
REM Municipalities https://github.com/guglielmo/geojson-italy/edit/main/geojson/limits_IT_municipalities.geojson
REM Italy=380,ITA,IT
----------------------------------------------------------------------------------------------------
--italian area codes: SOVC, MUNC, REG, GEOS,  USER
----------------------------------------------------------------------------------------------------
SELECT DISTINCT area_code
FROM   my_areas m
START WITH area_code = 'SOVC' AND area_number = 380 and name = 'Italy'
CONNECT BY NOCYCLE prior m.area_code   = m.parent_area_code
               AND prior m.area_number = m.parent_area_number
/

----------------------------------------------------------------------------------------------------
--stage_geo_data --area staging table - one row per geometry
----------------------------------------------------------------------------------------------------
--DROP TABLE stage_geo_data PURGE;
CREATE TABLE stage_geo_data (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name        varchar2(200),
    geo_json    clob,
    geom        MDSYS.SDO_GEOMETRY,
	constraint stage_geo_date_pk primary key (id)
);

----------------------------------------------------------------------------------------------------
--tables
----------------------------------------------------------------------------------------------------
DROP TABLE stage_my_areas PURGE;
CREATE TABLE stage_my_areas (
    AREA_CODE VARCHAR2(4 CHAR) NOT NULL , 
	AREA_NUMBER NUMBER(*,0) NOT NULL , 
 	AREA_LEVEL NUMBER(*,0), 
	PARENT_AREA_CODE VARCHAR2(4 CHAR), 
	PARENT_AREA_NUMBER NUMBER(*,0), 
	NAME VARCHAR2(200 CHAR), 
	REG_ID NUMBER,
	REGION VARCHAR2(200 CHAR), 
	PROV_ID NUMBER,
	PROVINCE VARCHAR2(200 CHAR), 
	MUNC_ID NUMBER,
	MUNC VARCHAR2(200 CHAR), 
	MATCHABLE NUMBER(*,0) DEFAULT 1, 
	SUFFIX VARCHAR2(30 CHAR),
--
    GEOM MDSYS.SDO_GEOMETRY ,
	MBR MDSYS.SDO_GEOMETRY , 
	AREA NUMBER,
	NUM_PTS NUMBER(*,0)	
);

ALTER TABLE stage_my_areas ADD AREA NUMBER;
ALTER TABLE stage_my_areas MATCHABLE NUMBER(*,0) DEFAULT 1;
ALTER TABLE stage_my_areas ADD SUFFIX VARCHAR2(20 CHAR);
UPDATE stage_my_areas set MATCHABLE = 1;
ALTER TABLE stage_my_areas ADD CONSTRAINT stage_my_areas_pk PRIMARY KEY (area_code, area_number);
ALTER TABLE stage_my_areas ADD CONSTRAINT stage_my_areas_uk UNIQUE (MUNC_id)
alter table stage_my_areas
add constraint stage_my_areas_rfk_area_code foreign key (parent_area_code, parent_area_number) references stage_my_areas (area_code, area_number);

INSERT INTO USER_SDO_GEOM_METADATA (
    TABLE_NAME,
    COLUMN_NAME,
    DIMINFO,
    SRID
)
VALUES (
    'STAGE_GEO_DATA',
    'GEOM',
    SDO_DIM_ARRAY(
        SDO_DIM_ELEMENT('Longitude', -180, 180, 0.005),
        SDO_DIM_ELEMENT('Latitude',  -90,  90, 0.005)
    ),
    4326
);

INSERT INTO USER_SDO_GEOM_METADATA (
    TABLE_NAME,
    COLUMN_NAME,
    DIMINFO,
    SRID
)
VALUES (
    'STAGE_MY_AREAS',
    'GEOM',
    SDO_DIM_ARRAY(
        SDO_DIM_ELEMENT('Longitude', -180, 180, 0.005),
        SDO_DIM_ELEMENT('Latitude',  -90,  90, 0.005)
    ),
    4326
);

DROP INDEX stage_geo_data_sidx
/
CREATE INDEX stage_geo_data_sidx
ON stage_geo_data(geom)
INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2
/

----------------------------------------------------------------------------------------------------
--Load GeoJSON from URL
--https://github.com/guglielmo/geojson-italy
----------------------------------------------------------------------------------------------------
clear screen
set serveroutput on timi on echo on
--TRUNCATE TABLE stage_geo_data;

DECLARE   
PROCEDURE load_geojson_url(p_id NUMBER, p_url varchar2) IS
  l_clob CLOB;
BEGIN
  DBMS_LOB.createtemporary(l_clob, TRUE);
  l_clob:=strava_http.http_request(p_url);
  --strava_http.print_clob(l_clob);
  --strava_sdo.parse_geojson(l_clob);
  INSERT INTO stage_geo_data (id, geo_json) VALUES (p_id, l_clob);

  DBMS_LOB.freetemporary(l_clob);
END load_geojson_url;
BEGIN
  load_geojson_url(1,'https://raw.githubusercontent.com/guglielmo/geojson-italy/refs/heads/main/geojson/limits_IT_regions.geojson');
  load_geojson_url(2,'https://raw.githubusercontent.com/guglielmo/geojson-italy/refs/heads/main/geojson/limits_IT_provinces.geojson'); --load_geojson_url(3,'https://raw.githubusercontent.com/guglielmo/geojson-italy/refs/heads/main/geojson/limits_IT_metropolitan_cities.geojson');
  load_geojson_url(4,'https://raw.githubusercontent.com/guglielmo/geojson-italy/refs/heads/main/geojson/limits_IT_municipalities.geojson');
END;
/


--staging data loaded from web
select * from stage_geo_data;
delete from stage_geo_data where length(geo_json) < 1000;
----------------------------------------------------------------------------------------------------
-- Load staged GeoJSON into stage areas
----------------------------------------------------------------------------------------------------
clear screen
set serveroutput on echo on timi on
TRUNCATE TABLE stage_my_areas;

DECLARE   
PROCEDURE load_geojson(p_id NUMBER) IS
  k_iso         CONSTANT INTEGER := '380'; --country isco code
  l_clob        CLOB;
  j_root        JSON_OBJECT_T;
  j_crs         JSON_OBJECT_T;
  j_features    JSON_ARRAY_T;
  j_feature     JSON_OBJECT_T;
  j_properties  JSON_OBJECT_T;
  j_geometry    JSON_OBJECT_T;

  l_geom        MDSYS.SDO_GEOMETRY;
  l_mbr         MDSYS.SDO_GEOMETRY;
  l_area        stage_my_areas.area%TYPE;

  l_area_code   stage_my_areas.area_code%TYPE;
  l_area_number stage_my_areas.area_number%TYPE;
  l_area_level  stage_my_areas.area_level%TYPE;
  l_name        stage_my_areas.name%TYPE;
  l_parent_area_code   stage_my_areas.parent_area_code%TYPE;
  l_parent_area_number stage_my_areas.parent_area_number%TYPE;

  l_srid        VARCHAR2(10 char) := '4326';
  l_reg_id      stage_my_areas.reg_id%TYPE;
  l_region      stage_my_areas.region%TYPE;
  l_prov_id     stage_my_areas.prov_id%TYPE;
  l_prov        stage_my_areas.province%TYPE;
  l_munc_id     stage_my_areas.munc_id%TYPE;
  l_munc        stage_my_areas.MUNC%TYPE;
  l_suffix      stage_my_areas.suffix%TYPE;
  l_num_pts     stage_my_areas.num_pts%TYPE;
  
  e_json_syntax_error  EXCEPTION;
  PRAGMA exception_init(e_json_syntax_error,-40441);
BEGIN 
  SELECT geo_json INTO l_clob FROM stage_geo_data WHERE id = p_id;
  l_clob := strava_http.clean_clob(l_clob);
  --strava_http.pretty_json(l_clob);
  j_root := JSON_OBJECT_T.parse(l_clob);

  --j_crs := j_root.get_object('crs');
  --l_clob := j_crs.to_clob;
  --strava_http.print_clob(l_clob);
	  
  j_features := j_root.get_array('features');
  --l_srid     := REGEXP_SUBSTR(j_crs.get_object('properties').get_string('name'),'[^:]+',1,2);
  FOR i IN 0 .. j_features.get_size - 1 LOOP
    j_feature := TREAT(j_features.get(i) AS JSON_OBJECT_T);
    j_properties := j_feature.get_object('properties');
	IF j_properties IS NULL THEN 
	  dbms_output.put_line('J_PROPERTIES is null');
	ELSE
      l_clob := j_properties.to_clob;

	  IF p_id = 1 THEN
--"properties":{"reg_name":"Sardegna","reg_istat_code_num":20,"reg_iso_3166_2":"IT-88","reg_istat_code":"20"}}]}
	    l_reg_id      := j_properties.get_string('reg_istat_code_num');
		l_region      := j_properties.get_string('reg_name');
		l_suffix      := j_properties.get_string('prov_tipo_uts');
		
		l_area_level  := 5;
		l_area_code   := 'REG';
		l_area_number := k_iso*100+l_reg_id;
		l_name        := l_region;
	  ELSIF p_id = 2 THEN
--"properties":{"prov_name":"Sulcis Iglesiente","prov_istat_code_num":119,"prov_acr":"CI","prov_iso_3166_2":null,"prov_uts_code":"119","prov_tipo_uts":"Provincia","reg_name":"Sardegna","reg_istat_code":"20","reg_istat_code_num":20,"reg_iso_3166_2":"IT-88","prov_istat_code":"119"}}
--,"properties":{"prov_name":"Torino","prov_istat_code_num":1,"prov_acr":"TO","prov_iso_3166_2":"IT-TO","prov_uts_code":"201","prov_tipo_uts":"Città metropolitana","reg_name":"Piemonte","reg_istat_code":"01","reg_istat_code_num":1,"reg_iso_3166_2":"IT-21","prov_istat_code":"001"}},
	    l_reg_id      := j_properties.get_string('reg_istat_code_num');
		l_region      := j_properties.get_string('reg_name');
	    l_prov_id     := j_properties.get_string('prov_istat_code_num');
		l_prov        := j_properties.get_string('prov_name');
		l_suffix      := j_properties.get_string('prov_tipo_uts');
		
		l_area_level  := 6;
		l_area_code   := 'PROV';
		l_area_number := k_iso*1000+l_prov_id;
		l_name        := l_prov;
	  ELSIF p_id = 3 THEN
--properties":{"prov_name":"Cagliari","prov_istat_code_num":118,"prov_acr":"CA","prov_iso_3166_2":"IT-CA","prov_uts_code":"318","prov_tipo_uts":"Città metropolitana","reg_name":"Sardegna","reg_istat_code":"20","reg_istat_code_num":20,"reg_iso_3166_2":"IT-88","prov_istat_code":"118"}}
--"properties":{"prov_name":"Torino","prov_istat_code_num":1,"prov_acr":"TO","prov_iso_3166_2":"IT-TO","prov_uts_code":"201","prov_tipo_uts":"Città metropolitana","reg_name":"Piemonte","reg_istat_code":"01","reg_istat_code_num":1,"reg_iso_3166_2":"IT-21","prov_istat_code":"001"}},
	    l_reg_id      := j_properties.get_string('reg_istat_code_num');
		l_region      := j_properties.get_string('reg_name');
	    l_prov_id     := j_properties.get_string('prov_istat_code_num');
		--l_prov        := j_properties.get_string('prov_name');
	    --l_vwg_id      := j_properties.get_string('vwg_code');
		--l_vwg         := initcap(j_properties.get_string('vwg_name_short');
		l_suffix      := j_properties.get_string('prov_tipo_uts');
		
	    l_area_level  := 7;
		l_area_code   := 'CITY';
		--l_area_number := k_iso||l_vwg_id;
		--l_name        := l_vwg;

	  ELSIF p_id = 4 THEN
--"properties": {"name": "EPSG:4326"}}, "features": [{"type": "Feature", "properties": {"name": "Agli\u00e8", "op_id": "130", "minint_elettorale": "1010810010", "minint_finloc": "1010810010", "prov_name": "Torino", "prov_istat_code": "001", "prov_istat_code_num": 1, "prov_acr": "TO", "prov_iso_3166_2": "IT-TO", "reg_name": "Piemonte", "reg_istat_code": "01", "reg_istat_code_num": 1, "reg_iso_3166_2": "IT-21", "opdm_id": "1", "com_catasto_code": "A074", "com_istat_code": "001001", "com_istat_code_num": 1001, "prov_uts_code": "201", "prov_tipo_uts": "Citt\u00e0 metropolitana"},
--"properties": {"name": "Cortina d'Ampezzo", "op_id": "3451", "minint_elettorale": "1050100160", "minint_finloc": "2050100160", "prov_name": "Belluno", "prov_istat_code": "025", "prov_istat_code_num": 25, "prov_acr": "BL", "prov_iso_3166_2": "IT-BL", "reg_name": "Veneto", "reg_istat_code": "05", "reg_istat_code_num": 5, "reg_iso_3166_2": "IT-34", "opdm_id": "3311", "com_catasto_code": "A266", "com_istat_code": "025016", "com_istat_code_num": 25016, "prov_uts_code": "025", "prov_tipo_uts": "Provincia"}, 
	    l_reg_id      := j_properties.get_string('reg_istat_code_num');
		l_region      := j_properties.get_string('reg_name');
	    l_prov_id     := j_properties.get_string('prov_istat_code_num');
		--l_prov        := j_properties.get_string('prov_name');
	    l_munc_id     := j_properties.get_string('com_istat_code_num');
		l_munc        := j_properties.get_string('name');
		l_suffix      := j_properties.get_string('prov_tipo_uts');
		
		l_area_level  := 8;
		l_area_code   := 'MUNC';
		l_area_number := k_iso*1e6+l_munc_id;
		l_name        := l_munc;

	  END IF;
	END IF;

    j_geometry := j_feature.get_object('geometry');
	IF j_geometry IS NULL THEN
	  dbms_output.put_line(l_munc||': j_geometry is null');
	  l_geom := NULl;
	  l_num_pts := NULL;
      l_area := NULL;
      l_mbr := NULL;
	ELSE
	  -- Get coordinates array
      l_clob := j_geometry.to_clob;
      
      BEGIN
	    l_geom := sdo_util.from_geojson(l_clob);
	  EXCEPTION 
	    WHEN e_json_syntax_error THEN
		  dbms_output.put_line(sqlerrm||' during parse of '||l_area_number||':'||l_munc||'. Switch to own function.' );
    	  l_geom := strava_sdo.build_sdo_geometry_from_geojson(j_geometry, l_srid);
	  END;

	  l_geom.SDO_SRID := TO_NUMBER(l_srid);
	  l_geom := SDO_CS.TRANSFORM(l_geom, 4326);
      l_geom := sdo_util.rectify_Geometry(SDO_CS.MAKE_2D(l_geom),0.001);	
      l_mbr := sdo_geom.sdo_mbr(l_geom);
	  l_num_pts := SDO_UTIL.GETNUMVERTICES(l_geom);
      --l_area := SDO_GEOM.SDO_AREA(l_geom, 0.001,'unit=km');
	END IF;
    
	/*dbms_output.put_line(l_area_number
          --||':'||l_srid
	      ||', '||l_reg_id||':'||l_region
          ||', '||l_prov_id||':'||l_prov
          ||', '||l_munc_id||':'||l_munc
		  --||' ('||l_suffix||')'
		  --||', '||l_num_pts||' points'
          --||', '||l_area||' kmsq'
          );*/
	--dbms_output.put_line(SDO_UTIL.TO_WKTGEOMETRY(l_geom));
	
  	INSERT INTO stage_my_areas
	(area_code, area_number, area_level, name
	--,parent_area_code, parent_area_number
	, reg_id, region, PROV_ID, province, MUNC_id, MUNC
	, geom, mbr, num_pts, area, suffix
	) VALUES
  	(l_area_code, l_area_number, l_area_level, l_name
	--,'CTY', TRUNC(l_area_number,-4)
	, l_reg_id, l_region, l_prov_id, l_prov, l_munc_id, l_munc
	, l_geom, l_mbr, l_num_pts, l_area, l_suffix
	);
	
    COMMIT;
  END LOOP;
END load_geojson;
BEGIN
  load_geojson(1);
  load_geojson(2);
/*load_geojson(3); not loading metropolitean cities*/
  load_geojson(4);
END;
/

UPDATE stage_my_areas
SET    mbr = sdo_geom.sdo_mbr(geom)
,      num_pts = SDO_UTIL.GETNUMVERTICES(geom)
,      area = sdo_geom.sdo_area(geom, unit=>'unit=sq_km')
where area IS NULL
/
----------------------------------------------------------------------------------------------------
-- set parents of Regions to Sovereignity of Italy
----------------------------------------------------------------------------------------------------
UPDATE stage_my_areas
SET    parent_area_code = 'SOVC'
,      parent_area_number = 380 
WHERE  area_code = 'REG'
AND    (parent_area_code IS NULL OR parent_area_code != 'SOVC')
/
----------------------------------------------------------------------------------------------------
-- set parents of prov
----------------------------------------------------------------------------------------------------
UPDATE stage_my_areas c
SET   (c.parent_area_code, c.parent_area_number) 
    = (select p.area_code, p.area_number
	   from   stage_my_areas p
	   where  p.reg_id = c.reg_id
	   AND    p.prov_id IS NULL
	   AND    p.munc_id IS null)
WHERE c.reg_id IS NOT NULL
AND   c.prov_id IS NOT NULL
AND   c.munc_id IS NULL
--AND   c.parent_area_code IS NULL
--AND   c.parent_area_number IS NULL
;
----------------------------------------------------------------------------------------------------
-- set parents of MUNC
----------------------------------------------------------------------------------------------------
UPDATE stage_my_areas c
SET   (c.parent_area_code, c.parent_area_number) 
    = (select p.area_code, p.area_number
	   from   stage_my_areas p
	   where  p.reg_id = c.reg_id
	   AND    p.prov_id = c.prov_id
	   AND    p.munc_id IS NULL)
WHERE c.reg_id IS NOT NULL
AND   c.prov_id IS NOT NULL
AND   c.munc_id IS NOT NULL
--AND   c.parent_area_code IS NULL
--AND   c.parent_area_number IS NULL
;
----------------------------------------------------------------------------------------------------
-- summary of numbers of areas
----------------------------------------------------------------------------------------------------
select area_level, area_code, suffix, count(*) num_areas
from stage_my_areas
group by area_level, area_code, suffix
order by area_level, num_areas desc
/
----------------------------------------------------------------------------------------------------
-- disable matchable on duplicate child names
----------------------------------------------------------------------------------------------------
UPDATE stage_my_areas c
SET    c.matchable = 0
WHERE  c.matchable = 1
AND EXISTS(
  SELECT 'X'
  FROM   stage_my_areas p
  WHERE  c.parent_area_code = p.area_Code 
  AND    c.parent_area_number = p.area_number
  AND    c.name = p.name)
/
----------------------------------------------------------------------------------------------------
--check children within parents - this should be blank
----------------------------------------------------------------------------------------------------
with x as (
select p.area_code p_area_code, p.area_number p_area_number, p.name p_name, p.suffix p_suffix, p.area p_area
,      c.area_code c_area_code, c.area_number c_area_number, c.name c_name, c.suffix c_suffix, c.area c_area
,      sdo_geom.sdo_area(SDO_GEOM.sdo_intersection(p.geom,c.geom,0.001), unit=>'unit=sq_km') i_area
from stage_my_areas p
  inner join stage_my_areas c ON p.area_Code = c.parent_area_code AND p.area_number = c.parent_area_number
)
select * 
from x
where NVL(i_area/c_area,0) < .9 
/
----------------------------------------------------------------------------------------------------
REM delete existing Italy data
----------------------------------------------------------------------------------------------------
DELETE FROM my_areas
WHERE (area_code,area_number) IN (
    SELECT area_code, area_number --, name, level, sys_connect_by_path(area_code||':'||area_number||':'||name,'/') path
    FROM   my_areas m
    START WITH area_code = 'SOVC' AND area_number = 380 and name = 'Italy'
    CONNECT BY NOCYCLE prior m.area_code   = m.parent_area_code
                   AND prior m.area_number = m.parent_area_number
    --order by level
    )
AND area_code != 'SOVC'
/
----------------------------------------------------------------------------------------------------
REM insert new Italy date
----------------------------------------------------------------------------------------------------
INSERT INTO my_areas
(AREA_CODE,AREA_NUMBER,AREA_LEVEL,PARENT_AREA_CODE,PARENT_AREA_NUMBER
,NAME,MATCHABLE,GEOM,MBR,SUFFIX,NUM_PTS,LAST_UPDATED)
SELECT AREA_CODE,AREA_NUMBER,AREA_LEVEL,PARENT_AREA_CODE,PARENT_AREA_NUMBER
,NAME,MATCHABLE,GEOM,MBR,SUFFIX,NUM_PTS,sysdate
FROM stage_my_areas
order by area_level
/

REM update names
MERGE INTO my_areas u
USING (
SELECT s.*
FROM stage_my_areas s
  INNER JOIN my_areas m ON m.area_code = s.area_code and m.area_number = s.area_number
WHERE s.name != m.name
) s 
ON (u.area_code = s.area_code and u.area_number = s.area_number)
WHEN MATCHED THEN UPDATE
SET u.name = s.name
/
----------------------------------------------------------------------------------------------------
--update hierarchy
----------------------------------------------------------------------------------------------------
update my_areas
set name_hierarchy = strava_sdo.name_hierarchy_fn(area_code, area_number,'C')||name 
where name_hierarchy IS null
--or name_hierarchy like 'Ireland'
/
----------------------------------------------------------------------------------------------------
--update number of children
----------------------------------------------------------------------------------------------------
merge into my_areas u
using (
select p.area_code, p.area_number, p.name, p.num_children, count(c.area_number) child_count
from my_areas p
  left outer join my_areas c
    on p.area_code = c.parent_area_code
    and p.area_number = c.parent_area_number
where 1=1
--and c.num_children IS NULL
group by p.area_code, p.area_number, p.name, p.num_children
having count(c.area_number) != NVL(p.num_children,0)
) s
ON (s.area_code = u.area_code AND s.area_number = u.area_number)
WHEN MATCHED THEN UPDATE 
SET u.num_children = s.child_count
/
----------------------------------------------------------------------------------------------------
--mark activities from recalculation
----------------------------------------------------------------------------------------------------
MERGE INTO activities u
USING (
select a.activity_id, a.name, a.start_date_utc, a.processing_status, a.last_updated activity_last_updated
, MAX(ma.last_updated) area_last_updated
from activities a
  INNER JOIN activity_areas aa ON a.activity_id = aa.activity_id
  INNER JOIN my_areas ma ON ma.area_code =aa.area_code and ma.area_number = aa.area_number
where ma.last_updated > sysdate -7
and a.last_updated < ma.last_updated
and a.processing_status > 3
and a.processing_status < 9
and ma.name_hierarchy like 'Italy%'
group by a.activity_id, a.name, a.start_date_utc, a.processing_status, a.last_updated 
) s
ON (s.activity_id = u.activity_id)
WHEN MATCHED THEN UPDATE
SET u.processing_status = 3
/
----------------------------------------------------------------------------------------------------
--force mark Italy activities from recalculation
----------------------------------------------------------------------------------------------------
update activities
set processing_status = 3
where processing_status > 3 and processing_status < 9
and activity_id IN(
  select distinct aa.activity_id
  from activity_areas aa 
     INNER JOIN my_areas ma ON ma.area_code =aa.area_code and ma.area_number = aa.area_number
  where ma.name_hierarchy like 'Italy%')
/

select * 
from activities
where activity_id IN(
  select distinct aa.activity_id
  from activity_areas aa 
     INNER JOIN my_areas ma ON ma.area_code =aa.area_code and ma.area_number = aa.area_number
  where ma.name_hierarchy like 'Italy%')
order by start_date_utc desc
/


drop table stage_my_areas purge;
create table stage_my_areas
as select * from my_areas p
where p.area_code = 'SOVC' AND p.area_number = 380 and p.name = 'Italy'
/
select * from stage_my_areas;

update my_areas p
set p.geom = (
  SELECT SDO_AGGR_UNION(SDOAGGRTYPE(c.geom, 0.01)) sum_geom
  FROM my_areas c
  where c.parent_area_code = p.area_code AND c.parent_area_number = p.area_number)
where p.area_code = 'SOVC' AND p.area_number = 380 and p.name = 'Italy'
/
update my_areas p
set num_pts = SDO_UTIL.GETNUMVERTICES(p.geom)
where p.area_code = 'SOVC' AND p.area_number = 380 and p.name = 'Italy'
/


with p as (
  select p.area_code, p.area_number, p.name, p.geom
  from my_areas p 
  where p.area_code = 'SOVC' AND p.area_number = 380 and p.name = 'Italy'
), c as (
select SDO_AGGR_UNION(SDOAGGRTYPE(c.geom, 0.01)) sum_geom
from p
  inner join my_areas c 
    on (c.parent_area_code = p.area_code AND c.parent_area_number = p.area_number)
    --or (c.area_code = p.area_code AND c.area_number = p.area_number)
)
select p.*, c.sum_geom
, sdo_geom.sdo_area(p.geom, unit=>'unit=sq_km')
, SDO_UTIL.GETNUMVERTICES(p.geom)
, sdo_geom.sdo_area(c.sum_geom, unit=>'unit=sq_km')
, SDO_UTIL.GETNUMVERTICES(c.sum_geom)
from p, c
/

SELECT area_code, area_number
, name, level, sys_connect_by_path(area_code||':'||area_number||':'||name,'/') path
, name_hierarchy
    FROM   my_areas m
    START WITH name = 'Bad Säckingen'  --and area_code = 'VMG' --and area_number = 83375005 
    CONNECT BY NOCYCLE prior m.area_code   = m.parent_area_code
                   AND prior m.area_number = m.parent_area_number
/