REM load_austria.sql
REM Austria ISO 040
----------------------------------------------------------------------------------------------------
REM https://github.com/ginseng666/GeoJSON-TopoJSON-Austria/tree/master
REM Lander       https://github.com/ginseng666/GeoJSON-TopoJSON-Austria/blob/master/2021/simplified-99.9/laender_999_geo.json
REM Bezirke      https://github.com/ginseng666/GeoJSON-TopoJSON-Austria/blob/master/2021/simplified-99.9/bezirke_999_geo.json
REN Gemeinde     https://github.com/ginseng666/GeoJSON-TopoJSON-Austria/blob/master/2021/simplified-99.9/gemeinden_999_geo.json
REM Siedlung/Seinheiten https://github.com/ginseng666/GeoJSON-TopoJSON-Austria/blob/master/2021/siedlungseinheiten/siedlungseinheiten_75_geo.json
-------------------------------------------------------------
--area codes
----------------------------------------------------------------------------------------------------
delete from my_area_codes where area_code IN('SDLG');
INSERT INTO my_area_codes VALUES ('SDLG','Siedlung/Seinheiten',7);
COMMIT;

select * from my_area_codes order by area_level
/

select area_code from stage_my_areas
minus 
select area_code from my_area_codes 
/
----------------------------------------------------------------------------------------------------
--stage_geo_data --area staging table - one row per geometry
----------------------------------------------------------------------------------------------------
--DROP TABLE stage_geo_data PURGE;
CREATE TABLE stage_geo_data (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name        varchar2(200),
    geo_json    clob,
    geom        MDSYS.SDO_GEOMETRY,
	constraint stage_geo_date_pk primary key (id)
);

----------------------------------------------------------------------------------------------------
--tables
----------------------------------------------------------------------------------------------------
DROP TABLE stage_my_areas PURGE;
CREATE TABLE stage_my_areas (
    AREA_CODE VARCHAR2(4 CHAR) NOT NULL , 
	AREA_NUMBER NUMBER(*,0) NOT NULL , 
 	AREA_LEVEL NUMBER(*,0), 
	PARENT_AREA_CODE VARCHAR2(4 CHAR), 
	PARENT_AREA_NUMBER NUMBER(*,0), 
	NAME VARCHAR2(200 CHAR), 
	MATCHABLE NUMBER(*,0) DEFAULT 1, 
	SUFFIX VARCHAR2(30 CHAR),
--
    GEOM MDSYS.SDO_GEOMETRY ,
	MBR MDSYS.SDO_GEOMETRY , 
	AREA NUMBER,
	NUM_PTS NUMBER(*,0)	
);

ALTER TABLE stage_my_areas ADD AREA NUMBER;
ALTER TABLE stage_my_areas MATCHABLE NUMBER(*,0) DEFAULT 1;
ALTER TABLE stage_my_areas ADD SUFFIX VARCHAR2(20 CHAR);
UPDATE stage_my_areas set MATCHABLE = 1;
ALTER TABLE stage_my_areas ADD CONSTRAINT stage_my_areas_pk PRIMARY KEY (area_code, area_number);
ALTER TABLE stage_my_areas ADD CONSTRAINT stage_my_areas_uk UNIQUE (gemeinde_id)
alter table stage_my_areas
add constraint stage_my_areas_rfk_area_code foreign key (parent_area_code, parent_area_number) references stage_my_areas (area_code, area_number);

INSERT INTO USER_SDO_GEOM_METADATA (
    TABLE_NAME,
    COLUMN_NAME,
    DIMINFO,
    SRID
)
VALUES (
    'STAGE_GEO_DATA',
    'GEOM',
    SDO_DIM_ARRAY(
        SDO_DIM_ELEMENT('Longitude', -180, 180, 0.005),
        SDO_DIM_ELEMENT('Latitude',  -90,  90, 0.005)
    ),
    4326
);

INSERT INTO USER_SDO_GEOM_METADATA (
    TABLE_NAME,
    COLUMN_NAME,
    DIMINFO,
    SRID
)
VALUES (
    'STAGE_MY_AREAS',
    'GEOM',
    SDO_DIM_ARRAY(
        SDO_DIM_ELEMENT('Longitude', -180, 180, 0.005),
        SDO_DIM_ELEMENT('Latitude',  -90,  90, 0.005)
    ),
    4326
);

DROP INDEX stage_geo_data_sidx
/
CREATE INDEX stage_geo_data_sidx
ON stage_geo_data(geom)
INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2
/

----------------------------------------------------------------------------------------------------
--Load GeoJSON from URL
--https://hub.huwise.com/explore/assets/georef-germany-gemeinde/
----------------------------------------------------------------------------------------------------
clear screen
set serveroutput on timi on echo on
--TRUNCATE TABLE stage_geo_data;

DECLARE   
PROCEDURE load_geojson_url(p_id NUMBER, p_url varchar2) IS
  l_clob CLOB;
BEGIN
  DBMS_LOB.createtemporary(l_clob, TRUE);
  l_clob:=strava_http.http_request(p_url);
  --strava_http.print_clob(l_clob);
  --strava_sdo.parse_geojson(l_clob);
  INSERT INTO stage_geo_data (id, geo_json) VALUES (p_id, l_clob);

  DBMS_LOB.freetemporary(l_clob);
END load_geojson_url;
BEGIN
  load_geojson_url(1,'https://raw.githubusercontent.com/ginseng666/GeoJSON-TopoJSON-Austria/refs/heads/master/2021/simplified-99.9/laender_999_geo.json');
  load_geojson_url(2,'https://github.com/ginseng666/GeoJSON-TopoJSON-Austria/refs/heads/master/2021/simplified-99.9/bezirke_999_geo.json');
  load_geojson_url(3,'https://github.com/ginseng666/GeoJSON-TopoJSON-Austria/refs/heads/master/2021/simplified-99.9/gemeinden_999_geo.json');
  load_geojson_url(4,'https://github.com/ginseng666/GeoJSON-TopoJSON-Austria/refs/heads/master/2021/siedlungseinheiten/siedlungseinheiten_75_geo.json');
END;
/

--staging data loaded from web
select * from stage_geo_data;
delete from stage_geo_data where length(geo_json) < 1000;
----------------------------------------------------------------------------------------------------
-- Load staged GeoJSON into stage areas
----------------------------------------------------------------------------------------------------
clear screen
set serveroutput on echo on timi on
TRUNCATE TABLE stage_my_areas;

DECLARE   
PROCEDURE load_geojson(p_id NUMBER) IS
  l_clob        CLOB;
  j_root        JSON_OBJECT_T;
  j_crs         JSON_OBJECT_T;
  j_features    JSON_ARRAY_T;
  j_feature     JSON_OBJECT_T;
  j_properties  JSON_OBJECT_T;
  j_geometry    JSON_OBJECT_T;

  l_geom        MDSYS.SDO_GEOMETRY;
  l_mbr         MDSYS.SDO_GEOMETRY;
  l_area        stage_my_areas.area%TYPE;

  l_area_code   stage_my_areas.area_code%TYPE;
  l_area_number stage_my_areas.area_number%TYPE;
  l_area_level  stage_my_areas.area_level%TYPE;
  l_name        stage_my_areas.name%TYPE;
  l_parent_area_code   stage_my_areas.parent_area_code%TYPE;
  l_parent_area_number stage_my_areas.parent_area_number%TYPE;

  l_srid        VARCHAR2(10 char) := '4326';
  l_suffix      stage_my_areas.suffix%TYPE;
  l_num_pts     stage_my_areas.num_pts%TYPE;
  
  e_json_syntax_error  EXCEPTION;
  PRAGMA exception_init(e_json_syntax_error,-40441);
BEGIN 
  SELECT geo_json INTO l_clob FROM stage_geo_data WHERE id = p_id;
  --l_clob := strava_http.clean_clob(l_clob);
  --strava_http.pretty_json(l_clob);
  j_root := JSON_OBJECT_T.parse(l_clob);

  j_crs := j_root.get_object('crs');
  --l_clob := j_crs.to_clob;
  --strava_http.print_clob(l_clob);
	  
  j_features := j_root.get_array('features');
  --l_srid     := REGEXP_SUBSTR(j_crs.get_object('properties').get_string('name'),'[^:]+',1,2);
  
  FOR i IN 0 .. j_features.get_size - 1 LOOP
    j_feature := TREAT(j_features.get(i) AS JSON_OBJECT_T);
    j_properties := j_feature.get_object('properties');

	IF j_properties IS NULL THEN 
	  dbms_output.put_line('J_PROPERTIES is null');
	ELSE
      --l_clob := j_properties.to_clob;
	  --strava_http.print_clob(l_clob);
	  l_area_number   := '040'||j_properties.get_string('iso');
      l_name          := initcap(j_properties.get_string('name'));
      --dbms_output.put_line(l_area_number||', '||l_srid||', '||l_name);

	  IF p_id = 1 THEN
		l_area_level  := 5;
		l_area_code   := 'LAND';
	  ELSIF p_id = 2 THEN
		l_area_level  := 6;
		l_area_code   := 'DIS';
	  ELSIF p_id = 3 THEN
	    l_area_level  := 7;
		l_area_code   := 'GMND';
	  ELSIF p_id = 4 THEN
		l_area_level  := 6;
		l_area_code   := 'SDLG';
	  END IF;
	END IF;

    j_geometry := j_feature.get_object('geometry');
	IF j_geometry IS NULL THEN
	  dbms_output.put_line(l_name||': j_geometry is null');
	  l_geom := NULL;
	ELSE
	  -- Get coordinates array
      l_clob := j_geometry.to_clob;      
      BEGIN
	    l_geom := sdo_util.from_geojson(l_clob);
	  EXCEPTION 
	    WHEN e_json_syntax_error THEN
		  dbms_output.put_line(sqlerrm||' during parse of '||l_name||' ('||l_area_code||'.'||l_area_number||'). Switch to own function.' );
    	  l_geom := strava_sdo.build_sdo_geometry_from_geojson(j_geometry, l_srid);
	  END;

	  l_geom.SDO_SRID := TO_NUMBER(l_srid);
	  l_geom := SDO_CS.TRANSFORM(l_geom, 4326);
      l_geom := sdo_util.rectify_Geometry(SDO_CS.MAKE_2D(l_geom),0.001);	
      l_mbr := sdo_geom.sdo_mbr(l_geom);
	  l_num_pts := SDO_UTIL.GETNUMVERTICES(l_geom);
      --l_area := SDO_GEOM.SDO_AREA(l_geom, 0.001,'unit=km');
	END IF;
    
	/*dbms_output.put_line(l_area_number
          --||':'||l_srid
	      ||', '||l_area_code||'.'||l_area_number
		  --||' ('||l_suffix||')'
		  --||', '||l_num_pts||' points'
          --||', '||l_area||' kmsq'
          );*/
	--dbms_output.put_line(SDO_UTIL.TO_WKTGEOMETRY(l_geom));
	
  	INSERT INTO stage_my_areas
	(area_code, area_number, area_level, name
	--,parent_area_code, parent_area_number
	, geom, mbr, num_pts, area, suffix
	) VALUES
  	(l_area_code, l_area_number, l_area_level, l_name
	--,'CTY', TRUNC(l_area_number,-4)
	, l_geom, l_mbr, l_num_pts, l_area, l_suffix
	);
	
    COMMIT;
  END LOOP;
END load_geojson;
BEGIN
  load_geojson(1);
  load_geojson(2);
  load_geojson(3);
  load_geojson(4);
END;
/

UPDATE stage_my_areas
SET    mbr = sdo_geom.sdo_mbr(geom)
,      num_pts = SDO_UTIL.GETNUMVERTICES(geom)
,      area = sdo_geom.sdo_area(geom, unit=>'unit=sq_km')
where area IS NULL
/
select * from stage_my_areas
order by area_level, area_number
;
----------------------------------------------------------------------------------------------------
-- remove (Stadt) from DIS
----------------------------------------------------------------------------------------------------
UPDATE stage_my_areas
SET name = rtrim(replace(name,'(Stadt)'))
WHERE name like '%(Stadt)'
AND area_code = 'DIS'
/
UPDATE stage_my_areas
SET name = ltrim(replace(name,'Stadt '))
WHERE name like 'Stadt %'
AND area_code = 'DIS'
/
UPDATE stage_my_areas
SET name = rtrim(replace(name,' Stadt'))
WHERE name like '% Stadt'
AND area_code = 'DIS'
/
UPDATE stage_my_areas
SET name = rtrim(replace(name,'-Stadt'))
WHERE name like '%-Stadt'
AND area_code = 'DIS'
/
----------------------------------------------------------------------------------------------------
--might have 2 stadts left, Wien-Innere Stadt and Stadtschlaining
----------------------------------------------------------------------------------------------------
select area_code, area_number, area_level, name, area
from stage_my_areas
where name like '%Stadt%'
order by 2
/
----------------------------------------------------------------------------------------------------
-- deduplicate DIS -v- SDLG
----------------------------------------------------------------------------------------------------
DELETE FROM stage_my_areas b
WHERE b.area_code = 'SDLG'
AND EXISTS (
  SELECT 'x'
  FROM   stage_my_areas a
  where a.area_number = b.area_number
  and a.name = b.name
  and a.area_code = 'DIS')
/

SELECT a.area_code, b.area_code, a.area_number, a.name, a.area, b.area
,      sdo_geom.sdo_area(SDO_GEOM.sdo_intersection(a.geom,b.geom,0.001), unit=>'unit=sq_km') i_area
FROM stage_my_areas a, stage_my_areas b
where a.area_number = b.area_number
and a.name = b.name
and a.area_code = 'DIS'
and b.area_code = 'SDLG'
/
----------------------------------------------------------------------------------------------------
-- set parents for DIS, GMND and SDLG using  FLOOR(area_code/100)
----------------------------------------------------------------------------------------------------
UPDATE stage_my_areas
SET    parent_area_code = 'SOVC'
,      parent_area_number = 1159320379 
WHERE  area_code = 'LAND'
AND    (parent_area_code IS NULL OR parent_area_code != 'SOVC')
/
UPDATE stagE_my_areas
set parent_area_code = CASE WHEN area_number between 40000 and 50000 THEN 'LAND'
                            WHEN area_number between 4000000 and 5000000 THEN 'DIS'
                       END 
,   parent_area_number = FLOOR(area_number/100)
where area_number >= 40000
/
----------------------------------------------------------------------------------------------------
-- summary of numbers of areas
----------------------------------------------------------------------------------------------------
select area_level, area_code, parent_area_code
, count(*) num_areas
from stage_my_areas
group by area_code, parent_area_code, area_level
order by 1
/
----------------------------------------------------------------------------------------------------
-- disable matchable on duplicate child names
----------------------------------------------------------------------------------------------------
UPDATE stage_my_areas c
SET    c.matchable = 0
WHERE  c.matchable = 1
AND EXISTS(
  SELECT 'X'
  FROM   stage_my_areas p
  WHERE  c.parent_area_code = p.area_Code 
  AND    c.parent_area_number = p.area_number
  AND    c.name = p.name)
/
----------------------------------------------------------------------------------------------------
--check children within parents - this should be blank
----------------------------------------------------------------------------------------------------
with x as (
select p.area_code p_area_code, p.area_number p_area_number, p.name p_name, p.area p_area
,      c.area_code c_area_code, c.area_number c_area_number, c.name c_name, c.area c_area
,      sdo_geom.sdo_area(SDO_GEOM.sdo_intersection(p.geom,c.geom,0.001), unit=>'unit=sq_km') i_area
from stage_my_areas p
  inner join stage_my_areas c ON p.area_Code = c.parent_area_code AND p.area_number = c.parent_area_number
)
select x.*, round(100*i_area/c_area,3) pct
from x
where NVL(i_area/c_area,0) < .95
/
----------------------------------------------------------------------------------------------------
REM delete existing austria data
----------------------------------------------------------------------------------------------------
DELETE FROM my_areas
WHERE area_code != 'SOVC'
AND (area_code,area_number) IN (
    SELECT area_code, area_number
	--, name, level, sys_connect_by_path(area_code||':'||area_number||':'||name,'/') path
    FROM   my_areas m
    START WITH area_code = 'SOVC' AND area_number = 1159320379 and name = 'Austria'
    CONNECT BY NOCYCLE prior m.area_code   = m.parent_area_code
                   AND prior m.area_number = m.parent_area_number
    )
/
----------------------------------------------------------------------------------------------------
REM insert new austria date
----------------------------------------------------------------------------------------------------
INSERT INTO my_areas
(AREA_CODE,AREA_NUMBER,AREA_LEVEL,PARENT_AREA_CODE,PARENT_AREA_NUMBER
,NAME,MATCHABLE,GEOM,MBR,SUFFIX,NUM_PTS,LAST_UPDATED)
SELECT AREA_CODE,AREA_NUMBER,AREA_LEVEL,PARENT_AREA_CODE,PARENT_AREA_NUMBER
,NAME,MATCHABLE,GEOM,MBR,SUFFIX,NUM_PTS,sysdate
FROM stage_my_areas
order by area_level
/

REM update names
MERGE INTO my_areas u
USING (
SELECT s.*
FROM stage_my_areas s
  INNER JOIN my_areas m ON m.area_code = s.area_code and m.area_number = s.area_number
WHERE s.name != m.name
) s 
ON (u.area_code = s.area_code and u.area_number = s.area_number)
WHEN MATCHED THEN UPDATE
SET u.name = s.name
/

----------------------------------------------------------------------------------------------------
-- disable matchable on duplicate child names
----------------------------------------------------------------------------------------------------
UPDATE my_areas c
SET    c.matchable = 0
WHERE  c.matchable = 1
AND EXISTS(
  SELECT 'X'
  FROM   my_areas p
  WHERE  c.parent_area_code = p.area_Code 
  AND    c.parent_area_number = p.area_number
  AND    c.name = p.name)
/

----------------------------------------------------------------------------------------------------
-- set matchability
----------------------------------------------------------------------------------------------------
UPDATE stage_my_areas c
SET    c.matchable = 0
WHERE  c.matchable = 1
AND EXISTS(
  SELECT 'X'
  FROM   stage_my_areas p
  WHERE  c.parent_area_code = p.area_Code 
  AND    c.parent_area_number = p.area_number
  AND    c.name = p.name)
/
----------------------------------------------------------------------------------------------------
--update number of children
----------------------------------------------------------------------------------------------------
merge into my_areas u
using (
select p.area_code, p.area_number, p.name, p.num_children, count(c.area_number) child_count
from my_areas p
  left outer join my_areas c
    on p.area_code = c.parent_area_code
    and p.area_number = c.parent_area_number
where 1=1
--and c.num_children IS NULL
group by p.area_code, p.area_number, p.name, p.num_children
having count(c.area_number) != NVL(p.num_children,0)
) s
ON (s.area_code = u.area_code AND s.area_number = u.area_number)
WHEN MATCHED THEN UPDATE 
SET u.num_children = s.child_count
/
----------------------------------------------------------------------------------------------------
--mark activities from recalculation
----------------------------------------------------------------------------------------------------
MERGE INTO activities u
USING (
select a.activity_id, a.name, a.start_date_utc, a.processing_status, a.last_updated activity_last_updated
, MAX(ma.last_updated) area_last_updated
from activities a
  INNER JOIN activity_areas aa ON a.activity_id = aa.activity_id
  INNER JOIN my_areas ma ON ma.area_code =aa.area_code and ma.area_number = aa.area_number
where ma.last_updated > sysdate -7
and a.last_updated < ma.last_updated
and a.processing_status > 3
and a.processing_status < 9
and ma.name_hierarchy like 'Austra%'
group by a.activity_id, a.name, a.start_date_utc, a.processing_status, a.last_updated 
) s
ON (s.activity_id = u.activity_id)
WHEN MATCHED THEN UPDATE
SET u.processing_status = 3
/
----------------------------------------------------------------------------------------------------
--force mark austria activities from recalculation
----------------------------------------------------------------------------------------------------
update activities
set processing_status = 3
where processing_status > 3 and processing_status < 9
and activity_id IN(
  select distinct aa.activity_id
  from activity_areas aa 
     INNER JOIN my_areas ma ON ma.area_code =aa.area_code and ma.area_number = aa.area_number
  where ma.name_hierarchy like 'Austria%')
/

----------------------------------------------------------------------------------------------------
-- Austria activities
----------------------------------------------------------------------------------------------------
select activity_id, start_date_utc, name, type, area_list, processing_from activities
where activity_id IN(
  select distinct aa.activity_id
  from activity_areas aa 
     INNER JOIN my_areas ma ON ma.area_code =aa.area_code and ma.area_number = aa.area_number
  where ma.name_hierarchy like 'Austria%')
order by start_date_utc desc
/

----------------------------------------------------------------------------------------------------
-- Austria area hierarchy
----------------------------------------------------------------------------------------------------
SELECT area_code, area_number, name, level
, sys_connect_by_path(area_code||':'||area_number||':'||name||' ('||NVL(num_children,0)||')','/') path
FROM   my_areas m
WHERE matchable = 1
START WITH area_code = 'SOVC' AND area_number = 1159320379 and name = 'Austria'
CONNECT BY NOCYCLE prior m.area_code   = m.parent_area_code
               AND prior m.area_number = m.parent_area_number
/

SELECT area_code, area_number, name, level
, sys_connect_by_path(area_code||':'||area_number||':'||name||' ('||NVL(num_children,0)||')','/') path
FROM   my_areas m
WHERE matchable = 1
START WITH name = 'Austria' AND area_code = 'SOVC' AND area_number = 1159320379 
CONNECT BY NOCYCLE prior m.area_code   = m.parent_area_code
               AND prior m.area_number = m.parent_area_number
/