REM northernireland_load_aonb.sql
REM OSNI Open Data - Largescale Boundaries - County Boundaries
REM OSNI AONB https://admin.opendatani.gov.uk/dataset/areas-of-outstanding-natural-beauty
set serveroutput on echo on

----------------------------------------------------------------------------------------------------
-- create staging table
----------------------------------------------------------------------------------------------------
--DROP TABLE stage_geo_data PURGE;
CREATE TABLE strava.stage_geo_data (
   id          NUMBER GENERATED BY DEFAULT AS IDENTITY,
   name        varchar2(200),
   geo_json    clob
--,geom        MDSYS.SDO_GEOMETRY
);

----------------------------------------------------------------------------------------------------
--area staging table - one row per geometry
----------------------------------------------------------------------------------------------------
DROP TABLE stage_my_areas;
CREATE TABLE stage_my_areas (
    AREA_CODE VARCHAR2(4 CHAR) NOT NULL , 
	area_number NUMBER(*,0) NOT NULL , 
	UQID VARCHAR2(20 CHAR) NOT NULL , 
 	AREA_LEVEL NUMBER(*,0), 
	PARENT_AREA_CODE VARCHAR2(4 CHAR), 
	PARENT_area_number NUMBER(*,0), 
	PARENT_UQID VARCHAR2(20 CHAR), 
	NAME VARCHAR2(60 CHAR),
    COUNTY VARCHAR2(60 CHAR),	
	MATCHABLE NUMBER(*,0) DEFAULT 1, 
--
    GEOM MDSYS.SDO_GEOMETRY ,
	MBR MDSYS.SDO_GEOMETRY , 
	AREA NUMBER,
	NUM_PTS NUMBER(*,0)	
);

ALTER TABLE stage_my_areas ADD CONSTRAINT stage_my_areas_pk PRIMARY KEY (area_code, area_number);
ALTER TABLE stage_my_areas ADD CONSTRAINT stage_my_areas_pk2 UNIQUE (uqid);

INSERT INTO USER_SDO_GEOM_METADATA (
    TABLE_NAME,
    COLUMN_NAME,
    DIMINFO,
    SRID
)
VALUES (
    'STAGE_GEO_DATA',
    'GEOM',
    SDO_DIM_ARRAY(
        SDO_DIM_ELEMENT('Longitude', -180, 180, 0.005),
        SDO_DIM_ELEMENT('Latitude',  -90,  90, 0.005)
    ),
    4326
);

INSERT INTO USER_SDO_GEOM_METADATA (
    TABLE_NAME,
    COLUMN_NAME,
    DIMINFO,
    SRID
)
VALUES (
    'STAGE_MY_AREAS',
    'GEOM',
    SDO_DIM_ARRAY(
        SDO_DIM_ELEMENT('Longitude', -180, 180, 0.005),
        SDO_DIM_ELEMENT('Latitude',  -90,  90, 0.005)
    ),
    4326
);

DROP INDEX stage_geo_data_sidx
/
DROP INDEX stage_my_areas_sidx
/
CREATE INDEX stage_my_areas_sidx
ON stage_my_areas(geom)
INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2
/

----------------------------------------------------------------------------------------------------
--load json FROM https://admin.opendatani.gov.uk redirects to *.cloudflarestorage.com
--NI: GEOU:1159320745
----------------------------------------------------------------------------------------------------
clear screen
set serveroutput on timi on echo on
TRUNCATE TABLE strava.stage_geo_data;
DECLARE 
  l_url VARCHAR2(1000) :=
'https://admin.opendatani.gov.uk/dataset/f803cb72-e3d2-44df-8a0c-19a496bd7a5d/resource/00347e51-c3ca-46c0-a638-0b15b085060a/download/aonb-updated-27aug2020.geojson';
  l_clob CLOB;
BEGIN
  DBMS_LOB.createtemporary(l_clob, TRUE);
  l_clob:=strava_http.http_request(l_url,99);
  
  --strava_http.print_clob(l_clob);
  --strava_sdo.parse_geojson(l_clob);
  
  INSERT INTO stage_geo_data (name, geo_json)
  VALUES ('Northern Ireland', l_clob);

  DBMS_LOB.freetemporary(l_clob);
END;
/
--SELECT UTL_HTTP.get_detailed_sqlerrm FROM dual;
SELECT x.*, length(geo_json) FROM stage_geo_data x;


----------------------------------------------------------------------------------------------------
-- parse json in STAGE_GEO_DATA
----------------------------------------------------------------------------------------------------
clear screen
set serveroutput on echo on timi on
TRUNCATE TABLE stage_my_areas;
--select * from my_area_codes order by 1;
DECLARE 
  l_clob        CLOB;
  j_root        JSON_OBJECT_T;
  j_crs         JSON_OBJECT_T;
  j_features    JSON_ARRAY_T;
  j_feature     JSON_OBJECT_T;
  j_properties  JSON_OBJECT_T;
  j_geometry    JSON_OBJECT_T;

  l_geom        MDSYS.SDO_GEOMETRY;

  l_id       INTEGER;
  l_srid     VARCHAR2(10 char);
  l_name     VARCHAR2(100 char);
  l_county   VARCHAR2(100 char);
  l_num_pts  INTEGER;
  l_offset   NUMBER;
  
  e_json_syntax_error  EXCEPTION;
  PRAGMA exception_init(e_json_syntax_error,-40441);
BEGIN 
  SELECT geo_json INTO l_clob FROM stage_geo_data 
  WHERE name = 'Northern Ireland';
  l_clob := strava_http.clean_clob(l_clob);
  --strava_http.pretty_json(l_clob);
  j_root := JSON_OBJECT_T.parse(l_clob);

  j_crs := j_root.get_object('crs');
  --l_clob := j_crs.to_clob;
  --strava_http.print_clob(l_clob);
	  
  j_features := j_root.get_array('features');
  l_srid     := 4326;
  FOR i IN 0 .. j_features.get_size - 1 LOOP
    j_feature := TREAT(j_features.get(i) AS JSON_OBJECT_T);
    j_properties := j_feature.get_object('properties');
	IF j_properties IS NULL THEN 
	  dbms_output.put_line('J_PROPERTIES is null');
	ELSE
      l_clob := j_properties.to_clob;
	  strava_http.print_clob(l_clob);
	  --l_id               := j_properties.get_string('Id');
	  l_id               := 4e6+i;
	  l_name             := initcap(j_properties.get_string('NAME'));
	  l_county           := initcap(j_properties.get_string('COUNTY'));
	  
      dbms_output.put_line(l_id||', '||l_srid||', '||l_name
	  );
	END IF;

    j_geometry := j_feature.get_object('geometry');
	IF j_geometry IS NULL THEN
	  dbms_output.put_line(l_name||': j_geometry is null');
	  l_offset := NULL;
	  l_geom := NULl;
	  l_num_pts := NULL;
	ELSE
	  -- Get coordinates array
      l_clob := j_geometry.to_clob;
      
      IF i=0 THEN
        NULL;
	    --strava_http.print_clob(l_clob);
	    --strava_http.pretty_json(l_clob);
  	  END IF;

      BEGIN
	    l_geom := sdo_util.from_geojson(l_clob);
	  EXCEPTION 
	    WHEN e_json_syntax_error THEN
		  dbms_output.put_line(sqlerrm||' during parse of '||l_name||'. Switch to own function.' );
    	  l_geom := strava_sdo.build_sdo_geometry_from_geojson(j_geometry, l_srid);
	  END;

	  l_geom.SDO_SRID := TO_NUMBER(l_srid);
	  l_geom := SDO_CS.TRANSFORM(l_geom, 4326);
	  l_geom.SDO_SRID := TO_NUMBER(4326);
      l_geom := sdo_util.rectify_Geometry(SDO_CS.MAKE_2D(l_geom),0.001);	
	  l_num_pts := SDO_UTIL.GETNUMVERTICES(l_geom);
	END IF;
    
    dbms_output.put_line('ID:'||l_id
	      --||', Province:'||l_name
		  --||', County:'||l_county
		  ||', Name:'||l_name
		  ||', '||l_num_pts||' points');
	--dbms_output.put_line(SDO_UTIL.TO_WKTGEOMETRY(l_geom));
	
	INSERT INTO stage_my_areas
	(area_code, area_number, area_level, uqid, name, county, geom, mbr, num_pts
	--, area
	, matchable
	) VALUES
	--NI: GEOU:

	('AONB', l_id, 5, 'NIAONB'||l_id, l_name, l_county, l_geom, sdo_geom.sdo_mbr(l_geom), l_num_pts
	--, SDO_GEOM.SDO_AREA(l_geom, 0.001,'unit=km')
	, 1
	)
	;
  END LOOP;
  Commit;
END;
/

select * from stage_my_areas;

update stage_my_areas
set county = REPLACE(county,'Derry','Londonderry')
where county like '%Derry%'
/

UPDATE stage_my_areas s
set (s.parent_area_code, s.parent_area_number, s.parent_uqid) 
  = (SELECT a.area_code, a.area_number, a.uqid
     FROM   my_areas a
	 WHERE  a.parent_area_code = 'GEOU'
     AND    a.parent_area_number = 1159320745	
     AND    a.parent_uqid = 'NE1159320745'
	 AND    a.name = s.county)
, matchable = 1
, area_level = 5
, name = initcap(name)
/

UPDATE stage_my_areas s
set parent_area_code = 'GEOU'
, parent_area_number = 1159320745	
, parent_uqid = 'NE1159320745'
, matchable = 1
, area_level = 5
, name = initcap(name)
where parent_area_code IS NULL
and   parent_area_code IS NULL
/

UPDATE stage_my_areas
SET    mbr = sdo_geom.sdo_mbr(geom)
,      num_pts = SDO_UTIL.GETNUMVERTICES(geom)
,      area = sdo_geom.sdo_area(geom, unit=>'unit=sq_km')
/

select * from stage_my_areas;
select m.* 
, SDO_UTIL.GETNUMVERTICES(geom) num_pts
, sdo_geom.sdo_area(geom, unit=>'unit=sq_km') area
from my_areas m
--where name = 'Northern Ireland'
where parent_area_code = 'GEOU' AND parent_area_number = 1159320745
/

----------------------------------------------------------------------------------------------------
--identify parent area in my_areas qwert
----------------------------------------------------------------------------------------------------
clear screen
set serveroutput on
DECLARE
  e_general_error EXCEPTION;
PROCEDURE area_hsearch
(p_searchfor_area_code   stage_my_areas.area_code%TYPE
,p_searchfor_area_number stage_my_areas.area_number%TYPE
,p_searchfrom_code        my_areas.area_code%TYPE DEFAULT NULL
,p_searchfrom_number      my_areas.area_number%TYPE DEFAULT NULL
,p_query_type VARCHAR2 DEFAULT 'A'
,p_level INTEGER DEFAULT 0
) IS
  l_t0 timestamp; 
  l_t1 timestamp;
  l_secs NUMBER;
  l_num_rows NUMBER;
  l_pad VARCHAR2(20 CHAR) := '';
BEGIN
  l_pad := lpad('.',p_level,'.');
  l_t0 := SYSTIMESTAMP;
  
  IF p_level >4 then
    RAISE_APPLICATION_ERROR(-20000,'Recurrsion level '||p_level);
  ELSE
    dbms_output.put_line('Searching '||p_searchfor_area_code||'-'||p_searchfor_area_number
	        ||'. '||p_query_type||':'||p_searchfrom_code||'-'||p_searchfrom_number);

  END IF;
  
  FOR i IN(
   WITH x AS (
   SELECT m.area_code, m.area_number, m.name
   ,      new.area_code new_area_code, new.area_number new_area_number, new.name new_name, new.area new_area
   ,      CASE WHEN m.geom  IS NOT NULL AND new.geom IS NOT NULL THEN sdo_geom.sdo_area(SDO_GEOM.sdo_intersection(m.geom,new.geom,0.001), unit=>'unit=sq_km') 
		  END geom_area
   FROM   my_areas m
   ,      stage_my_areas new
   WHERE  (  (p_query_type = 'C' AND m.parent_area_code = p_searchfrom_code AND m.parent_area_number = p_searchfrom_number) 
          OR (p_query_type = 'A' AND m.area_code        = p_searchfrom_code AND m.area_number        = p_searchfrom_number)
		  --OR (p_query_type = 'A' AND p_area_number IS NULL          AND m.area_code          = p_area_code)
          --OR (p_area_code IS NULL AND p_area_number IS NULL AND parent_area_code IS NULL AND parent_area_number IS NULL)
		  )
   AND    new.area_code = p_searchfor_area_code 
   AND    new.area_number = p_searchfor_area_number
   --and    sdo_geom.sdo_intersection(m.mbr,new.mbr,1) IS NOT NULL
   --and    sdo_geom.sdo_intersection(m.geom,new.geom,1) IS NOT NULL
   and    SDO_ANYINTERACT(m.geom, new.geom)
   and    SDO_ANYINTERACT(m.mbr, new.mbr) 
   --and    sdo_geom.RELATE(m.mbr ,'mask=covers',new.mbr ,0.001) 
   --and    sdo_geom.RELATE(m.geom,'mask=covers',new.geom,0.001) 
   --and     m.area_level <7
   and m.rowid != new.rowid
   )
   SELECT * FROM x 
   WHERE geom_area/new_area>=.9
   ORDER BY geom_area desc nulls last fetch first 1 rows only
  ) LOOP
    IF i.geom_area/i.new_area >= .99 THEN
      dbms_output.put_line(l_pad||'Found '||i.area_code||'-'||i.area_number
	                            ||':'||i.name
		  	 	 			    ||', area '||i.new_area||' km^2'
			 				    ||', intersection area '||i.geom_area||' km^2 ('||100*i.geom_area/i.new_area||'%)'
							    );

	  IF i.area_code = p_searchfor_area_code AND i.area_number = p_searchfor_area_number then
	    dbms_output.put_line('Same');
	  ELSE
	    dbms_output.put_line('Updating '||i.area_code||'-'||i.area_number
		            ||' is a parent of '||p_searchfor_area_code||'-'||p_searchfor_area_number);
  	    UPDATE stage_my_areas
	    SET    parent_area_code = i.area_code
	    ,      parent_area_number = i.area_number
	    WHERE  area_code = p_searchfor_area_code 
        AND    area_number = p_searchfor_area_number;
   	    area_hsearch(p_searchfor_area_code, p_searchfor_area_number, i.area_code, i.area_number, 'C', p_level+1);
	  END IF;
	ELSE
      dbms_output.put_line(l_pad||'Not Matched '||i.area_code||'-'||i.area_number
	                            ||':'||i.name
		  	 	 			    ||', area '||i.new_area||' km^2'
			 				    ||', intersection area '||i.geom_area||' km^2 ('||100*i.geom_area/i.new_area||'%)'
							    );
	END IF;
  END LOOP;

  l_t1 := SYSTIMESTAMP;
  l_secs := 60*extract(minute FROM l_t1-l_t0)+extract(second FROM l_t1-l_t0);
  --dbms_output.put_line(l_pad||'Done '||p_searchfor_area_code||'-'||p_searchfor_area_number||':'||TO_CHAR(l_secs,'9990.999')||' secs).');
END area_hsearch;
  ----------------------------------------------------------------------------------------------------
BEGIN
  FOR i IN (
    SELECT * FROM stage_my_areas 
	--WHERE area_code != 'SOVC'
    --AND parent_area_number IS NULL
	--FETCH FIRST 10 ROWS ONLY
  ) LOOP
    area_hsearch(i.area_code, i.area_number, i.parent_area_code, i.parent_area_number, 'A', 0);
	COMMIT;
  END LOOP;
END;
/

----------------------------------------------------------------------------------------------------
-- verify area match 
----------------------------------------------------------------------------------------------------
select m.area_code,m.area_number, m.name, a.name
,      sdo_anyinteract(m.mbr,a.mbr) mbr_interact
,      sdo_anyinteract(m.geom,a.geom) geom_interact
,      sdo_relate(m.geom,a.geom,'OVERLAPBDYINTERSECT') overlapping
,      sdo_relate(m.geom,a.geom,'TOUCH') touching
,      sdo_relate(m.geom,a.geom,'INSIDE') inside
,      sdo_geom.sdo_area(m.geom, unit=>'unit=sq_km') staging_km_sq
,      sdo_geom.sdo_area(sdo_geom.sdo_intersection(m.geom,a.geom,1), unit=>'unit=sq_km') intersect_km_sq    
from stage_my_areas m, my_areas a
where 1=1
and a.area_code = m.parent_area_code
and a.area_number = m.parent_area_number
fetch first 50 rows only
/
----------------------------------------------------------------------------------------------------
-- merge staged areas into areas table
----------------------------------------------------------------------------------------------------
MERGE INTO my_areas u 
USING (select * from stage_my_areas order by area_level) s 
ON (s.area_code = u.area_code AND s.area_number = u.area_number)
WHEN MATCHED THEN UPDATE 
SET u.area_level = s.area_level
, u.parent_area_code = s.parent_area_code 
, u.parent_area_number = s.parent_area_number
, u.name = s.name
, u.matchable = s.matchable
, u.geom = s.geom
, u.mbr = s.mbr
, u.num_pts = s.num_pts
, u.num_children = null
WHEN NOT MATCHED THEN INSERT 
(area_code, area_number, uqid, area_level, parent_area_code, parent_area_number, name, matchable
, geom, mbr, num_pts, num_children)
VALUES
(s.area_code, s.area_number, s.uqid, s.area_level, s.parent_area_code, s.parent_area_number, s.name, s.matchable
, s.geom, s.mbr, s.num_pts, NULL)
/
----------------------------------------------------------------------------------------------------
-- correct parent uqid 
----------------------------------------------------------------------------------------------------
merge into my_areas u
using (
select c.area_level, c.area_code, c.area_number, p.uqid parent_uqid
from my_areas c
  inner join my_areas p
    on p.area_code = c.parent_area_code
    and p.area_number = c.parent_area_number
where c.parent_uqid IS NULL 
and c.parent_area_code IS NOT NULL
order by c.area_level
) s
ON (s.area_code = u.area_code AND s.area_number = u.area_number)
WHEN MATCHED THEN UPDATE 
SET u.parent_uqid = s.parent_uqid
/
----------------------------------------------------------------------------------------------------
--correct count of number of children
----------------------------------------------------------------------------------------------------
merge into my_areas u
using (
select p.area_code, p.area_number, p.name, p.num_children, count(c.area_number) child_count
from my_areas p
  left outer join my_areas c
    on p.area_code = c.parent_area_code
    and p.area_number = c.parent_area_number
where 1=1
--and c.num_children IS NULL
group by p.area_code, p.area_number, p.name, p.num_children
having count(c.area_number) != NVL(p.num_children,0)
) s
ON (s.area_code = u.area_code AND s.area_number = u.area_number)
WHEN MATCHED THEN UPDATE 
SET u.num_children = s.child_count
/
----------------------------------------------------------------------------------------------------
-- force area recalculate on NI
----------------------------------------------------------------------------------------------------
update activities
set processing_status = 3
where processing_status between 4 and 8
and activity_id IN(
select aa.activity_id
from my_areas a
  inner join activity_areas aa on a.area_code = aa.area_code and a.area_number = aa.area_number
where name = 'Northern Ireland')
/