-- Generated by Oracle SQL Developer REST Data Services 24.3.1.347.1826
-- Exported REST Definitions from ORDS Schema Version 25.4.2.r0502119
-- Schema: STRAVA   Date: Fri Mar 13 15:56:57 GMT 2026
--
BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_schema              => 'STRAVA',
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'strava',
      p_auto_rest_auth      => FALSE);    

  ORDS.DEFINE_MODULE(
      p_module_name    => 'placecloud',
      p_base_path      => '/placecloud/',
      p_items_per_page =>  25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'placecloud',
      p_pattern        => 'event',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'placecloud',
      p_pattern        => 'event',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => 'application/json',
      p_comments       => NULL,
      p_source         => 
'
	  DECLARE
	    l_status_code NUMBER;
		l_response    VARCHAR2(200 CHAR);
		l_message     CLOB;
	  BEGIN 
	    strava.webhook_pkg.handle_get(:hub_challenge, :hub_verify_token, l_response, l_status_code, l_message); 
		owa_util.status_line(l_status_code, l_message, FALSE);
        owa_util.mime_header(''application/json'', FALSE);
		:status_code := l_status_code;
        owa_util.http_header_close;
		htp.p(l_response);
		:response := l_response;
	  END;
	  '
      );
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'placecloud',
      p_pattern            => 'event',
      p_method             => 'GET',
      p_name               => 'hub.challenge',
      p_bind_variable_name => 'hub_challenge',
      p_source_type        => 'URI',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'placecloud',
      p_pattern            => 'event',
      p_method             => 'GET',
      p_name               => 'hub.mode',
      p_bind_variable_name => 'hub_mode',
      p_source_type        => 'URI',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'placecloud',
      p_pattern            => 'event',
      p_method             => 'GET',
      p_name               => 'hub.verify_token',
      p_bind_variable_name => 'hub_verify_token',
      p_source_type        => 'URI',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);      
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'placecloud',
      p_pattern        => 'event',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'
	BEGIN strava.webhook_pkg.handle_post(:body_text,:status_code); END;
	'
      );


  COMMIT; 
END;