-- Generated by Oracle SQL Developer REST Data Services 24.3.1.347.1826
-- Exported REST Definitions from ORDS Schema Version 25.4.2.r0502119
-- Schema: STRAVA   Date: Fri Mar 13 15:59:19 GMT 2026
--
BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_schema              => 'STRAVA',
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'strava',
      p_auto_rest_auth      => FALSE);    

  ORDS.CREATE_ROLE(p_role_name  => 'oracle.dbtools.role.autorest.any.STRAVA');
  ORDS.CREATE_ROLE(p_role_name  => 'oracle.dbtools.role.autorest.STRAVA');
  ORDS.CREATE_ROLE(p_role_name  => 'oracle.dbtools.role.autorest.STRAVA.WEBHOOK_EVENTS');


  COMMIT; 
END;