REM placecloud_rest_service.privileges.sql
-- Generated by Oracle SQL Developer REST Data Services 24.3.1.347.1826
-- Exported REST Definitions from ORDS Schema Version 25.4.2.r0502119
-- Schema: STRAVA   Date: Fri Mar 13 15:58:10 GMT 2026
--
DECLARE
  l_roles     OWA.VC_ARR;
  l_modules   OWA.VC_ARR;
  l_patterns  OWA.VC_ARR;
BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_schema              => 'STRAVA',
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'strava',
      p_auto_rest_auth      => FALSE);    

  ORDS.CREATE_ROLE(p_role_name  => 'oracle.dbtools.role.autorest.STRAVA');
  ORDS.CREATE_ROLE(p_role_name  => 'oracle.dbtools.role.autorest.STRAVA.WEBHOOK_EVENTS');
  ORDS.CREATE_ROLE(p_role_name  => 'oracle.dbtools.role.autorest.any.STRAVA');

  l_roles(1)   := 'oracle.dbtools.autorest.any.schema';
  l_roles(2)   := 'oracle.dbtools.role.autorest.STRAVA';

  ORDS.DEFINE_PRIVILEGE(
      p_privilege_name => 'oracle.dbtools.autorest.privilege.STRAVA',
      p_roles          => l_roles,
      p_patterns       => l_patterns,
      p_modules        => l_modules,
      p_label          => 'STRAVA metadata-catalog access',
      p_description    => 'Provides access to the metadata catalog of the objects in the STRAVA schema.',
      p_comments       => NULL);      

  l_roles.DELETE;
  l_modules.DELETE;
  l_patterns.DELETE;

  l_roles(1)   := 'oracle.dbtools.autorest.any.schema';
  l_roles(2)   := 'oracle.dbtools.role.autorest.STRAVA.WEBHOOK_EVENTS';
  l_roles(3)   := 'oracle.dbtools.role.autorest.any.STRAVA';

  ORDS.DEFINE_PRIVILEGE(
      p_privilege_name => 'oracle.dbtools.autorest.privilege.STRAVA.WEBHOOK_EVENTS',
      p_roles          => l_roles,
      p_patterns       => l_patterns,
      p_modules        => l_modules,
      p_label          => 'STRAVA.WEBHOOK_EVENTS access',
      p_description    => 'Provides access to the WEBHOOK_EVENTS TABLE in the STRAVA schema.',
      p_comments       => NULL);      

  l_roles.DELETE;
  l_modules.DELETE;
  l_patterns.DELETE;

  l_roles(1)   := 'SODA Developer';
  l_patterns(1):= '/soda/*';

  ORDS.DEFINE_PRIVILEGE(
      p_privilege_name => 'oracle.soda.privilege.developer',
      p_roles          => l_roles,
      p_patterns       => l_patterns,
      p_modules        => l_modules,
      p_label          => '',
      p_description    => '',
      p_comments       => NULL);      

  COMMIT; 

END;