rem rename_activities_exp.sql
set echo on
clear screen
spool rename_activities_exp.lst
ALTER TABLE ACTIVITIES RENAME TO ACTIVITIES_EXP;

ALTER INDEX ACTIVITIES_PK RENAME TO ACTIVITIES_EXP_pk;
ALTER INDEX ACTIVITIES_MBR RENAME TO ACTIVITIES_EXP_mbr;
ALTER INDEX ACTIVITIES_GEOM RENAME TO ACTIVITIES_EXP_geom;
ALTER INDEX ACTIVITIES_GEOM_27700 RENAME TO ACTIVITIES_EXP_geom_27700;
ALTER INDEX ACTIVITIES_AREA_LIST_TXTIDX RENAME TO ACTIVITIES_EXP__area_list_txtidx;

ALTER TABLE ACTIVITIES_EXP RENAME CONSTRAINT ACTIVITIES_PK to ACTIVITIES_EXP_PK;

ALTER TABLE ACTIVITIES_EXP RENAME LOB (AREA_LIST) ACTIVITIES_AREA_LIST to ACTIVITIES_EMP_AREA_LIST;

spool off
