REM spatial_indexes.sql
set echo ON
spool spatial_indexes.lst

DROP INDEX STRAVA.MY_AREAS_GEOM;
DROP INDEX STRAVA.MY_AREAS_MBR;
DROP INDEX STRAVA.ACTIVITIES_GEOM;
DROP INDEX STRAVA.ACTIVITIES_MBR;

CREATE INDEX STRAVA.MY_AREAS_GEOM   ON STRAVA.MY_AREAS   (GEOM) INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2;
CREATE INDEX STRAVA.MY_AREAS_MBR    ON STRAVA.MY_AREAS   (MBR)  INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2;

CREATE INDEX STRAVA.ACTIVITIES_GEOM ON STRAVA.ACTIVITIES (GEOM) INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2;
CREATE INDEX STRAVA.ACTIVITIES_MBR  ON STRAVA.ACTIVITIES (MBR)  INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2;

spool OFF 

