REM strava_activity_areas_api.sql
clear screen
set echo on timi on
spool strava_activity_areas_api.lst

CREATE TABLE STRAVA.ACTIVITY_AREAS
(ACTIVITY_ID NUMBER      NOT NULL
,AREA_CODE   VARCHAR2(4) NOT NULL
,AREA_NUMBER NUMBER      NOT NULL
,GEOM_LENGTH NUMBER
,CONSTRAINT ACTIVITY_AREAS_PK PRIMARY KEY (ACTIVITY_ID, AREA_CODE, AREA_NUMBER)
,CONSTRAINT ACTIVITY_AREAS_FK FOREIGN KEY (ACTIVITY_ID) REFERENCES STRAVA.ACTIVITIES (ACTIVITY_ID)
,CONSTRAINT ACTIVITY_AREAS_FK2 FOREIGN KEY (AREA_CODE, AREA_NUMBER) REFERENCES STRAVA.MY_AREAS (AREA_CODE, AREA_NUMBER)
);

delete from ACTIVITY_AREAS aa
where not exists(
  select 1 
  from ACTIVITIES a
  where a.activity_id = aa.activity_id)
/

ALTER TABLE STRAVA.ACTIVITY_AREAS DROP CONSTRAINT ACTIVITY_AREAS_FK
/
ALTER TABLE STRAVA.ACTIVITY_AREAS 
ADD CONSTRAINT ACTIVITY_AREAS_FK FOREIGN KEY (ACTIVITY_ID) REFERENCES STRAVA.ACTIVITIES (ACTIVITY_ID)
/

spool off


