REM strava_activities_api.sql
clear screen
set echo on
spool strava_activities_api.lst
--DROP TABLE STRAVA.ACTIVITIES PURGE;

CREATE TABLE STRAVA.ACTIVITIES 
   (ACTIVITY_ID NUMBER NOT NULL, 
    ATHLETE_ID NUMBER NOT NULL, 
	START_DATE_UTC TIMESTAMP NOT NULL, 
	START_DATE_LOCAL TIMESTAMP NOT NULL,
	TIMEZONE VARCHAR2(50 CHAR) NOT NULL,
    UTC_OFFSET NUMBER NOT NULL,
	NAME VARCHAR2(200 CHAR) NOT NULL, 
	TYPE VARCHAR2(15 CHAR) NOT NULL, 
	DEVICE_NAME VARCHAR2(30 CHAR),
	DESCRIPTION CLOB, 
	ELAPSED_TIME NUMBER NOT NULL, 
	DISTANCE_KM NUMBER NOT NULL, 
	GEAR_ID VARCHAR2(20 CHAR),
	GEAR_NAME VARCHAR2(30 CHAR) , 
	MOVING_TIME NUMBER NOT NULL, 
	MAX_SPEED NUMBER, 
	AVERAGE_SPEED NUMBER, 
	ELEVATION_GAIN NUMBER, 
	ELEVATION_HIGH NUMBER, 
	ELEVATION_LOW NUMBER, 
	AVERAGE_WATTS NUMBER, 
	CALORIES NUMBER, 
	KILOJOULES NUMBER,
	TRAINER BOOLEAN NOT NULL, 
	COMMUTE BOOLEAN NOT NULL, 
	MANUAL  BOOLEAN NOT NULL, 
	PRIVATE BOOLEAN NOT NULL, 
	VISIBILITY VARCHAR2(16 CHAR) NOT NULL,
	FLAGGED BOOLEAN, 
	PHOTO_COUNT NUMBER,
	MAP_POLYLINE CLOB,
	----------
	GPX SYS.XMLTYPE , 
	GEOM MDSYS.SDO_GEOMETRY , 
	NUM_PTS NUMBER, 
--  XMLNS VARCHAR2(128 CHAR) , 
	MBR MDSYS.SDO_GEOMETRY , 
--	GEOM_27700 MDSYS.SDO_GEOMETRY , 
	AREA_LIST CLOB , 
	SIGNATURE VARCHAR2(64),
	PROCESSING_STATUS NUMBER NOT NULL DEFAULT 0;
    last_updated TIMESTAMP WITH TIMEZONE DEFAULT SYSTIMESTAMP,
    CONSTRAINT ACTIVITIES_PK PRIMARY KEY (ACTIVITY_ID)
   )  --DEFAULT COLLATION USING_NLS_COMP  
XMLTYPE COLUMN GPX STORE AS SECUREFILE BINARY XML        (ENABLE STORAGE IN ROW 4000 COMPRESS HIGH DEDUPLICATE LOB) --ALLOW NONSCHEMA DISALLOW ANYSCHEMA 
VARRAY GEOM.SDO_ELEM_INFO STORE AS SECUREFILE LOB        (ENABLE STORAGE IN ROW 4000 COMPRESS HIGH DEDUPLICATE LOB) 
VARRAY GEOM.SDO_ORDINATES STORE AS SECUREFILE LOB        (ENABLE STORAGE IN ROW 4000 COMPRESS HIGH DEDUPLICATE LOB) 
VARRAY MBR.SDO_ELEM_INFO STORE AS SECUREFILE LOB         (ENABLE STORAGE IN ROW 4000 COMPRESS HIGH DEDUPLICATE LOB) 
VARRAY MBR.SDO_ORDINATES STORE AS SECUREFILE LOB         (ENABLE STORAGE IN ROW 4000 COMPRESS HIGH DEDUPLICATE LOB) 
--VARRAY GEOM_27700.SDO_ELEM_INFO STORE AS SECUREFILE LOB  (ENABLE STORAGE IN ROW 4000 COMPRESS HIGH DEDUPLICATE LOB) 
--VARRAY GEOM_27700.SDO_ORDINATES STORE AS SECUREFILE LOB  (ENABLE STORAGE IN ROW 4000 COMPRESS HIGH DEDUPLICATE LOB) 
LOB (DESCRIPTION) STORE AS SECUREFILE                    (ENABLE STORAGE IN ROW 4000 COMPRESS HIGH DEDUPLICATE LOB)
LOB (MAP_POLYLINE) STORE AS SECUREFILE                   (ENABLE STORAGE IN ROW 4000 COMPRESS HIGH DEDUPLICATE LOB)
LOB (AREA_LIST) STORE AS SECUREFILE                      (ENABLE STORAGE IN ROW 4000 COMPRESS HIGH DEDUPLICATE LOB)
 /

ALTER TABLE ACTIVITIES ADD PROCESSING_STATUS NUMBER;
ALTER TABLE ACTIVITIES MODIFY PROCESSING_STATUS DEFAULT 0 NOT NULL;
ALTER TABLE ACTIVITIES MODIFY START_DATE_LOCAL  NOT NULL;
ALTER TABLE ACTIVITIES MODIFY TIMEZONE          NOT NULL;
ALTER TABLE ACTIVITIES MODIFY UTC_OFFSET        NOT NULL;
ALTER TABLE ACTIVITIES MODIFY TRAINER           NOT NULL;
ALTER TABLE ACTIVITIES MODIFY COMMUTE           NOT NULL;
ALTER TABLE ACTIVITIES MODIFY MANUAL            NOT NULL;
ALTER TABLE ACTIVITIES MODIFY PRIVATE           NOT NULL;
ALTER TABLE ACTIVITIES MODIFY VISIBILITY        NOT NULL;
ALTER TABLE ACTIVITIES MODIFY FLAGGED           NOT NULL;
ALTER TABLE ACTIVITIES MODIFY PHOTO_COUNT       NOT NULL;

CREATE OR REPLACE TRIGGER strava.activities_last_updated
BEFORE INSERT OR UPDATE ON activities
FOR EACH ROW
BEGIN
  :new.last_updated := SYSTIMESTAMP;
END;
/
show errors


--abandon british nation grid
update activities
set geom_27700 = NULL
where geom_27700 is not null
/

CREATE INDEX STRAVA.ACTIVITIES_GEOM ON STRAVA.ACTIVITIES (GEOM) 
INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2 
/

--CREATE INDEX STRAVA.ACTIVITIES_GEOM_27700 ON STRAVA.ACTIVITIES (GEOM_27700) 
--INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2 
--/

CREATE INDEX STRAVA.ACTIVITIES_MBR ON STRAVA.ACTIVITIES (MBR) 
INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2 
/

drop index STRAVA.ACTIVITIES_GEOM_27700 
/
alter table ACTIVITIES drop column GEOM_27700
/


DROP INDEX STRAVA.ACTIVITIES_AREA_LIST_TXTIDX ;
CREATE INDEX STRAVA.ACTIVITIES_AREA_LIST_TXTIDX ON STRAVA.ACTIVITIES (AREA_LIST) 
INDEXTYPE IS CTXSYS.CONTEXT  PARAMETERS ('datastore activities_datastore lexer activities_lexer sync(on commit)')


/*add timezone to last_updated column
create table activities_tmp as
select activity_id, last_updated
from activities 
where last_updated is not null;
select * from activities_tmp;
alter TRIGGER strava.activities_last_updated disable;
update activities set last_updated = NULL where last_updated is not null;
alter table activities modify last_updated timestamp with time zone;
merge into activities u
using (select * from activities_tmp) s
on (s.activity_id = u.activity_id)
when matched then update
set u.last_updated = s.last_updated;
alter table activities modify last_updated not null;
alter TRIGGER strava.activities_last_updated enable;
drop table activities_tmp purge;
*/
desc activities


drop index STRAVA.ACTIVITIES_GEOM_27700 
/
alter table ACTIVITIES drop column GEOM_27700
/
alter table ACTIVITIES move tablespace data 
/


select * from user_lobs where column_name like '%27700%' order by 1,2;

alter index activities_pk rebuild;
alter index activities_mbr rebuild;
alter index activities_geom rebuild;


spool off

